// 自动生成：由 scripts 扫描 public/moko/collection/ 生成，请勿手改。
// 重新生成：node scripts/gen-moko-collection.js
import type { MokoChar, MokoCategoryKey } from './types';

export interface MokoCollectionCat {
  key: MokoCategoryKey;
  label: string;
  emoji: string;
  color: string;
  desc: string;
}

/** 本次新增的季分类（需并入 MOko_CATEGORIES） */
export const COLLECTION_CATEGORIES: MokoCollectionCat[] = [
  {
    "key": "mo",
    "label": "魔方萌可",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "desc": "第一、二季的魔法萌可"
  },
  {
    "key": "prince",
    "label": "王子萌可",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "desc": "守护王国的王子们"
  },
  {
    "key": "villain",
    "label": "反派萌可",
    "emoji": "😈",
    "color": "text-slate-500",
    "desc": "搞怪的反派与神秘角色"
  },
  {
    "key": "legend",
    "label": "传奇萌可",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "desc": "传说中的特别萌可"
  }
];

/** 全部萌可图片（165 张，2026-07-31 官网更新批次），key 以 col_ 前缀，category 见上 */
export const mokoCollection: MokoChar[] = [
  {
    "key": "col_01_优雅萌可_render",
    "name": "优雅萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/优雅萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是优雅萌可！"
  },
  {
    "key": "col_01_信信萌可_render",
    "name": "信信萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/信信萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是信信萌可！"
  },
  {
    "key": "col_01_勇气萌可_render",
    "name": "勇气萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/勇气萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是勇气萌可！"
  },
  {
    "key": "col_01_唱唱萌可_render",
    "name": "唱唱萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/唱唱萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是唱唱萌可！"
  },
  {
    "key": "col_01_好好萌可_render",
    "name": "好好萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/好好萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是好好萌可！"
  },
  {
    "key": "col_01_幸福萌可_render",
    "name": "幸福萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/幸福萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是幸福萌可！"
  },
  {
    "key": "col_01_星光萌可_render",
    "name": "星光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/星光萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是星光萌可！"
  },
  {
    "key": "col_01_月光萌可_18",
    "name": "月光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/月光萌可_18.jpg",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是月光萌可！"
  },
  {
    "key": "col_01_正正萌可_render",
    "name": "正正萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/正正萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是正正萌可！"
  },
  {
    "key": "col_01_漂亮萌可_render",
    "name": "漂亮萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/漂亮萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是漂亮萌可！"
  },
  {
    "key": "col_01_热情萌可_render",
    "name": "热情萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/热情萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是热情萌可！"
  },
  {
    "key": "col_01_爱心萌可_render",
    "name": "爱心萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/爱心萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是爱心萌可！"
  },
  {
    "key": "col_01_王子萌可_render",
    "name": "王子萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/王子萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是王子萌可！"
  },
  {
    "key": "col_01_盼盼萌可_render",
    "name": "盼盼萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/盼盼萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是盼盼萌可！"
  },
  {
    "key": "col_01_笑笑萌可_render",
    "name": "笑笑萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/笑笑萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是笑笑萌可！"
  },
  {
    "key": "col_01_绵绵萌可_render",
    "name": "绵绵萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/绵绵萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是绵绵萌可！"
  },
  {
    "key": "col_01_美丽萌可_render",
    "name": "美丽萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/美丽萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是美丽萌可！"
  },
  {
    "key": "col_01_诚实萌可_render",
    "name": "诚实萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/诚实萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是诚实萌可！"
  },
  {
    "key": "col_01_赞赞萌可_render",
    "name": "赞赞萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/赞赞萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是赞赞萌可！"
  },
  {
    "key": "col_01_软软萌可_render",
    "name": "软软萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/软软萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是软软萌可！"
  },
  {
    "key": "col_01_银光萌可_render",
    "name": "银光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/银光萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是银光萌可！"
  },
  {
    "key": "col_01_闪闪萌可_render",
    "name": "闪闪萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/闪闪萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是闪闪萌可！"
  },
  {
    "key": "col_02_乖乖萌可_13",
    "name": "乖乖萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/乖乖萌可_13.jpg",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是乖乖萌可！"
  },
  {
    "key": "col_02_仿仿萌可_render",
    "name": "仿仿萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/仿仿萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是仿仿萌可！"
  },
  {
    "key": "col_02_倒倒萌可_render",
    "name": "倒倒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/倒倒萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是倒倒萌可！"
  },
  {
    "key": "col_02_八卦萌可_render",
    "name": "八卦萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/八卦萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是八卦萌可！"
  },
  {
    "key": "col_02_冰冰萌可_34",
    "name": "冰冰萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/冰冰萌可_34.jpg",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是冰冰萌可！"
  },
  {
    "key": "col_02_冷冷萌可_render",
    "name": "冷冷萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/冷冷萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是冷冷萌可！"
  },
  {
    "key": "col_02_厌厌萌可_render",
    "name": "厌厌萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/厌厌萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是厌厌萌可！"
  },
  {
    "key": "col_02_变身萌可_render",
    "name": "变身萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/变身萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是变身萌可！"
  },
  {
    "key": "col_02_叹气萌可_render",
    "name": "叹气萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/叹气萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是叹气萌可！"
  },
  {
    "key": "col_02_否否萌可_render",
    "name": "否否萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/否否萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是否否萌可！"
  },
  {
    "key": "col_02_好奇萌可_render",
    "name": "好奇萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/好奇萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是好奇萌可！"
  },
  {
    "key": "col_02_妒妒萌可_render",
    "name": "妒妒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/妒妒萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是妒妒萌可！"
  },
  {
    "key": "col_02_妖妖萌可_render",
    "name": "妖妖萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/妖妖萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是妖妖萌可！"
  },
  {
    "key": "col_02_娇娇萌可_render",
    "name": "娇娇萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/娇娇萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是娇娇萌可！"
  },
  {
    "key": "col_02_孤独萌可_render",
    "name": "孤独萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/孤独萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是孤独萌可！"
  },
  {
    "key": "col_02_宝宝萌可_render",
    "name": "宝宝萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/宝宝萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是宝宝萌可！"
  },
  {
    "key": "col_02_害羞萌可_render",
    "name": "害羞萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/害羞萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是害羞萌可！"
  },
  {
    "key": "col_02_幻幻萌可_render",
    "name": "幻幻萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/幻幻萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是幻幻萌可！"
  },
  {
    "key": "col_02_怒怒萌可_render",
    "name": "怒怒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/怒怒萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是怒怒萌可！"
  },
  {
    "key": "col_02_怕怕萌可_render",
    "name": "怕怕萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/怕怕萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是怕怕萌可！"
  },
  {
    "key": "col_02_恋恋萌可_render",
    "name": "恋恋萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/恋恋萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是恋恋萌可！"
  },
  {
    "key": "col_02_泪泪萌可_render",
    "name": "泪泪萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/泪泪萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是泪泪萌可！"
  },
  {
    "key": "col_02_淘气萌可_render",
    "name": "淘气萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/淘气萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是淘气萌可！"
  },
  {
    "key": "col_02_玩具萌可_render",
    "name": "玩具萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩具萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是玩具萌可！"
  },
  {
    "key": "col_02_玩玩萌可_render",
    "name": "玩玩萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩玩萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是玩玩萌可！"
  },
  {
    "key": "col_02_电电萌可_render",
    "name": "电电萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/电电萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是电电萌可！"
  },
  {
    "key": "col_02_画画萌可_render",
    "name": "画画萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/画画萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是画画萌可！"
  },
  {
    "key": "col_02_睡睡萌可_render",
    "name": "睡睡萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/睡睡萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是睡睡萌可！"
  },
  {
    "key": "col_02_美美萌可_render",
    "name": "美美萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/美美萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是美美萌可！"
  },
  {
    "key": "col_02_聪明萌可_render",
    "name": "聪明萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/聪明萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是聪明萌可！"
  },
  {
    "key": "col_02_花花萌可_render",
    "name": "花花萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/花花萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是花花萌可！"
  },
  {
    "key": "col_02_贪贪萌可_render",
    "name": "贪贪萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/贪贪萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是贪贪萌可！"
  },
  {
    "key": "col_02_赛赛萌可_render",
    "name": "赛赛萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/赛赛萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是赛赛萌可！"
  },
  {
    "key": "col_02_迷糊萌可_render",
    "name": "迷糊萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/迷糊萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是迷糊萌可！"
  },
  {
    "key": "col_02_速速萌可_render",
    "name": "速速萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/速速萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是速速萌可！"
  },
  {
    "key": "col_02_重重萌可_render",
    "name": "重重萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/重重萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是重重萌可！"
  },
  {
    "key": "col_02_黏黏萌可_render",
    "name": "黏黏萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/黏黏萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是黏黏萌可！"
  },
  {
    "key": "col_03_公主萌可_render",
    "name": "公主萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/公主萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是公主萌可！"
  },
  {
    "key": "col_03_净净萌可_render",
    "name": "净净萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/净净萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是净净萌可！"
  },
  {
    "key": "col_03_分享萌可_render",
    "name": "分享萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/分享萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是分享萌可！"
  },
  {
    "key": "col_03_双双萌可_render",
    "name": "双双萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/双双萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是双双萌可！"
  },
  {
    "key": "col_03_嘻嘻萌可_render",
    "name": "嘻嘻萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/嘻嘻萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是嘻嘻萌可！"
  },
  {
    "key": "col_03_安慰萌可_render",
    "name": "安慰萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/安慰萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是安慰萌可！"
  },
  {
    "key": "col_03_弱弱萌可_02",
    "name": "弱弱萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/弱弱萌可_02.jpg",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是弱弱萌可！"
  },
  {
    "key": "col_03_愿望萌可_03",
    "name": "愿望萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/愿望萌可_03.jpg",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是愿望萌可！"
  },
  {
    "key": "col_03_暖暖萌可_render",
    "name": "暖暖萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/暖暖萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是暖暖萌可！"
  },
  {
    "key": "col_03_神奇萌可_render",
    "name": "神奇萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/神奇萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是神奇萌可！"
  },
  {
    "key": "col_03_笔记萌可_render",
    "name": "笔记萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/笔记萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是笔记萌可！"
  },
  {
    "key": "col_03_美味萌可_render",
    "name": "美味萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/美味萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是美味萌可！"
  },
  {
    "key": "col_03_芭蕾萌可_render",
    "name": "芭蕾萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/芭蕾萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是芭蕾萌可！"
  },
  {
    "key": "col_03_躲躲萌可_render",
    "name": "躲躲萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/躲躲萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是躲躲萌可！"
  },
  {
    "key": "col_03_雕刻萌可_render",
    "name": "雕刻萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/雕刻萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是雕刻萌可！"
  },
  {
    "key": "col_04_人鱼萌可_10",
    "name": "人鱼萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/人鱼萌可_10.jpg",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是人鱼萌可！"
  },
  {
    "key": "col_04_修理萌可_render",
    "name": "修理萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/修理萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是修理萌可！"
  },
  {
    "key": "col_04_加油萌可_render",
    "name": "加油萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/加油萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是加油萌可！"
  },
  {
    "key": "col_04_医生萌可_render",
    "name": "医生萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/医生萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是医生萌可！"
  },
  {
    "key": "col_04_发明萌可_render",
    "name": "发明萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/发明萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是发明萌可！"
  },
  {
    "key": "col_04_吞吞萌可_render",
    "name": "吞吞萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/吞吞萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是吞吞萌可！"
  },
  {
    "key": "col_04_快快萌可_render",
    "name": "快快萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/快快萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是快快萌可！"
  },
  {
    "key": "col_04_时尚萌可_render",
    "name": "时尚萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/时尚萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是时尚萌可！"
  },
  {
    "key": "col_04_歌声萌可_render",
    "name": "歌声萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/歌声萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是歌声萌可！"
  },
  {
    "key": "col_04_气气萌可_render",
    "name": "气气萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/气气萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是气气萌可！"
  },
  {
    "key": "col_04_派对萌可_render",
    "name": "派对萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/派对萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是派对萌可！"
  },
  {
    "key": "col_04_滑冰萌可_render",
    "name": "滑冰萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/滑冰萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是滑冰萌可！"
  },
  {
    "key": "col_04_灭火萌可_03",
    "name": "灭火萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/灭火萌可_03.jpg",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是灭火萌可！"
  },
  {
    "key": "col_04_美发萌可_12",
    "name": "美发萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/美发萌可_12.jpg",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是美发萌可！"
  },
  {
    "key": "col_04_警察萌可_render",
    "name": "警察萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/警察萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是警察萌可！"
  },
  {
    "key": "col_05_冰沙萌可_render",
    "name": "冰沙萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/冰沙萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是冰沙萌可！"
  },
  {
    "key": "col_05_华夫萌可_render",
    "name": "华夫萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/华夫萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是华夫萌可！"
  },
  {
    "key": "col_05_夹心萌可_render",
    "name": "夹心萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/夹心萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是夹心萌可！"
  },
  {
    "key": "col_05_奶油萌可_render",
    "name": "奶油萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/奶油萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是奶油萌可！"
  },
  {
    "key": "col_05_巧克力萌可_render",
    "name": "巧克力萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/巧克力萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是巧克力萌可！"
  },
  {
    "key": "col_05_布丁萌可_render",
    "name": "布丁萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/布丁萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是布丁萌可！"
  },
  {
    "key": "col_05_松饼萌可_render",
    "name": "松饼萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/松饼萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是松饼萌可！"
  },
  {
    "key": "col_05_棉花糖萌可_13",
    "name": "棉花糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/棉花糖萌可_13.jpg",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是棉花糖萌可！"
  },
  {
    "key": "col_05_棒棒糖萌可_render",
    "name": "棒棒糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/棒棒糖萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是棒棒糖萌可！"
  },
  {
    "key": "col_05_泡泡萌可_render",
    "name": "泡泡萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/泡泡萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是泡泡萌可！"
  },
  {
    "key": "col_05_甜甜圈萌可_render",
    "name": "甜甜圈萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/甜甜圈萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是甜甜圈萌可！"
  },
  {
    "key": "col_05_糖糖萌可_render",
    "name": "糖糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/糖糖萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是糖糖萌可！"
  },
  {
    "key": "col_05_蛋糕妹妹萌可_01",
    "name": "蛋糕妹妹萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕妹妹萌可_01.jpg",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是蛋糕妹妹萌可！"
  },
  {
    "key": "col_05_蛋糕妹妹萌可_蛋糕弟弟萌可_09",
    "name": "蛋糕妹妹萌可·蛋糕弟弟萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕妹妹萌可_蛋糕弟弟萌可_09.jpg",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是蛋糕妹妹萌可·蛋糕弟弟萌可！"
  },
  {
    "key": "col_05_蛋糕弟弟萌可_01",
    "name": "蛋糕弟弟萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕弟弟萌可_01.jpg",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是蛋糕弟弟萌可！"
  },
  {
    "key": "col_05_酸奶萌可_render",
    "name": "酸奶萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/酸奶萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是酸奶萌可！"
  },
  {
    "key": "col_05_马卡龙萌可_render",
    "name": "马卡龙萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/马卡龙萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是马卡龙萌可！"
  },
  {
    "key": "col_06_乐美萌可_01",
    "name": "乐美萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/乐美萌可_01.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是乐美萌可！"
  },
  {
    "key": "col_06_亲亲萌可_render",
    "name": "亲亲萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/亲亲萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是亲亲萌可！"
  },
  {
    "key": "col_06_光明萌可_render",
    "name": "光明萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/光明萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是光明萌可！"
  },
  {
    "key": "col_06_兔兔萌可_01",
    "name": "兔兔萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/兔兔萌可_01.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是兔兔萌可！"
  },
  {
    "key": "col_06_共共萌可_render",
    "name": "共共萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/共共萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是共共萌可！"
  },
  {
    "key": "col_06_动动萌可_render",
    "name": "动动萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/动动萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是动动萌可！"
  },
  {
    "key": "col_06_叮咚萌可_render",
    "name": "叮咚萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/叮咚萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是叮咚萌可！"
  },
  {
    "key": "col_06_呼啦萌可_render",
    "name": "呼啦萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/呼啦萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是呼啦萌可！"
  },
  {
    "key": "col_06_悄悄萌可_render",
    "name": "悄悄萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/悄悄萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是悄悄萌可！"
  },
  {
    "key": "col_06_歌谣萌可_15",
    "name": "歌谣萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/歌谣萌可_15.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是歌谣萌可！"
  },
  {
    "key": "col_06_流浪萌可_render",
    "name": "流浪萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/流浪萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是流浪萌可！"
  },
  {
    "key": "col_06_熊熊萌可_08",
    "name": "熊熊萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/熊熊萌可_08.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是熊熊萌可！"
  },
  {
    "key": "col_06_狐狐萌可_14",
    "name": "狐狐萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/狐狐萌可_14.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是狐狐萌可！"
  },
  {
    "key": "col_06_纷纷萌可_01",
    "name": "纷纷萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/纷纷萌可_01.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是纷纷萌可！"
  },
  {
    "key": "col_06_绵羊萌可_10",
    "name": "绵羊萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/绵羊萌可_10.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是绵羊萌可！"
  },
  {
    "key": "col_06_缤缤萌可_01",
    "name": "缤缤萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/缤缤萌可_01.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是缤缤萌可！"
  },
  {
    "key": "col_06_缤缤萌可_纷纷萌可_09",
    "name": "缤缤萌可·纷纷萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/缤缤萌可_纷纷萌可_09.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是缤缤萌可·纷纷萌可！"
  },
  {
    "key": "col_06_贴贴萌可_render",
    "name": "贴贴萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/贴贴萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是贴贴萌可！"
  },
  {
    "key": "col_06_跳舞萌可_render",
    "name": "跳舞萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/跳舞萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是跳舞萌可！"
  },
  {
    "key": "col_06_透明萌可_11",
    "name": "透明萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/透明萌可_11.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是透明萌可！"
  },
  {
    "key": "col_07_丘比特萌可_render",
    "name": "丘比特萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/丘比特萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是丘比特萌可！"
  },
  {
    "key": "col_07_丝绸萌可_render",
    "name": "丝绸萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/丝绸萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是丝绸萌可！"
  },
  {
    "key": "col_07_困困萌可_07",
    "name": "困困萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/困困萌可_07.jpg",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是困困萌可！"
  },
  {
    "key": "col_07_洗洗萌可_render",
    "name": "洗洗萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/洗洗萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是洗洗萌可！"
  },
  {
    "key": "col_07_猫猫萌可_render",
    "name": "猫猫萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/猫猫萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是猫猫萌可！"
  },
  {
    "key": "col_07_玲珑萌可_09",
    "name": "玲珑萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/玲珑萌可_09.jpg",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是玲珑萌可！"
  },
  {
    "key": "col_07_白雪萌可_render",
    "name": "白雪萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/白雪萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是白雪萌可！"
  },
  {
    "key": "col_07_蝴蝶萌可_render",
    "name": "蝴蝶萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/蝴蝶萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是蝴蝶萌可！"
  },
  {
    "key": "col_07_露水萌可_render",
    "name": "露水萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/露水萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是露水萌可！"
  },
  {
    "key": "col_07_鞋鞋萌可_08",
    "name": "鞋鞋萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/鞋鞋萌可_08.jpg",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是鞋鞋萌可！"
  },
  {
    "key": "col_07_魅力萌可_render",
    "name": "魅力萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/魅力萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是魅力萌可！"
  },
  {
    "key": "col_08_查尔斯萌可_render",
    "name": "查尔斯萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/查尔斯萌可_render.png",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是查尔斯萌可！"
  },
  {
    "key": "col_08_演歌萌可_01",
    "name": "演歌萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/演歌萌可_01.jpg",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是演歌萌可！"
  },
  {
    "key": "col_08_绅士萌可_01",
    "name": "绅士萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/绅士萌可_01.jpg",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是绅士萌可！"
  },
  {
    "key": "col_08_青蛙萌可_01",
    "name": "青蛙萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/青蛙萌可_01.jpg",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是青蛙萌可！"
  },
  {
    "key": "col_09_extra_18",
    "name": "神秘萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/extra_18.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是神秘萌可！"
  },
  {
    "key": "col_09_其他萌可_01",
    "name": "其他萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/其他萌可_01.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是其他萌可！"
  },
  {
    "key": "col_09_其他萌可_02",
    "name": "其他萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/其他萌可_02.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是其他萌可！"
  },
  {
    "key": "col_09_其他萌可_03",
    "name": "其他萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/其他萌可_03.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是其他萌可！"
  },
  {
    "key": "col_09_其他萌可_04",
    "name": "其他萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/其他萌可_04.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是其他萌可！"
  },
  {
    "key": "col_09_其他萌可_05",
    "name": "其他萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/其他萌可_05.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是其他萌可！"
  },
  {
    "key": "col_09_其他萌可_06",
    "name": "其他萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/其他萌可_06.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是其他萌可！"
  },
  {
    "key": "col_09_其他萌可_07",
    "name": "其他萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/其他萌可_07.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是其他萌可！"
  },
  {
    "key": "col_09_其他萌可_08",
    "name": "其他萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/其他萌可_08.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是其他萌可！"
  },
  {
    "key": "col_09_其他萌可_09",
    "name": "其他萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/其他萌可_09.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是其他萌可！"
  },
  {
    "key": "col_09_其他萌可_10",
    "name": "其他萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/其他萌可_10.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是其他萌可！"
  },
  {
    "key": "col_09_士兵萌可_01",
    "name": "士兵萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/士兵萌可_01.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是士兵萌可！"
  },
  {
    "key": "col_09_奉献萌可_01",
    "name": "奉献萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/奉献萌可_01.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是奉献萌可！"
  },
  {
    "key": "col_09_泡泡萌可_01",
    "name": "泡泡萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/泡泡萌可_01.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是泡泡萌可！"
  },
  {
    "key": "col_09_波荡萌可_01",
    "name": "波荡萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/波荡萌可_01.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是波荡萌可！"
  },
  {
    "key": "col_09_铃铛萌可_01",
    "name": "铃铛萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/铃铛萌可_01.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是铃铛萌可！"
  },
  {
    "key": "col_09_闹闹萌可_render",
    "name": "闹闹萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/闹闹萌可_render.png",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是闹闹萌可！"
  },
  {
    "key": "col_09_黑暗萌可_01",
    "name": "黑暗萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/黑暗萌可_01.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是黑暗萌可！"
  },
  {
    "key": "col_10_幸运萌可_render",
    "name": "幸运萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/幸运萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是幸运萌可！"
  },
  {
    "key": "col_10_月神萌可_01",
    "name": "月神萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/月神萌可_01.jpg",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是月神萌可！"
  },
  {
    "key": "col_10_月食萌可_01",
    "name": "月食萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/月食萌可_01.jpg",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是月食萌可！"
  },
  {
    "key": "col_10_极光萌可_render",
    "name": "极光萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/极光萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是极光萌可！"
  },
  {
    "key": "col_10_甜甜萌可_render",
    "name": "甜甜萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/甜甜萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是甜甜萌可！"
  },
  {
    "key": "col_10_酸酸萌可_render",
    "name": "酸酸萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/酸酸萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是酸酸萌可！"
  }
];

/** 同名首图（用于把核心萌可的 img 重映射到真实图片） */
export const mokoCollectionByName: Record<string, MokoChar> = {
  "优雅萌可": {
    "key": "col_01_优雅萌可_render",
    "name": "优雅萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/优雅萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是优雅萌可！"
  },
  "信信萌可": {
    "key": "col_01_信信萌可_render",
    "name": "信信萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/信信萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是信信萌可！"
  },
  "勇气萌可": {
    "key": "col_01_勇气萌可_render",
    "name": "勇气萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/勇气萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是勇气萌可！"
  },
  "唱唱萌可": {
    "key": "col_01_唱唱萌可_render",
    "name": "唱唱萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/唱唱萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是唱唱萌可！"
  },
  "好好萌可": {
    "key": "col_01_好好萌可_render",
    "name": "好好萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/好好萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是好好萌可！"
  },
  "幸福萌可": {
    "key": "col_01_幸福萌可_render",
    "name": "幸福萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/幸福萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是幸福萌可！"
  },
  "星光萌可": {
    "key": "col_01_星光萌可_render",
    "name": "星光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/星光萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是星光萌可！"
  },
  "月光萌可": {
    "key": "col_01_月光萌可_18",
    "name": "月光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/月光萌可_18.jpg",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是月光萌可！"
  },
  "正正萌可": {
    "key": "col_01_正正萌可_render",
    "name": "正正萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/正正萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是正正萌可！"
  },
  "漂亮萌可": {
    "key": "col_01_漂亮萌可_render",
    "name": "漂亮萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/漂亮萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是漂亮萌可！"
  },
  "热情萌可": {
    "key": "col_01_热情萌可_render",
    "name": "热情萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/热情萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是热情萌可！"
  },
  "爱心萌可": {
    "key": "col_01_爱心萌可_render",
    "name": "爱心萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/爱心萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是爱心萌可！"
  },
  "王子萌可": {
    "key": "col_01_王子萌可_render",
    "name": "王子萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/王子萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是王子萌可！"
  },
  "盼盼萌可": {
    "key": "col_01_盼盼萌可_render",
    "name": "盼盼萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/盼盼萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是盼盼萌可！"
  },
  "笑笑萌可": {
    "key": "col_01_笑笑萌可_render",
    "name": "笑笑萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/笑笑萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是笑笑萌可！"
  },
  "绵绵萌可": {
    "key": "col_01_绵绵萌可_render",
    "name": "绵绵萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/绵绵萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是绵绵萌可！"
  },
  "美丽萌可": {
    "key": "col_01_美丽萌可_render",
    "name": "美丽萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/美丽萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是美丽萌可！"
  },
  "诚实萌可": {
    "key": "col_01_诚实萌可_render",
    "name": "诚实萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/诚实萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是诚实萌可！"
  },
  "赞赞萌可": {
    "key": "col_01_赞赞萌可_render",
    "name": "赞赞萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/赞赞萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是赞赞萌可！"
  },
  "软软萌可": {
    "key": "col_01_软软萌可_render",
    "name": "软软萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/软软萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是软软萌可！"
  },
  "银光萌可": {
    "key": "col_01_银光萌可_render",
    "name": "银光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/银光萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是银光萌可！"
  },
  "闪闪萌可": {
    "key": "col_01_闪闪萌可_render",
    "name": "闪闪萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/闪闪萌可_render.png",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是闪闪萌可！"
  },
  "乖乖萌可": {
    "key": "col_02_乖乖萌可_13",
    "name": "乖乖萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/乖乖萌可_13.jpg",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是乖乖萌可！"
  },
  "仿仿萌可": {
    "key": "col_02_仿仿萌可_render",
    "name": "仿仿萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/仿仿萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是仿仿萌可！"
  },
  "倒倒萌可": {
    "key": "col_02_倒倒萌可_render",
    "name": "倒倒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/倒倒萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是倒倒萌可！"
  },
  "八卦萌可": {
    "key": "col_02_八卦萌可_render",
    "name": "八卦萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/八卦萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是八卦萌可！"
  },
  "冰冰萌可": {
    "key": "col_02_冰冰萌可_34",
    "name": "冰冰萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/冰冰萌可_34.jpg",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是冰冰萌可！"
  },
  "冷冷萌可": {
    "key": "col_02_冷冷萌可_render",
    "name": "冷冷萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/冷冷萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是冷冷萌可！"
  },
  "厌厌萌可": {
    "key": "col_02_厌厌萌可_render",
    "name": "厌厌萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/厌厌萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是厌厌萌可！"
  },
  "变身萌可": {
    "key": "col_02_变身萌可_render",
    "name": "变身萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/变身萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是变身萌可！"
  },
  "叹气萌可": {
    "key": "col_02_叹气萌可_render",
    "name": "叹气萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/叹气萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是叹气萌可！"
  },
  "否否萌可": {
    "key": "col_02_否否萌可_render",
    "name": "否否萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/否否萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是否否萌可！"
  },
  "好奇萌可": {
    "key": "col_02_好奇萌可_render",
    "name": "好奇萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/好奇萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是好奇萌可！"
  },
  "妒妒萌可": {
    "key": "col_02_妒妒萌可_render",
    "name": "妒妒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/妒妒萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是妒妒萌可！"
  },
  "妖妖萌可": {
    "key": "col_02_妖妖萌可_render",
    "name": "妖妖萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/妖妖萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是妖妖萌可！"
  },
  "娇娇萌可": {
    "key": "col_02_娇娇萌可_render",
    "name": "娇娇萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/娇娇萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是娇娇萌可！"
  },
  "孤独萌可": {
    "key": "col_02_孤独萌可_render",
    "name": "孤独萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/孤独萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是孤独萌可！"
  },
  "宝宝萌可": {
    "key": "col_02_宝宝萌可_render",
    "name": "宝宝萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/宝宝萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是宝宝萌可！"
  },
  "害羞萌可": {
    "key": "col_02_害羞萌可_render",
    "name": "害羞萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/害羞萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是害羞萌可！"
  },
  "幻幻萌可": {
    "key": "col_02_幻幻萌可_render",
    "name": "幻幻萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/幻幻萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是幻幻萌可！"
  },
  "怒怒萌可": {
    "key": "col_02_怒怒萌可_render",
    "name": "怒怒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/怒怒萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是怒怒萌可！"
  },
  "怕怕萌可": {
    "key": "col_02_怕怕萌可_render",
    "name": "怕怕萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/怕怕萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是怕怕萌可！"
  },
  "恋恋萌可": {
    "key": "col_02_恋恋萌可_render",
    "name": "恋恋萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/恋恋萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是恋恋萌可！"
  },
  "泪泪萌可": {
    "key": "col_02_泪泪萌可_render",
    "name": "泪泪萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/泪泪萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是泪泪萌可！"
  },
  "淘气萌可": {
    "key": "col_02_淘气萌可_render",
    "name": "淘气萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/淘气萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是淘气萌可！"
  },
  "玩具萌可": {
    "key": "col_02_玩具萌可_render",
    "name": "玩具萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩具萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是玩具萌可！"
  },
  "玩玩萌可": {
    "key": "col_02_玩玩萌可_render",
    "name": "玩玩萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩玩萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是玩玩萌可！"
  },
  "电电萌可": {
    "key": "col_02_电电萌可_render",
    "name": "电电萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/电电萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是电电萌可！"
  },
  "画画萌可": {
    "key": "col_02_画画萌可_render",
    "name": "画画萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/画画萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是画画萌可！"
  },
  "睡睡萌可": {
    "key": "col_02_睡睡萌可_render",
    "name": "睡睡萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/睡睡萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是睡睡萌可！"
  },
  "美美萌可": {
    "key": "col_02_美美萌可_render",
    "name": "美美萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/美美萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是美美萌可！"
  },
  "聪明萌可": {
    "key": "col_02_聪明萌可_render",
    "name": "聪明萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/聪明萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是聪明萌可！"
  },
  "花花萌可": {
    "key": "col_02_花花萌可_render",
    "name": "花花萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/花花萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是花花萌可！"
  },
  "贪贪萌可": {
    "key": "col_02_贪贪萌可_render",
    "name": "贪贪萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/贪贪萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是贪贪萌可！"
  },
  "赛赛萌可": {
    "key": "col_02_赛赛萌可_render",
    "name": "赛赛萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/赛赛萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是赛赛萌可！"
  },
  "迷糊萌可": {
    "key": "col_02_迷糊萌可_render",
    "name": "迷糊萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/迷糊萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是迷糊萌可！"
  },
  "速速萌可": {
    "key": "col_02_速速萌可_render",
    "name": "速速萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/速速萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是速速萌可！"
  },
  "重重萌可": {
    "key": "col_02_重重萌可_render",
    "name": "重重萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/重重萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是重重萌可！"
  },
  "黏黏萌可": {
    "key": "col_02_黏黏萌可_render",
    "name": "黏黏萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/黏黏萌可_render.png",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是黏黏萌可！"
  },
  "公主萌可": {
    "key": "col_03_公主萌可_render",
    "name": "公主萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/公主萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是公主萌可！"
  },
  "净净萌可": {
    "key": "col_03_净净萌可_render",
    "name": "净净萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/净净萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是净净萌可！"
  },
  "分享萌可": {
    "key": "col_03_分享萌可_render",
    "name": "分享萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/分享萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是分享萌可！"
  },
  "双双萌可": {
    "key": "col_03_双双萌可_render",
    "name": "双双萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/双双萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是双双萌可！"
  },
  "嘻嘻萌可": {
    "key": "col_03_嘻嘻萌可_render",
    "name": "嘻嘻萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/嘻嘻萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是嘻嘻萌可！"
  },
  "安慰萌可": {
    "key": "col_03_安慰萌可_render",
    "name": "安慰萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/安慰萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是安慰萌可！"
  },
  "弱弱萌可": {
    "key": "col_03_弱弱萌可_02",
    "name": "弱弱萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/弱弱萌可_02.jpg",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是弱弱萌可！"
  },
  "愿望萌可": {
    "key": "col_03_愿望萌可_03",
    "name": "愿望萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/愿望萌可_03.jpg",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是愿望萌可！"
  },
  "暖暖萌可": {
    "key": "col_03_暖暖萌可_render",
    "name": "暖暖萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/暖暖萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是暖暖萌可！"
  },
  "神奇萌可": {
    "key": "col_03_神奇萌可_render",
    "name": "神奇萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/神奇萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是神奇萌可！"
  },
  "笔记萌可": {
    "key": "col_03_笔记萌可_render",
    "name": "笔记萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/笔记萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是笔记萌可！"
  },
  "美味萌可": {
    "key": "col_03_美味萌可_render",
    "name": "美味萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/美味萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是美味萌可！"
  },
  "芭蕾萌可": {
    "key": "col_03_芭蕾萌可_render",
    "name": "芭蕾萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/芭蕾萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是芭蕾萌可！"
  },
  "躲躲萌可": {
    "key": "col_03_躲躲萌可_render",
    "name": "躲躲萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/躲躲萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是躲躲萌可！"
  },
  "雕刻萌可": {
    "key": "col_03_雕刻萌可_render",
    "name": "雕刻萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/雕刻萌可_render.png",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是雕刻萌可！"
  },
  "人鱼萌可": {
    "key": "col_04_人鱼萌可_10",
    "name": "人鱼萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/人鱼萌可_10.jpg",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是人鱼萌可！"
  },
  "修理萌可": {
    "key": "col_04_修理萌可_render",
    "name": "修理萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/修理萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是修理萌可！"
  },
  "加油萌可": {
    "key": "col_04_加油萌可_render",
    "name": "加油萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/加油萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是加油萌可！"
  },
  "医生萌可": {
    "key": "col_04_医生萌可_render",
    "name": "医生萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/医生萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是医生萌可！"
  },
  "发明萌可": {
    "key": "col_04_发明萌可_render",
    "name": "发明萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/发明萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是发明萌可！"
  },
  "吞吞萌可": {
    "key": "col_04_吞吞萌可_render",
    "name": "吞吞萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/吞吞萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是吞吞萌可！"
  },
  "快快萌可": {
    "key": "col_04_快快萌可_render",
    "name": "快快萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/快快萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是快快萌可！"
  },
  "时尚萌可": {
    "key": "col_04_时尚萌可_render",
    "name": "时尚萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/时尚萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是时尚萌可！"
  },
  "歌声萌可": {
    "key": "col_04_歌声萌可_render",
    "name": "歌声萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/歌声萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是歌声萌可！"
  },
  "气气萌可": {
    "key": "col_04_气气萌可_render",
    "name": "气气萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/气气萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是气气萌可！"
  },
  "派对萌可": {
    "key": "col_04_派对萌可_render",
    "name": "派对萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/派对萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是派对萌可！"
  },
  "滑冰萌可": {
    "key": "col_04_滑冰萌可_render",
    "name": "滑冰萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/滑冰萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是滑冰萌可！"
  },
  "灭火萌可": {
    "key": "col_04_灭火萌可_03",
    "name": "灭火萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/灭火萌可_03.jpg",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是灭火萌可！"
  },
  "美发萌可": {
    "key": "col_04_美发萌可_12",
    "name": "美发萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/美发萌可_12.jpg",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是美发萌可！"
  },
  "警察萌可": {
    "key": "col_04_警察萌可_render",
    "name": "警察萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/警察萌可_render.png",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是警察萌可！"
  },
  "冰沙萌可": {
    "key": "col_05_冰沙萌可_render",
    "name": "冰沙萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/冰沙萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是冰沙萌可！"
  },
  "华夫萌可": {
    "key": "col_05_华夫萌可_render",
    "name": "华夫萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/华夫萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是华夫萌可！"
  },
  "夹心萌可": {
    "key": "col_05_夹心萌可_render",
    "name": "夹心萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/夹心萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是夹心萌可！"
  },
  "奶油萌可": {
    "key": "col_05_奶油萌可_render",
    "name": "奶油萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/奶油萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是奶油萌可！"
  },
  "巧克力萌可": {
    "key": "col_05_巧克力萌可_render",
    "name": "巧克力萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/巧克力萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是巧克力萌可！"
  },
  "布丁萌可": {
    "key": "col_05_布丁萌可_render",
    "name": "布丁萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/布丁萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是布丁萌可！"
  },
  "松饼萌可": {
    "key": "col_05_松饼萌可_render",
    "name": "松饼萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/松饼萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是松饼萌可！"
  },
  "棉花糖萌可": {
    "key": "col_05_棉花糖萌可_13",
    "name": "棉花糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/棉花糖萌可_13.jpg",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是棉花糖萌可！"
  },
  "棒棒糖萌可": {
    "key": "col_05_棒棒糖萌可_render",
    "name": "棒棒糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/棒棒糖萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是棒棒糖萌可！"
  },
  "泡泡萌可": {
    "key": "col_05_泡泡萌可_render",
    "name": "泡泡萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/泡泡萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是泡泡萌可！"
  },
  "甜甜圈萌可": {
    "key": "col_05_甜甜圈萌可_render",
    "name": "甜甜圈萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/甜甜圈萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是甜甜圈萌可！"
  },
  "糖糖萌可": {
    "key": "col_05_糖糖萌可_render",
    "name": "糖糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/糖糖萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是糖糖萌可！"
  },
  "蛋糕妹妹萌可": {
    "key": "col_05_蛋糕妹妹萌可_01",
    "name": "蛋糕妹妹萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕妹妹萌可_01.jpg",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是蛋糕妹妹萌可！"
  },
  "蛋糕妹妹萌可·蛋糕弟弟萌可": {
    "key": "col_05_蛋糕妹妹萌可_蛋糕弟弟萌可_09",
    "name": "蛋糕妹妹萌可·蛋糕弟弟萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕妹妹萌可_蛋糕弟弟萌可_09.jpg",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是蛋糕妹妹萌可·蛋糕弟弟萌可！"
  },
  "蛋糕弟弟萌可": {
    "key": "col_05_蛋糕弟弟萌可_01",
    "name": "蛋糕弟弟萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕弟弟萌可_01.jpg",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是蛋糕弟弟萌可！"
  },
  "酸奶萌可": {
    "key": "col_05_酸奶萌可_render",
    "name": "酸奶萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/酸奶萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是酸奶萌可！"
  },
  "马卡龙萌可": {
    "key": "col_05_马卡龙萌可_render",
    "name": "马卡龙萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/马卡龙萌可_render.png",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是马卡龙萌可！"
  },
  "乐美萌可": {
    "key": "col_06_乐美萌可_01",
    "name": "乐美萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/乐美萌可_01.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是乐美萌可！"
  },
  "亲亲萌可": {
    "key": "col_06_亲亲萌可_render",
    "name": "亲亲萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/亲亲萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是亲亲萌可！"
  },
  "光明萌可": {
    "key": "col_06_光明萌可_render",
    "name": "光明萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/光明萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是光明萌可！"
  },
  "兔兔萌可": {
    "key": "col_06_兔兔萌可_01",
    "name": "兔兔萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/兔兔萌可_01.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是兔兔萌可！"
  },
  "共共萌可": {
    "key": "col_06_共共萌可_render",
    "name": "共共萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/共共萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是共共萌可！"
  },
  "动动萌可": {
    "key": "col_06_动动萌可_render",
    "name": "动动萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/动动萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是动动萌可！"
  },
  "叮咚萌可": {
    "key": "col_06_叮咚萌可_render",
    "name": "叮咚萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/叮咚萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是叮咚萌可！"
  },
  "呼啦萌可": {
    "key": "col_06_呼啦萌可_render",
    "name": "呼啦萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/呼啦萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是呼啦萌可！"
  },
  "悄悄萌可": {
    "key": "col_06_悄悄萌可_render",
    "name": "悄悄萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/悄悄萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是悄悄萌可！"
  },
  "歌谣萌可": {
    "key": "col_06_歌谣萌可_15",
    "name": "歌谣萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/歌谣萌可_15.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是歌谣萌可！"
  },
  "流浪萌可": {
    "key": "col_06_流浪萌可_render",
    "name": "流浪萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/流浪萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是流浪萌可！"
  },
  "熊熊萌可": {
    "key": "col_06_熊熊萌可_08",
    "name": "熊熊萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/熊熊萌可_08.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是熊熊萌可！"
  },
  "狐狐萌可": {
    "key": "col_06_狐狐萌可_14",
    "name": "狐狐萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/狐狐萌可_14.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是狐狐萌可！"
  },
  "纷纷萌可": {
    "key": "col_06_纷纷萌可_01",
    "name": "纷纷萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/纷纷萌可_01.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是纷纷萌可！"
  },
  "绵羊萌可": {
    "key": "col_06_绵羊萌可_10",
    "name": "绵羊萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/绵羊萌可_10.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是绵羊萌可！"
  },
  "缤缤萌可": {
    "key": "col_06_缤缤萌可_01",
    "name": "缤缤萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/缤缤萌可_01.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是缤缤萌可！"
  },
  "缤缤萌可·纷纷萌可": {
    "key": "col_06_缤缤萌可_纷纷萌可_09",
    "name": "缤缤萌可·纷纷萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/缤缤萌可_纷纷萌可_09.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是缤缤萌可·纷纷萌可！"
  },
  "贴贴萌可": {
    "key": "col_06_贴贴萌可_render",
    "name": "贴贴萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/贴贴萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是贴贴萌可！"
  },
  "跳舞萌可": {
    "key": "col_06_跳舞萌可_render",
    "name": "跳舞萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/跳舞萌可_render.png",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是跳舞萌可！"
  },
  "透明萌可": {
    "key": "col_06_透明萌可_11",
    "name": "透明萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/透明萌可_11.jpg",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是透明萌可！"
  },
  "丘比特萌可": {
    "key": "col_07_丘比特萌可_render",
    "name": "丘比特萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/丘比特萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是丘比特萌可！"
  },
  "丝绸萌可": {
    "key": "col_07_丝绸萌可_render",
    "name": "丝绸萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/丝绸萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是丝绸萌可！"
  },
  "困困萌可": {
    "key": "col_07_困困萌可_07",
    "name": "困困萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/困困萌可_07.jpg",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是困困萌可！"
  },
  "洗洗萌可": {
    "key": "col_07_洗洗萌可_render",
    "name": "洗洗萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/洗洗萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是洗洗萌可！"
  },
  "猫猫萌可": {
    "key": "col_07_猫猫萌可_render",
    "name": "猫猫萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/猫猫萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是猫猫萌可！"
  },
  "玲珑萌可": {
    "key": "col_07_玲珑萌可_09",
    "name": "玲珑萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/玲珑萌可_09.jpg",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是玲珑萌可！"
  },
  "白雪萌可": {
    "key": "col_07_白雪萌可_render",
    "name": "白雪萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/白雪萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是白雪萌可！"
  },
  "蝴蝶萌可": {
    "key": "col_07_蝴蝶萌可_render",
    "name": "蝴蝶萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/蝴蝶萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是蝴蝶萌可！"
  },
  "露水萌可": {
    "key": "col_07_露水萌可_render",
    "name": "露水萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/露水萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是露水萌可！"
  },
  "鞋鞋萌可": {
    "key": "col_07_鞋鞋萌可_08",
    "name": "鞋鞋萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/鞋鞋萌可_08.jpg",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是鞋鞋萌可！"
  },
  "魅力萌可": {
    "key": "col_07_魅力萌可_render",
    "name": "魅力萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/魅力萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是魅力萌可！"
  },
  "查尔斯萌可": {
    "key": "col_08_查尔斯萌可_render",
    "name": "查尔斯萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/查尔斯萌可_render.png",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是查尔斯萌可！"
  },
  "演歌萌可": {
    "key": "col_08_演歌萌可_01",
    "name": "演歌萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/演歌萌可_01.jpg",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是演歌萌可！"
  },
  "绅士萌可": {
    "key": "col_08_绅士萌可_01",
    "name": "绅士萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/绅士萌可_01.jpg",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是绅士萌可！"
  },
  "青蛙萌可": {
    "key": "col_08_青蛙萌可_01",
    "name": "青蛙萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/青蛙萌可_01.jpg",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是青蛙萌可！"
  },
  "神秘萌可": {
    "key": "col_09_extra_18",
    "name": "神秘萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/extra_18.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是神秘萌可！"
  },
  "其他萌可": {
    "key": "col_09_其他萌可_01",
    "name": "其他萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/其他萌可_01.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是其他萌可！"
  },
  "士兵萌可": {
    "key": "col_09_士兵萌可_01",
    "name": "士兵萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/士兵萌可_01.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是士兵萌可！"
  },
  "奉献萌可": {
    "key": "col_09_奉献萌可_01",
    "name": "奉献萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/奉献萌可_01.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是奉献萌可！"
  },
  "波荡萌可": {
    "key": "col_09_波荡萌可_01",
    "name": "波荡萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/波荡萌可_01.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是波荡萌可！"
  },
  "铃铛萌可": {
    "key": "col_09_铃铛萌可_01",
    "name": "铃铛萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/铃铛萌可_01.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是铃铛萌可！"
  },
  "闹闹萌可": {
    "key": "col_09_闹闹萌可_render",
    "name": "闹闹萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/闹闹萌可_render.png",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是闹闹萌可！"
  },
  "黑暗萌可": {
    "key": "col_09_黑暗萌可_01",
    "name": "黑暗萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/黑暗萌可_01.jpg",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是黑暗萌可！"
  },
  "幸运萌可": {
    "key": "col_10_幸运萌可_render",
    "name": "幸运萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/幸运萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是幸运萌可！"
  },
  "月神萌可": {
    "key": "col_10_月神萌可_01",
    "name": "月神萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/月神萌可_01.jpg",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是月神萌可！"
  },
  "月食萌可": {
    "key": "col_10_月食萌可_01",
    "name": "月食萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/月食萌可_01.jpg",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是月食萌可！"
  },
  "极光萌可": {
    "key": "col_10_极光萌可_render",
    "name": "极光萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/极光萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是极光萌可！"
  },
  "甜甜萌可": {
    "key": "col_10_甜甜萌可_render",
    "name": "甜甜萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/甜甜萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是甜甜萌可！"
  },
  "酸酸萌可": {
    "key": "col_10_酸酸萌可_render",
    "name": "酸酸萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/酸酸萌可_render.png",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是酸酸萌可！"
  }
};
