// 自动生成：由 scripts 扫描 public/moko/collection/ 生成，请勿手改。
// 重新生成：node scripts/gen-moko-collection.js
import type { MokoChar, MokoCategoryKey } from './types';

export interface MokoCollectionCat {
  key: MokoCategoryKey;
  label: string;
  emoji: string;
  color: string;
  desc: string;
}

/** 本次新增的季分类（需并入 MOko_CATEGORIES） */
export const COLLECTION_CATEGORIES: MokoCollectionCat[] = [
  {
    "key": "mo",
    "label": "魔方萌可",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "desc": "第一、二季的魔法萌可"
  },
  {
    "key": "prince",
    "label": "王子萌可",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "desc": "守护王国的王子们"
  },
  {
    "key": "villain",
    "label": "反派萌可",
    "emoji": "😈",
    "color": "text-slate-500",
    "desc": "搞怪的反派与神秘角色"
  },
  {
    "key": "legend",
    "label": "传奇萌可",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "desc": "传说中的特别萌可"
  }
];

/** 全部萌可图片（由 public/moko/collection 扫描生成，key 以 col_ 前缀，category 见上） */
export const mokoCollection: MokoChar[] = [
  {
    "key": "col_01_优雅萌可_render",
    "name": "优雅萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/优雅萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，温柔~ 我是优雅萌可！"
  },
  {
    "key": "col_01_信信萌可_render",
    "name": "信信萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/信信萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，软软~ 我是信信萌可！"
  },
  {
    "key": "col_01_勇气萌可_render",
    "name": "勇气萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/勇气萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "哈哈，我是勇气萌可，冲呀！"
  },
  {
    "key": "col_01_唱唱萌可_render",
    "name": "唱唱萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/唱唱萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啦啦~ 我是唱唱萌可，唱给世界听！"
  },
  {
    "key": "col_01_好好萌可_render",
    "name": "好好萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/好好萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，软软~ 我是好好萌可！"
  },
  {
    "key": "col_01_幸福萌可_render",
    "name": "幸福萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/幸福萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "幸福~ 我是幸福萌可，甜甜满满！"
  },
  {
    "key": "col_01_星光萌可_render",
    "name": "星光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/星光萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "星星~ 我是星光萌可，闪亮登场！"
  },
  {
    "key": "col_01_月光萌可_render",
    "name": "月光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/月光萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "月光~ 我是月光萌可，明朗皎洁！"
  },
  {
    "key": "col_01_正正萌可_render",
    "name": "正正萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/正正萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "敬礼！我是正正萌可，无所畏惧！"
  },
  {
    "key": "col_01_漂亮萌可_render",
    "name": "漂亮萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/漂亮萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，元气~ 我是漂亮萌可！"
  },
  {
    "key": "col_01_热情萌可_render",
    "name": "热情萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/热情萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "华丽！热情萌可来啦！"
  },
  {
    "key": "col_01_爱心萌可_render",
    "name": "爱心萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/爱心萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是爱心萌可，爱心光波！"
  },
  {
    "key": "col_01_王子萌可_render",
    "name": "王子萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/王子萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "我是王子萌可，我来守护大家！"
  },
  {
    "key": "col_01_盼盼萌可_render",
    "name": "盼盼萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/盼盼萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "锵锵，我是盼盼萌可，希望满满！"
  },
  {
    "key": "col_01_笑笑萌可_render",
    "name": "笑笑萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/笑笑萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "呼呼，笑笑萌可在这里，甜甜~"
  },
  {
    "key": "col_01_绵绵萌可_render",
    "name": "绵绵萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/绵绵萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "绵绵~ 我是绵绵萌可，软乎乎！"
  },
  {
    "key": "col_01_美丽萌可_render",
    "name": "美丽萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/美丽萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，幸福~ 我是美丽萌可！"
  },
  {
    "key": "col_01_诚实萌可_render",
    "name": "诚实萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/诚实萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "月光！诚实萌可来啦！"
  },
  {
    "key": "col_01_赞赞萌可_render",
    "name": "赞赞萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/赞赞萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，元气~ 我是赞赞萌可！"
  },
  {
    "key": "col_01_软软萌可_render",
    "name": "软软萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/软软萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "软软~ 我是软软萌可，弹弹果冻！"
  },
  {
    "key": "col_01_银光萌可_render",
    "name": "银光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/银光萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "耀耀~ 我是银光萌可，柔柔发光！"
  },
  {
    "key": "col_01_闪闪萌可_render",
    "name": "闪闪萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/闪闪萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "闪闪~ 我是闪闪萌可，元气满满！"
  },
  {
    "key": "col_02_乖乖萌可_render",
    "name": "乖乖萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/乖乖萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，乖乖萌可在这里，咻咻~"
  },
  {
    "key": "col_02_仿仿萌可_render",
    "name": "仿仿萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/仿仿萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！仿仿萌可来啦！"
  },
  {
    "key": "col_02_倒倒萌可_render",
    "name": "倒倒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/倒倒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，倒倒萌可在这里，咻咻~"
  },
  {
    "key": "col_02_八卦萌可_render",
    "name": "八卦萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/八卦萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "八卦萌可登场，转转~"
  },
  {
    "key": "col_02_冰冰萌可_render",
    "name": "冰冰萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/冰冰萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，冰冰萌可在这里，咻咻~"
  },
  {
    "key": "col_02_冷冷萌可_render",
    "name": "冷冷萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/冷冷萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！冷冷萌可来啦！"
  },
  {
    "key": "col_02_厌厌萌可_render",
    "name": "厌厌萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/厌厌萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是厌厌萌可！"
  },
  {
    "key": "col_02_变身萌可_render",
    "name": "变身萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/变身萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，灵灵~ 我是变身萌可！"
  },
  {
    "key": "col_02_叹气萌可_render",
    "name": "叹气萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/叹气萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "叹气萌可登场，转转~"
  },
  {
    "key": "col_02_否否萌可_render",
    "name": "否否萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/否否萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，否否萌可在这里，咻咻~"
  },
  {
    "key": "col_02_好奇萌可_render",
    "name": "好奇萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/好奇萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，叮咚~ 我是好奇萌可！"
  },
  {
    "key": "col_02_妒妒萌可_render",
    "name": "妒妒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/妒妒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是妒妒萌可！"
  },
  {
    "key": "col_02_妖妖萌可_render",
    "name": "妖妖萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/妖妖萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，妖妖萌可在这里，咻咻~"
  },
  {
    "key": "col_02_娇娇萌可_render",
    "name": "娇娇萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/娇娇萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是娇娇萌可！"
  },
  {
    "key": "col_02_孤独萌可_render",
    "name": "孤独萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/孤独萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，孤独萌可在这里，闪闪~"
  },
  {
    "key": "col_02_宝宝萌可_render",
    "name": "宝宝萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/宝宝萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，宝宝萌可在这里，咻咻~"
  },
  {
    "key": "col_02_害羞萌可_render",
    "name": "害羞萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/害羞萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，转转~ 我是害羞萌可！"
  },
  {
    "key": "col_02_幻幻萌可_render",
    "name": "幻幻萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/幻幻萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是幻幻萌可！"
  },
  {
    "key": "col_02_怒怒萌可_render",
    "name": "怒怒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/怒怒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！怒怒萌可来啦！"
  },
  {
    "key": "col_02_怕怕萌可_render",
    "name": "怕怕萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/怕怕萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！怕怕萌可来啦！"
  },
  {
    "key": "col_02_恋恋萌可_render",
    "name": "恋恋萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/恋恋萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！恋恋萌可来啦！"
  },
  {
    "key": "col_02_泪泪萌可_render",
    "name": "泪泪萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/泪泪萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！泪泪萌可来啦！"
  },
  {
    "key": "col_02_淘气萌可_render",
    "name": "淘气萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/淘气萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咔咔！淘气萌可来啦！"
  },
  {
    "key": "col_02_玩具萌可_render",
    "name": "玩具萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩具萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，玩具萌可在这里，噗噗~"
  },
  {
    "key": "col_02_玩玩萌可_render",
    "name": "玩玩萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩玩萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，玩玩萌可在这里，咻咻~"
  },
  {
    "key": "col_02_玩玩萌可_乐乐萌可_render",
    "name": "玩玩萌可·乐乐萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩玩萌可_乐乐萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "飘飘！玩玩萌可·乐乐萌可来啦！"
  },
  {
    "key": "col_02_电电萌可_render",
    "name": "电电萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/电电萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，电电萌可在这里，咻咻~"
  },
  {
    "key": "col_02_画画萌可_render",
    "name": "画画萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/画画萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，画画萌可在这里，咻咻~"
  },
  {
    "key": "col_02_睡睡萌可_render",
    "name": "睡睡萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/睡睡萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！睡睡萌可来啦！"
  },
  {
    "key": "col_02_美美萌可_render",
    "name": "美美萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/美美萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，美美萌可在这里，咻咻~"
  },
  {
    "key": "col_02_聪明萌可_render",
    "name": "聪明萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/聪明萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，飘飘~ 我是聪明萌可！"
  },
  {
    "key": "col_02_花花萌可_render",
    "name": "花花萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/花花萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是花花萌可！"
  },
  {
    "key": "col_02_贪贪萌可_render",
    "name": "贪贪萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/贪贪萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！贪贪萌可来啦！"
  },
  {
    "key": "col_02_赛赛萌可_render",
    "name": "赛赛萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/赛赛萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是赛赛萌可！"
  },
  {
    "key": "col_02_迷糊萌可_render",
    "name": "迷糊萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/迷糊萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "灵灵~ 我是迷糊萌可！"
  },
  {
    "key": "col_02_速速萌可_render",
    "name": "速速萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/速速萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是速速萌可！"
  },
  {
    "key": "col_02_重重萌可_render",
    "name": "重重萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/重重萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，重重萌可在这里，咻咻~"
  },
  {
    "key": "col_02_黏黏萌可_render",
    "name": "黏黏萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/黏黏萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，黏黏萌可在这里，咻咻~"
  },
  {
    "key": "col_03_公主萌可_render",
    "name": "公主萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/公主萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "亮晶晶~ 我是公主萌可！"
  },
  {
    "key": "col_03_净净萌可_render",
    "name": "净净萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/净净萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "透透！净净萌可来啦！"
  },
  {
    "key": "col_03_分享萌可_render",
    "name": "分享萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/分享萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "分享萌可登场，亮晶晶~"
  },
  {
    "key": "col_03_双双萌可_render",
    "name": "双双萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/双双萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "呼呼，双双萌可在这里，耀耀~"
  },
  {
    "key": "col_03_嘻嘻萌可_render",
    "name": "嘻嘻萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/嘻嘻萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，耀耀~ 我是嘻嘻萌可！"
  },
  {
    "key": "col_03_安慰萌可_render",
    "name": "安慰萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/安慰萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "亮晶晶~ 我是安慰萌可！"
  },
  {
    "key": "col_03_弱弱萌可_render",
    "name": "弱弱萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/弱弱萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "晶晶！弱弱萌可来啦！"
  },
  {
    "key": "col_03_愿望萌可_render",
    "name": "愿望萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/愿望萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，熠熠~ 我是愿望萌可！"
  },
  {
    "key": "col_03_暖暖萌可_render",
    "name": "暖暖萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/暖暖萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "透透！暖暖萌可来啦！"
  },
  {
    "key": "col_03_神奇萌可_render",
    "name": "神奇萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/神奇萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，绚绚~ 我是神奇萌可！"
  },
  {
    "key": "col_03_笔记萌可_render",
    "name": "笔记萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/笔记萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，熠熠~ 我是笔记萌可！"
  },
  {
    "key": "col_03_美味萌可_render",
    "name": "美味萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/美味萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，bling~ 我是美味萌可！"
  },
  {
    "key": "col_03_芭蕾萌可_render",
    "name": "芭蕾萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/芭蕾萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "芭蕾萌可登场，bling~"
  },
  {
    "key": "col_03_躲躲萌可_render",
    "name": "躲躲萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/躲躲萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "呼呼，躲躲萌可在这里，耀耀~"
  },
  {
    "key": "col_03_雕刻萌可_render",
    "name": "雕刻萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/雕刻萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "璀璨！雕刻萌可来啦！"
  },
  {
    "key": "col_04_人鱼萌可_render",
    "name": "人鱼萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/人鱼萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "呼呼，人鱼萌可在这里，叮当~"
  },
  {
    "key": "col_04_修理萌可_render",
    "name": "修理萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/修理萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "呼呼，修理萌可在这里，叮当~"
  },
  {
    "key": "col_04_加油萌可_render",
    "name": "加油萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/加油萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "加油萌可登场，寻寻~"
  },
  {
    "key": "col_04_医生萌可_render",
    "name": "医生萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/医生萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，探索~ 我是医生萌可！"
  },
  {
    "key": "col_04_发明萌可_render",
    "name": "发明萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/发明萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，锁好~ 我是发明萌可！"
  },
  {
    "key": "col_04_吞吞萌可_render",
    "name": "吞吞萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/吞吞萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "锁好！吞吞萌可来啦！"
  },
  {
    "key": "col_04_快快萌可_render",
    "name": "快快萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/快快萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "钥匙！快快萌可来啦！"
  },
  {
    "key": "col_04_时尚萌可_render",
    "name": "时尚萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/时尚萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "钥匙！时尚萌可来啦！"
  },
  {
    "key": "col_04_歌声萌可_render",
    "name": "歌声萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/歌声萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "呼呼，歌声萌可在这里，猜猜~"
  },
  {
    "key": "col_04_气气萌可_render",
    "name": "气气萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/气气萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "呼呼，气气萌可在这里，猜猜~"
  },
  {
    "key": "col_04_派对萌可_render",
    "name": "派对萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/派对萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "派对萌可登场，猜猜~"
  },
  {
    "key": "col_04_滑冰萌可_render",
    "name": "滑冰萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/滑冰萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，解密~ 我是滑冰萌可！"
  },
  {
    "key": "col_04_灭火萌可_render",
    "name": "灭火萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/灭火萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，探索~ 我是灭火萌可！"
  },
  {
    "key": "col_04_美发萌可_render",
    "name": "美发萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/美发萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，解密~ 我是美发萌可！"
  },
  {
    "key": "col_04_警察萌可_render",
    "name": "警察萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/警察萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，钥匙~ 我是警察萌可！"
  },
  {
    "key": "col_05_冰沙萌可_render",
    "name": "冰沙萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/冰沙萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "华夫~ 我是冰沙萌可！"
  },
  {
    "key": "col_05_华夫萌可_render",
    "name": "华夫萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/华夫萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "软软~ 我是华夫萌可！"
  },
  {
    "key": "col_05_夹心萌可_render",
    "name": "夹心萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/夹心萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "呼呼，夹心萌可在这里，棒棒~"
  },
  {
    "key": "col_05_奶油萌可_render",
    "name": "奶油萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/奶油萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "香香~ 我是奶油萌可！"
  },
  {
    "key": "col_05_巧克力萌可_render",
    "name": "巧克力萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/巧克力萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "巧克力萌可登场，糖糖~"
  },
  {
    "key": "col_05_布丁萌可_render",
    "name": "布丁萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/布丁萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，甜甜~ 我是布丁萌可！"
  },
  {
    "key": "col_05_松饼萌可_render",
    "name": "松饼萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/松饼萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，糖糖~ 我是松饼萌可！"
  },
  {
    "key": "col_05_棉花糖萌可_render",
    "name": "棉花糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/棉花糖萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，凉凉~ 我是棉花糖萌可！"
  },
  {
    "key": "col_05_棒棒糖萌可_render",
    "name": "棒棒糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/棒棒糖萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "呼呼，棒棒糖萌可在这里，甜甜~"
  },
  {
    "key": "col_05_泡泡萌可_render",
    "name": "泡泡萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/泡泡萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "糯糯！泡泡萌可来啦！"
  },
  {
    "key": "col_05_甜甜圈萌可_render",
    "name": "甜甜圈萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/甜甜圈萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "呼呼，甜甜圈萌可在这里，呼呼~"
  },
  {
    "key": "col_05_糖糖萌可_render",
    "name": "糖糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/糖糖萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "糖糖~ 我是糖糖萌可，甜滋滋！"
  },
  {
    "key": "col_05_蛋糕妹妹萌可_render",
    "name": "蛋糕妹妹萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕妹妹萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "呼呼，蛋糕妹妹萌可在这里，糯糯~"
  },
  {
    "key": "col_05_蛋糕妹妹萌可_蛋糕弟弟萌可_render",
    "name": "蛋糕妹妹萌可·蛋糕弟弟萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕妹妹萌可_蛋糕弟弟萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "呼呼！蛋糕妹妹萌可·蛋糕弟弟萌可来啦！"
  },
  {
    "key": "col_05_蛋糕弟弟萌可_render",
    "name": "蛋糕弟弟萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕弟弟萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，绵绵~ 我是蛋糕弟弟萌可！"
  },
  {
    "key": "col_05_酸奶萌可_render",
    "name": "酸奶萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/酸奶萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "呼呼，酸奶萌可在这里，蜜蜜~"
  },
  {
    "key": "col_05_马卡龙萌可_render",
    "name": "马卡龙萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/马卡龙萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，巧巧~ 我是马卡龙萌可！"
  },
  {
    "key": "col_06_乐美萌可_render",
    "name": "乐美公主",
    "category": "guide",
    "season": "星星萌可_第六季",
    "img": "/moko/lemei.jpg",
    "emoji": "👑",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "一起捕捉萌可吧！"
  },
  {
    "key": "col_06_亲亲萌可_render",
    "name": "亲亲萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/亲亲萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "亲亲~ 我是亲亲萌可，mua！"
  },
  {
    "key": "col_06_光明萌可_render",
    "name": "光明萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/光明萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "光明~ 我是光明萌可，照亮你！"
  },
  {
    "key": "col_06_兔兔萌可_render",
    "name": "兔兔萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/兔兔萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "跳跳~ 我是兔兔萌可，蹦蹦跳！"
  },
  {
    "key": "col_06_共共萌可_render",
    "name": "共共萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/共共萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "共共~ 我是共共萌可，一起分享！"
  },
  {
    "key": "col_06_动动萌可_render",
    "name": "动动萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/动动萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "动动~ 我是动动萌可，动起来！"
  },
  {
    "key": "col_06_叮咚萌可_render",
    "name": "叮咚萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/叮咚萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "叮咚~ 我是叮咚萌可，门铃响啦！"
  },
  {
    "key": "col_06_呼啦萌可_render",
    "name": "呼啦萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/呼啦萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼啦~ 我是呼啦萌可，转圈圈！"
  },
  {
    "key": "col_06_悄悄萌可_render",
    "name": "悄悄萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/悄悄萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "悄悄~ 我是悄悄萌可，别出声～"
  },
  {
    "key": "col_06_歌谣萌可_render",
    "name": "歌谣萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/歌谣萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "歌谣~ 我是歌谣萌可，唱起来！"
  },
  {
    "key": "col_06_流浪萌可_render",
    "name": "流浪萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/流浪萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "嗖嗖~ 我是流浪萌可！"
  },
  {
    "key": "col_06_熊熊萌可_render",
    "name": "熊熊萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/熊熊萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "熊熊~ 我是熊熊萌可，抱抱你！"
  },
  {
    "key": "col_06_狐狐萌可_render",
    "name": "狐狐萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/狐狐萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "狐狐~ 我是狐狐萌可，狡黠一笑！"
  },
  {
    "key": "col_06_纷纷萌可_render",
    "name": "纷纷萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/纷纷萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "纷纷~ 我是纷纷萌可，飘呀飘！"
  },
  {
    "key": "col_06_绵羊萌可_render",
    "name": "绵羊萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/绵羊萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咩咩~ 我是绵羊萌可，软软的！"
  },
  {
    "key": "col_06_缤缤萌可_render",
    "name": "缤缤萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/缤缤萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "缤缤~ 我是缤缤萌可，五彩缤纷！"
  },
  {
    "key": "col_06_缤缤萌可_纷纷萌可_render",
    "name": "缤缤萌可·纷纷萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/缤缤萌可_纷纷萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "望望！缤缤萌可·纷纷萌可来啦！"
  },
  {
    "key": "col_06_贴贴萌可_render",
    "name": "贴贴萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/贴贴萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "贴贴~ 我是贴贴萌可，贴贴你！"
  },
  {
    "key": "col_06_跳舞萌可_render",
    "name": "跳舞萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/跳舞萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "跳舞~ 我是跳舞萌可，转个圈！"
  },
  {
    "key": "col_06_透明萌可_render",
    "name": "透明萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/透明萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "玻璃~ 我是透明萌可，看不见啦！"
  },
  {
    "key": "col_07_丘比特萌可_render",
    "name": "丘比特萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/丘比特萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "丘比特萌可登场，月光~"
  },
  {
    "key": "col_07_丝绸萌可_render",
    "name": "丝绸萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/丝绸萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "丝绸萌可登场，灵灵~"
  },
  {
    "key": "col_07_困困萌可_render",
    "name": "困困萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/困困萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "呼呼，困困萌可在这里，自信~"
  },
  {
    "key": "col_07_洗洗萌可_render",
    "name": "洗洗萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/洗洗萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "自信！洗洗萌可来啦！"
  },
  {
    "key": "col_07_猫猫萌可_render",
    "name": "猫猫萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/猫猫萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "呼呼，猫猫萌可在这里，自信~"
  },
  {
    "key": "col_07_玲珑萌可_render",
    "name": "玲珑萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/玲珑萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "华丽~ 我是玲珑萌可！"
  },
  {
    "key": "col_07_白雪萌可_render",
    "name": "白雪萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/白雪萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，月光~ 我是白雪萌可！"
  },
  {
    "key": "col_07_蝴蝶萌可_render",
    "name": "蝴蝶萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/蝴蝶萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "优雅！蝴蝶萌可来啦！"
  },
  {
    "key": "col_07_露水萌可_render",
    "name": "露水萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/露水萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "呼呼，露水萌可在这里，优雅~"
  },
  {
    "key": "col_07_鞋鞋萌可_render",
    "name": "鞋鞋萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/鞋鞋萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "呼呼，鞋鞋萌可在这里，自信~"
  },
  {
    "key": "col_07_魅力萌可_render",
    "name": "魅力萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/魅力萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，盈盈~ 我是魅力萌可！"
  },
  {
    "key": "col_08_查尔斯萌可_render",
    "name": "查尔斯王子",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/查尔斯萌可_render.webp",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，凛凛~ 我是查尔斯王子！"
  },
  {
    "key": "col_08_演歌萌可_render",
    "name": "演歌萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/演歌萌可_render.webp",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，剑剑~ 我是演歌萌可！"
  },
  {
    "key": "col_08_绅士萌可_render",
    "name": "绅士萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/绅士萌可_render.webp",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "呼呼，绅士萌可在这里，英英~"
  },
  {
    "key": "col_08_青蛙萌可_render",
    "name": "青蛙萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/青蛙萌可_render.webp",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "帅帅~ 我是青蛙萌可！"
  },
  {
    "key": "col_09_奉献萌可_render",
    "name": "奉献萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/奉献萌可_render.webp",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "嘻嘻~ 我是奉献萌可！"
  },
  {
    "key": "col_09_闹闹萌可_render",
    "name": "闹闹萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/闹闹萌可_render.webp",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "呼呼，闹闹萌可在这里，鬼鬼~"
  },
  {
    "key": "col_10_幸运萌可_render",
    "name": "幸运萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/幸运萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "呼呼，幸运萌可在这里，运运~"
  },
  {
    "key": "col_10_月神萌可_render",
    "name": "月神萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/月神萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，灿灿~ 我是月神萌可！"
  },
  {
    "key": "col_10_月食萌可_render",
    "name": "月食萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/月食萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，奇奇~ 我是月食萌可！"
  },
  {
    "key": "col_10_极光萌可_render",
    "name": "极光萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/极光萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "极光~ 我是极光萌可，绚丽登场！"
  },
  {
    "key": "col_10_甜甜萌可_render",
    "name": "甜甜萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/甜甜萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，闪耀~ 我是甜甜萌可！"
  },
  {
    "key": "col_10_酸酸萌可_render",
    "name": "酸酸萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/酸酸萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，闪耀~ 我是酸酸萌可！"
  }
];

/** 同名首图（用于把核心萌可的 img 重映射到真实图片） */
export const mokoCollectionByName: Record<string, MokoChar> = {
  "优雅萌可": {
    "key": "col_01_优雅萌可_render",
    "name": "优雅萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/优雅萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，温柔~ 我是优雅萌可！"
  },
  "信信萌可": {
    "key": "col_01_信信萌可_render",
    "name": "信信萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/信信萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，软软~ 我是信信萌可！"
  },
  "勇气萌可": {
    "key": "col_01_勇气萌可_render",
    "name": "勇气萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/勇气萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "哈哈，我是勇气萌可，冲呀！"
  },
  "唱唱萌可": {
    "key": "col_01_唱唱萌可_render",
    "name": "唱唱萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/唱唱萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啦啦~ 我是唱唱萌可，唱给世界听！"
  },
  "好好萌可": {
    "key": "col_01_好好萌可_render",
    "name": "好好萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/好好萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，软软~ 我是好好萌可！"
  },
  "幸福萌可": {
    "key": "col_01_幸福萌可_render",
    "name": "幸福萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/幸福萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "幸福~ 我是幸福萌可，甜甜满满！"
  },
  "星光萌可": {
    "key": "col_01_星光萌可_render",
    "name": "星光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/星光萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "星星~ 我是星光萌可，闪亮登场！"
  },
  "月光萌可": {
    "key": "col_01_月光萌可_render",
    "name": "月光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/月光萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "月光~ 我是月光萌可，明朗皎洁！"
  },
  "正正萌可": {
    "key": "col_01_正正萌可_render",
    "name": "正正萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/正正萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "敬礼！我是正正萌可，无所畏惧！"
  },
  "漂亮萌可": {
    "key": "col_01_漂亮萌可_render",
    "name": "漂亮萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/漂亮萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，元气~ 我是漂亮萌可！"
  },
  "热情萌可": {
    "key": "col_01_热情萌可_render",
    "name": "热情萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/热情萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "华丽！热情萌可来啦！"
  },
  "爱心萌可": {
    "key": "col_01_爱心萌可_render",
    "name": "爱心萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/爱心萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是爱心萌可，爱心光波！"
  },
  "王子萌可": {
    "key": "col_01_王子萌可_render",
    "name": "王子萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/王子萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "我是王子萌可，我来守护大家！"
  },
  "盼盼萌可": {
    "key": "col_01_盼盼萌可_render",
    "name": "盼盼萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/盼盼萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "锵锵，我是盼盼萌可，希望满满！"
  },
  "笑笑萌可": {
    "key": "col_01_笑笑萌可_render",
    "name": "笑笑萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/笑笑萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "呼呼，笑笑萌可在这里，甜甜~"
  },
  "绵绵萌可": {
    "key": "col_01_绵绵萌可_render",
    "name": "绵绵萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/绵绵萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "绵绵~ 我是绵绵萌可，软乎乎！"
  },
  "美丽萌可": {
    "key": "col_01_美丽萌可_render",
    "name": "美丽萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/美丽萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，幸福~ 我是美丽萌可！"
  },
  "诚实萌可": {
    "key": "col_01_诚实萌可_render",
    "name": "诚实萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/诚实萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "月光！诚实萌可来啦！"
  },
  "赞赞萌可": {
    "key": "col_01_赞赞萌可_render",
    "name": "赞赞萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/赞赞萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，元气~ 我是赞赞萌可！"
  },
  "软软萌可": {
    "key": "col_01_软软萌可_render",
    "name": "软软萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/软软萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "软软~ 我是软软萌可，弹弹果冻！"
  },
  "银光萌可": {
    "key": "col_01_银光萌可_render",
    "name": "银光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/银光萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "耀耀~ 我是银光萌可，柔柔发光！"
  },
  "闪闪萌可": {
    "key": "col_01_闪闪萌可_render",
    "name": "闪闪萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/闪闪萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "闪闪~ 我是闪闪萌可，元气满满！"
  },
  "乖乖萌可": {
    "key": "col_02_乖乖萌可_render",
    "name": "乖乖萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/乖乖萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，乖乖萌可在这里，咻咻~"
  },
  "仿仿萌可": {
    "key": "col_02_仿仿萌可_render",
    "name": "仿仿萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/仿仿萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！仿仿萌可来啦！"
  },
  "倒倒萌可": {
    "key": "col_02_倒倒萌可_render",
    "name": "倒倒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/倒倒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，倒倒萌可在这里，咻咻~"
  },
  "八卦萌可": {
    "key": "col_02_八卦萌可_render",
    "name": "八卦萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/八卦萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "八卦萌可登场，转转~"
  },
  "冰冰萌可": {
    "key": "col_02_冰冰萌可_render",
    "name": "冰冰萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/冰冰萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，冰冰萌可在这里，咻咻~"
  },
  "冷冷萌可": {
    "key": "col_02_冷冷萌可_render",
    "name": "冷冷萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/冷冷萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！冷冷萌可来啦！"
  },
  "厌厌萌可": {
    "key": "col_02_厌厌萌可_render",
    "name": "厌厌萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/厌厌萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是厌厌萌可！"
  },
  "变身萌可": {
    "key": "col_02_变身萌可_render",
    "name": "变身萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/变身萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，灵灵~ 我是变身萌可！"
  },
  "叹气萌可": {
    "key": "col_02_叹气萌可_render",
    "name": "叹气萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/叹气萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "叹气萌可登场，转转~"
  },
  "否否萌可": {
    "key": "col_02_否否萌可_render",
    "name": "否否萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/否否萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，否否萌可在这里，咻咻~"
  },
  "好奇萌可": {
    "key": "col_02_好奇萌可_render",
    "name": "好奇萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/好奇萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，叮咚~ 我是好奇萌可！"
  },
  "妒妒萌可": {
    "key": "col_02_妒妒萌可_render",
    "name": "妒妒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/妒妒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是妒妒萌可！"
  },
  "妖妖萌可": {
    "key": "col_02_妖妖萌可_render",
    "name": "妖妖萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/妖妖萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，妖妖萌可在这里，咻咻~"
  },
  "娇娇萌可": {
    "key": "col_02_娇娇萌可_render",
    "name": "娇娇萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/娇娇萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是娇娇萌可！"
  },
  "孤独萌可": {
    "key": "col_02_孤独萌可_render",
    "name": "孤独萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/孤独萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，孤独萌可在这里，闪闪~"
  },
  "宝宝萌可": {
    "key": "col_02_宝宝萌可_render",
    "name": "宝宝萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/宝宝萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，宝宝萌可在这里，咻咻~"
  },
  "害羞萌可": {
    "key": "col_02_害羞萌可_render",
    "name": "害羞萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/害羞萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，转转~ 我是害羞萌可！"
  },
  "幻幻萌可": {
    "key": "col_02_幻幻萌可_render",
    "name": "幻幻萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/幻幻萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是幻幻萌可！"
  },
  "怒怒萌可": {
    "key": "col_02_怒怒萌可_render",
    "name": "怒怒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/怒怒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！怒怒萌可来啦！"
  },
  "怕怕萌可": {
    "key": "col_02_怕怕萌可_render",
    "name": "怕怕萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/怕怕萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！怕怕萌可来啦！"
  },
  "恋恋萌可": {
    "key": "col_02_恋恋萌可_render",
    "name": "恋恋萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/恋恋萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！恋恋萌可来啦！"
  },
  "泪泪萌可": {
    "key": "col_02_泪泪萌可_render",
    "name": "泪泪萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/泪泪萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！泪泪萌可来啦！"
  },
  "淘气萌可": {
    "key": "col_02_淘气萌可_render",
    "name": "淘气萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/淘气萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咔咔！淘气萌可来啦！"
  },
  "玩具萌可": {
    "key": "col_02_玩具萌可_render",
    "name": "玩具萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩具萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，玩具萌可在这里，噗噗~"
  },
  "玩玩萌可": {
    "key": "col_02_玩玩萌可_render",
    "name": "玩玩萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩玩萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，玩玩萌可在这里，咻咻~"
  },
  "玩玩萌可·乐乐萌可": {
    "key": "col_02_玩玩萌可_乐乐萌可_render",
    "name": "玩玩萌可·乐乐萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩玩萌可_乐乐萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "飘飘！玩玩萌可·乐乐萌可来啦！"
  },
  "电电萌可": {
    "key": "col_02_电电萌可_render",
    "name": "电电萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/电电萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，电电萌可在这里，咻咻~"
  },
  "画画萌可": {
    "key": "col_02_画画萌可_render",
    "name": "画画萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/画画萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，画画萌可在这里，咻咻~"
  },
  "睡睡萌可": {
    "key": "col_02_睡睡萌可_render",
    "name": "睡睡萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/睡睡萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！睡睡萌可来啦！"
  },
  "美美萌可": {
    "key": "col_02_美美萌可_render",
    "name": "美美萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/美美萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，美美萌可在这里，咻咻~"
  },
  "聪明萌可": {
    "key": "col_02_聪明萌可_render",
    "name": "聪明萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/聪明萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，飘飘~ 我是聪明萌可！"
  },
  "花花萌可": {
    "key": "col_02_花花萌可_render",
    "name": "花花萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/花花萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是花花萌可！"
  },
  "贪贪萌可": {
    "key": "col_02_贪贪萌可_render",
    "name": "贪贪萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/贪贪萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！贪贪萌可来啦！"
  },
  "赛赛萌可": {
    "key": "col_02_赛赛萌可_render",
    "name": "赛赛萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/赛赛萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是赛赛萌可！"
  },
  "迷糊萌可": {
    "key": "col_02_迷糊萌可_render",
    "name": "迷糊萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/迷糊萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "灵灵~ 我是迷糊萌可！"
  },
  "速速萌可": {
    "key": "col_02_速速萌可_render",
    "name": "速速萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/速速萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是速速萌可！"
  },
  "重重萌可": {
    "key": "col_02_重重萌可_render",
    "name": "重重萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/重重萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，重重萌可在这里，咻咻~"
  },
  "黏黏萌可": {
    "key": "col_02_黏黏萌可_render",
    "name": "黏黏萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/黏黏萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，黏黏萌可在这里，咻咻~"
  },
  "公主萌可": {
    "key": "col_03_公主萌可_render",
    "name": "公主萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/公主萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "亮晶晶~ 我是公主萌可！"
  },
  "净净萌可": {
    "key": "col_03_净净萌可_render",
    "name": "净净萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/净净萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "透透！净净萌可来啦！"
  },
  "分享萌可": {
    "key": "col_03_分享萌可_render",
    "name": "分享萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/分享萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "分享萌可登场，亮晶晶~"
  },
  "双双萌可": {
    "key": "col_03_双双萌可_render",
    "name": "双双萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/双双萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "呼呼，双双萌可在这里，耀耀~"
  },
  "嘻嘻萌可": {
    "key": "col_03_嘻嘻萌可_render",
    "name": "嘻嘻萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/嘻嘻萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，耀耀~ 我是嘻嘻萌可！"
  },
  "安慰萌可": {
    "key": "col_03_安慰萌可_render",
    "name": "安慰萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/安慰萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "亮晶晶~ 我是安慰萌可！"
  },
  "弱弱萌可": {
    "key": "col_03_弱弱萌可_render",
    "name": "弱弱萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/弱弱萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "晶晶！弱弱萌可来啦！"
  },
  "愿望萌可": {
    "key": "col_03_愿望萌可_render",
    "name": "愿望萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/愿望萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，熠熠~ 我是愿望萌可！"
  },
  "暖暖萌可": {
    "key": "col_03_暖暖萌可_render",
    "name": "暖暖萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/暖暖萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "透透！暖暖萌可来啦！"
  },
  "神奇萌可": {
    "key": "col_03_神奇萌可_render",
    "name": "神奇萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/神奇萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，绚绚~ 我是神奇萌可！"
  },
  "笔记萌可": {
    "key": "col_03_笔记萌可_render",
    "name": "笔记萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/笔记萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，熠熠~ 我是笔记萌可！"
  },
  "美味萌可": {
    "key": "col_03_美味萌可_render",
    "name": "美味萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/美味萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，bling~ 我是美味萌可！"
  },
  "芭蕾萌可": {
    "key": "col_03_芭蕾萌可_render",
    "name": "芭蕾萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/芭蕾萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "芭蕾萌可登场，bling~"
  },
  "躲躲萌可": {
    "key": "col_03_躲躲萌可_render",
    "name": "躲躲萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/躲躲萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "呼呼，躲躲萌可在这里，耀耀~"
  },
  "雕刻萌可": {
    "key": "col_03_雕刻萌可_render",
    "name": "雕刻萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/雕刻萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "璀璨！雕刻萌可来啦！"
  },
  "人鱼萌可": {
    "key": "col_04_人鱼萌可_render",
    "name": "人鱼萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/人鱼萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "呼呼，人鱼萌可在这里，叮当~"
  },
  "修理萌可": {
    "key": "col_04_修理萌可_render",
    "name": "修理萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/修理萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "呼呼，修理萌可在这里，叮当~"
  },
  "加油萌可": {
    "key": "col_04_加油萌可_render",
    "name": "加油萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/加油萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "加油萌可登场，寻寻~"
  },
  "医生萌可": {
    "key": "col_04_医生萌可_render",
    "name": "医生萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/医生萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，探索~ 我是医生萌可！"
  },
  "发明萌可": {
    "key": "col_04_发明萌可_render",
    "name": "发明萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/发明萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，锁好~ 我是发明萌可！"
  },
  "吞吞萌可": {
    "key": "col_04_吞吞萌可_render",
    "name": "吞吞萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/吞吞萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "锁好！吞吞萌可来啦！"
  },
  "快快萌可": {
    "key": "col_04_快快萌可_render",
    "name": "快快萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/快快萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "钥匙！快快萌可来啦！"
  },
  "时尚萌可": {
    "key": "col_04_时尚萌可_render",
    "name": "时尚萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/时尚萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "钥匙！时尚萌可来啦！"
  },
  "歌声萌可": {
    "key": "col_04_歌声萌可_render",
    "name": "歌声萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/歌声萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "呼呼，歌声萌可在这里，猜猜~"
  },
  "气气萌可": {
    "key": "col_04_气气萌可_render",
    "name": "气气萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/气气萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "呼呼，气气萌可在这里，猜猜~"
  },
  "派对萌可": {
    "key": "col_04_派对萌可_render",
    "name": "派对萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/派对萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "派对萌可登场，猜猜~"
  },
  "滑冰萌可": {
    "key": "col_04_滑冰萌可_render",
    "name": "滑冰萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/滑冰萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，解密~ 我是滑冰萌可！"
  },
  "灭火萌可": {
    "key": "col_04_灭火萌可_render",
    "name": "灭火萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/灭火萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，探索~ 我是灭火萌可！"
  },
  "美发萌可": {
    "key": "col_04_美发萌可_render",
    "name": "美发萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/美发萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，解密~ 我是美发萌可！"
  },
  "警察萌可": {
    "key": "col_04_警察萌可_render",
    "name": "警察萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/警察萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，钥匙~ 我是警察萌可！"
  },
  "冰沙萌可": {
    "key": "col_05_冰沙萌可_render",
    "name": "冰沙萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/冰沙萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "华夫~ 我是冰沙萌可！"
  },
  "华夫萌可": {
    "key": "col_05_华夫萌可_render",
    "name": "华夫萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/华夫萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "软软~ 我是华夫萌可！"
  },
  "夹心萌可": {
    "key": "col_05_夹心萌可_render",
    "name": "夹心萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/夹心萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "呼呼，夹心萌可在这里，棒棒~"
  },
  "奶油萌可": {
    "key": "col_05_奶油萌可_render",
    "name": "奶油萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/奶油萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "香香~ 我是奶油萌可！"
  },
  "巧克力萌可": {
    "key": "col_05_巧克力萌可_render",
    "name": "巧克力萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/巧克力萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "巧克力萌可登场，糖糖~"
  },
  "布丁萌可": {
    "key": "col_05_布丁萌可_render",
    "name": "布丁萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/布丁萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，甜甜~ 我是布丁萌可！"
  },
  "松饼萌可": {
    "key": "col_05_松饼萌可_render",
    "name": "松饼萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/松饼萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，糖糖~ 我是松饼萌可！"
  },
  "棉花糖萌可": {
    "key": "col_05_棉花糖萌可_render",
    "name": "棉花糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/棉花糖萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，凉凉~ 我是棉花糖萌可！"
  },
  "棒棒糖萌可": {
    "key": "col_05_棒棒糖萌可_render",
    "name": "棒棒糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/棒棒糖萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "呼呼，棒棒糖萌可在这里，甜甜~"
  },
  "泡泡萌可": {
    "key": "col_05_泡泡萌可_render",
    "name": "泡泡萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/泡泡萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "糯糯！泡泡萌可来啦！"
  },
  "甜甜圈萌可": {
    "key": "col_05_甜甜圈萌可_render",
    "name": "甜甜圈萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/甜甜圈萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "呼呼，甜甜圈萌可在这里，呼呼~"
  },
  "糖糖萌可": {
    "key": "col_05_糖糖萌可_render",
    "name": "糖糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/糖糖萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "糖糖~ 我是糖糖萌可，甜滋滋！"
  },
  "蛋糕妹妹萌可": {
    "key": "col_05_蛋糕妹妹萌可_render",
    "name": "蛋糕妹妹萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕妹妹萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "呼呼，蛋糕妹妹萌可在这里，糯糯~"
  },
  "蛋糕妹妹萌可·蛋糕弟弟萌可": {
    "key": "col_05_蛋糕妹妹萌可_蛋糕弟弟萌可_render",
    "name": "蛋糕妹妹萌可·蛋糕弟弟萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕妹妹萌可_蛋糕弟弟萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "呼呼！蛋糕妹妹萌可·蛋糕弟弟萌可来啦！"
  },
  "蛋糕弟弟萌可": {
    "key": "col_05_蛋糕弟弟萌可_render",
    "name": "蛋糕弟弟萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕弟弟萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，绵绵~ 我是蛋糕弟弟萌可！"
  },
  "酸奶萌可": {
    "key": "col_05_酸奶萌可_render",
    "name": "酸奶萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/酸奶萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "呼呼，酸奶萌可在这里，蜜蜜~"
  },
  "马卡龙萌可": {
    "key": "col_05_马卡龙萌可_render",
    "name": "马卡龙萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/马卡龙萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，巧巧~ 我是马卡龙萌可！"
  },
  "乐美公主": {
    "key": "col_06_乐美萌可_render",
    "name": "乐美公主",
    "category": "guide",
    "season": "星星萌可_第六季",
    "img": "/moko/lemei.jpg",
    "emoji": "👑",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "一起捕捉萌可吧！"
  },
  "亲亲萌可": {
    "key": "col_06_亲亲萌可_render",
    "name": "亲亲萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/亲亲萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "亲亲~ 我是亲亲萌可，mua！"
  },
  "光明萌可": {
    "key": "col_06_光明萌可_render",
    "name": "光明萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/光明萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "光明~ 我是光明萌可，照亮你！"
  },
  "兔兔萌可": {
    "key": "col_06_兔兔萌可_render",
    "name": "兔兔萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/兔兔萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "跳跳~ 我是兔兔萌可，蹦蹦跳！"
  },
  "共共萌可": {
    "key": "col_06_共共萌可_render",
    "name": "共共萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/共共萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "共共~ 我是共共萌可，一起分享！"
  },
  "动动萌可": {
    "key": "col_06_动动萌可_render",
    "name": "动动萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/动动萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "动动~ 我是动动萌可，动起来！"
  },
  "叮咚萌可": {
    "key": "col_06_叮咚萌可_render",
    "name": "叮咚萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/叮咚萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "叮咚~ 我是叮咚萌可，门铃响啦！"
  },
  "呼啦萌可": {
    "key": "col_06_呼啦萌可_render",
    "name": "呼啦萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/呼啦萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼啦~ 我是呼啦萌可，转圈圈！"
  },
  "悄悄萌可": {
    "key": "col_06_悄悄萌可_render",
    "name": "悄悄萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/悄悄萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "悄悄~ 我是悄悄萌可，别出声～"
  },
  "歌谣萌可": {
    "key": "col_06_歌谣萌可_render",
    "name": "歌谣萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/歌谣萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "歌谣~ 我是歌谣萌可，唱起来！"
  },
  "流浪萌可": {
    "key": "col_06_流浪萌可_render",
    "name": "流浪萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/流浪萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "嗖嗖~ 我是流浪萌可！"
  },
  "熊熊萌可": {
    "key": "col_06_熊熊萌可_render",
    "name": "熊熊萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/熊熊萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "熊熊~ 我是熊熊萌可，抱抱你！"
  },
  "狐狐萌可": {
    "key": "col_06_狐狐萌可_render",
    "name": "狐狐萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/狐狐萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "狐狐~ 我是狐狐萌可，狡黠一笑！"
  },
  "纷纷萌可": {
    "key": "col_06_纷纷萌可_render",
    "name": "纷纷萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/纷纷萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "纷纷~ 我是纷纷萌可，飘呀飘！"
  },
  "绵羊萌可": {
    "key": "col_06_绵羊萌可_render",
    "name": "绵羊萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/绵羊萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咩咩~ 我是绵羊萌可，软软的！"
  },
  "缤缤萌可": {
    "key": "col_06_缤缤萌可_render",
    "name": "缤缤萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/缤缤萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "缤缤~ 我是缤缤萌可，五彩缤纷！"
  },
  "缤缤萌可·纷纷萌可": {
    "key": "col_06_缤缤萌可_纷纷萌可_render",
    "name": "缤缤萌可·纷纷萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/缤缤萌可_纷纷萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "望望！缤缤萌可·纷纷萌可来啦！"
  },
  "贴贴萌可": {
    "key": "col_06_贴贴萌可_render",
    "name": "贴贴萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/贴贴萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "贴贴~ 我是贴贴萌可，贴贴你！"
  },
  "跳舞萌可": {
    "key": "col_06_跳舞萌可_render",
    "name": "跳舞萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/跳舞萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "跳舞~ 我是跳舞萌可，转个圈！"
  },
  "透明萌可": {
    "key": "col_06_透明萌可_render",
    "name": "透明萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/透明萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "玻璃~ 我是透明萌可，看不见啦！"
  },
  "丘比特萌可": {
    "key": "col_07_丘比特萌可_render",
    "name": "丘比特萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/丘比特萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "丘比特萌可登场，月光~"
  },
  "丝绸萌可": {
    "key": "col_07_丝绸萌可_render",
    "name": "丝绸萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/丝绸萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "丝绸萌可登场，灵灵~"
  },
  "困困萌可": {
    "key": "col_07_困困萌可_render",
    "name": "困困萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/困困萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "呼呼，困困萌可在这里，自信~"
  },
  "洗洗萌可": {
    "key": "col_07_洗洗萌可_render",
    "name": "洗洗萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/洗洗萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "自信！洗洗萌可来啦！"
  },
  "猫猫萌可": {
    "key": "col_07_猫猫萌可_render",
    "name": "猫猫萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/猫猫萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "呼呼，猫猫萌可在这里，自信~"
  },
  "玲珑萌可": {
    "key": "col_07_玲珑萌可_render",
    "name": "玲珑萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/玲珑萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "华丽~ 我是玲珑萌可！"
  },
  "白雪萌可": {
    "key": "col_07_白雪萌可_render",
    "name": "白雪萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/白雪萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，月光~ 我是白雪萌可！"
  },
  "蝴蝶萌可": {
    "key": "col_07_蝴蝶萌可_render",
    "name": "蝴蝶萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/蝴蝶萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "优雅！蝴蝶萌可来啦！"
  },
  "露水萌可": {
    "key": "col_07_露水萌可_render",
    "name": "露水萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/露水萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "呼呼，露水萌可在这里，优雅~"
  },
  "鞋鞋萌可": {
    "key": "col_07_鞋鞋萌可_render",
    "name": "鞋鞋萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/鞋鞋萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "呼呼，鞋鞋萌可在这里，自信~"
  },
  "魅力萌可": {
    "key": "col_07_魅力萌可_render",
    "name": "魅力萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/魅力萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，盈盈~ 我是魅力萌可！"
  },
  "查尔斯王子": {
    "key": "col_08_查尔斯萌可_render",
    "name": "查尔斯王子",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/查尔斯萌可_render.webp",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，凛凛~ 我是查尔斯王子！"
  },
  "演歌萌可": {
    "key": "col_08_演歌萌可_render",
    "name": "演歌萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/演歌萌可_render.webp",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，剑剑~ 我是演歌萌可！"
  },
  "绅士萌可": {
    "key": "col_08_绅士萌可_render",
    "name": "绅士萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/绅士萌可_render.webp",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "呼呼，绅士萌可在这里，英英~"
  },
  "青蛙萌可": {
    "key": "col_08_青蛙萌可_render",
    "name": "青蛙萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/青蛙萌可_render.webp",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "帅帅~ 我是青蛙萌可！"
  },
  "奉献萌可": {
    "key": "col_09_奉献萌可_render",
    "name": "奉献萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/奉献萌可_render.webp",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "嘻嘻~ 我是奉献萌可！"
  },
  "闹闹萌可": {
    "key": "col_09_闹闹萌可_render",
    "name": "闹闹萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/闹闹萌可_render.webp",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "呼呼，闹闹萌可在这里，鬼鬼~"
  },
  "幸运萌可": {
    "key": "col_10_幸运萌可_render",
    "name": "幸运萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/幸运萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "呼呼，幸运萌可在这里，运运~"
  },
  "月神萌可": {
    "key": "col_10_月神萌可_render",
    "name": "月神萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/月神萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，灿灿~ 我是月神萌可！"
  },
  "月食萌可": {
    "key": "col_10_月食萌可_render",
    "name": "月食萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/月食萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，奇奇~ 我是月食萌可！"
  },
  "极光萌可": {
    "key": "col_10_极光萌可_render",
    "name": "极光萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/极光萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "极光~ 我是极光萌可，绚丽登场！"
  },
  "甜甜萌可": {
    "key": "col_10_甜甜萌可_render",
    "name": "甜甜萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/甜甜萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，闪耀~ 我是甜甜萌可！"
  },
  "酸酸萌可": {
    "key": "col_10_酸酸萌可_render",
    "name": "酸酸萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/酸酸萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，闪耀~ 我是酸酸萌可！"
  }
};
