// RAZ AA 级核心词汇，按绘本主题分类
// 来源：RAZ AA 级绘本内容提取

export interface RazVocabItem {
  word: string;
  emoji: string;
  cn: string;
  book: string; // 来源绘本 id
  sentence: string;
}

export const RAZ_VOCAB: Record<string, RazVocabItem[]> = {
  动物: [
    { word: 'cat', emoji: '🐱', cn: '猫', book: 'AA-04Pets', sentence: 'I see a cat.' },
    { word: 'dog', emoji: '🐶', cn: '狗', book: 'AA-04Pets', sentence: 'I see a dog.' },
    { word: 'pig', emoji: '🐷', cn: '猪', book: 'AA-01Farm_Animals', sentence: 'The pig is on the farm.' },
    { word: 'cow', emoji: '🐮', cn: '牛', book: 'AA-01Farm_Animals', sentence: 'The cow is big.' },
    { word: 'sheep', emoji: '🐑', cn: '羊', book: 'AA-01Farm_Animals', sentence: 'The sheep has wool.' },
    { word: 'horse', emoji: '🐴', cn: '马', book: 'AA-01Farm_Animals', sentence: 'The horse runs fast.' },
    { word: 'duck', emoji: '🦆', cn: '鸭子', book: 'AA-01Farm_Animals', sentence: 'The duck swims.' },
    { word: 'bird', emoji: '🐦', cn: '鸟', book: 'AA-16These_Birds', sentence: 'I see birds.' },
    { word: 'fish', emoji: '🐟', cn: '鱼', book: 'AA-13The_Ocean', sentence: 'The fish is in the water.' },
    { word: 'bug', emoji: '🐛', cn: '虫子', book: 'AA-41Counting_Bugs', sentence: 'I see bugs.' },
    { word: 'bee', emoji: '🐝', cn: '蜜蜂', book: 'AA-41Counting_Bugs', sentence: 'The bee flies.' },
    { word: 'ant', emoji: '🐜', cn: '蚂蚁', book: 'AA-41Counting_Bugs', sentence: 'The ant is small.' },
    { word: 'butterfly', emoji: '🦋', cn: '蝴蝶', book: 'AA-41Counting_Bugs', sentence: 'The butterfly is beautiful.' },
    { word: 'chicken', emoji: '🐔', cn: '鸡', book: 'AA-15The_Chicken', sentence: 'The chicken lays eggs.' },
    { word: 'lion', emoji: '🦁', cn: '狮子', book: 'AA-06Rainforest_Animals', sentence: 'The lion is big.' },
    { word: 'monkey', emoji: '🐵', cn: '猴子', book: 'AA-06Rainforest_Animals', sentence: 'The monkey climbs trees.' },
    { word: 'snake', emoji: '🐍', cn: '蛇', book: 'AA-06Rainforest_Animals', sentence: 'The snake is long.' },
    { word: 'tiger', emoji: '🐯', cn: '老虎', book: 'AA-18Jungle_Friends', sentence: 'The tiger is in the jungle.' },
    { word: 'elephant', emoji: '🐘', cn: '大象', book: 'AA-05Plains_Animals', sentence: 'The elephant is big.' },
    { word: 'zebra', emoji: '🦓', cn: '斑马', book: 'AA-05Plains_Animals', sentence: 'The zebra has stripes.' },
    { word: 'rabbit', emoji: '🐰', cn: '兔子', book: 'AA-04Pets', sentence: 'The rabbit is small.' },
    { word: 'mouse', emoji: '🐭', cn: '老鼠', book: 'AA-04Pets', sentence: 'The mouse is small.' },
    { word: 'frog', emoji: '🐸', cn: '青蛙', book: 'AA-07The_Coast', sentence: 'The frog is in the water.' },
  ],
  颜色: [
    { word: 'red', emoji: '🔴', cn: '红色', book: 'AA-26Red', sentence: 'The ball is red.' },
    { word: 'blue', emoji: '🔵', cn: '蓝色', book: 'AA-23Blue', sentence: 'The sky is blue.' },
    { word: 'green', emoji: '🟢', cn: '绿色', book: 'AA-24Green', sentence: 'The grass is green.' },
    { word: 'yellow', emoji: '🟡', cn: '黄色', book: 'AA-22Yellow', sentence: 'The sun is yellow.' },
    { word: 'orange', emoji: '🟠', cn: '橙色', book: 'AA-25Orange', sentence: 'The orange is orange.' },
    { word: 'purple', emoji: '🟣', cn: '紫色', book: 'AA-21Purple', sentence: 'The grape is purple.' },
    { word: 'white', emoji: '⚪', cn: '白色', book: 'AA-27White', sentence: 'The snow is white.' },
    { word: 'black', emoji: '⚫', cn: '黑色', book: 'AA-28Black', sentence: 'The cat is black.' },
    { word: 'pink', emoji: '🌸', cn: '粉色', book: 'AA-26Red', sentence: 'The flower is pink.' },
    { word: 'brown', emoji: '🟤', cn: '棕色', book: 'AA-28Black', sentence: 'The bear is brown.' },
  ],
  数字: [
    { word: 'one', emoji: '1️⃣', cn: '一', book: 'AA-29One', sentence: 'One apple.' },
    { word: 'two', emoji: '2️⃣', cn: '二', book: 'AA-30Two', sentence: 'Two cats.' },
    { word: 'three', emoji: '3️⃣', cn: '三', book: 'AA-31Three', sentence: 'Three dogs.' },
    { word: 'four', emoji: '4️⃣', cn: '四', book: 'AA-32Four', sentence: 'Four birds.' },
    { word: 'five', emoji: '5️⃣', cn: '五', book: 'AA-33Five', sentence: 'Five fish.' },
    { word: 'six', emoji: '6️⃣', cn: '六', book: 'AA-34Six', sentence: 'Six bugs.' },
    { word: 'seven', emoji: '7️⃣', cn: '七', book: 'AA-35Seven', sentence: 'Seven bees.' },
    { word: 'eight', emoji: '8️⃣', cn: '八', book: 'AA-36Eight', sentence: 'Eight ants.' },
    { word: 'nine', emoji: '9️⃣', cn: '九', book: 'AA-37Nine', sentence: 'Nine butterflies.' },
    { word: 'ten', emoji: '🔟', cn: '十', book: 'AA-38Ten', sentence: 'Ten animals.' },
    { word: 'eleven', emoji: '1️⃣1️⃣', cn: '十一', book: 'AA-39Eleven', sentence: 'Eleven stars.' },
    { word: 'twelve', emoji: '1️⃣2️⃣', cn: '十二', book: 'AA-40Twelve', sentence: 'Twelve eggs.' },
  ],
  季节天气: [
    { word: 'spring', emoji: '🌸', cn: '春天', book: 'AA-09Spring', sentence: 'Spring is here.' },
    { word: 'summer', emoji: '☀️', cn: '夏天', book: 'AA-10Summer', sentence: 'Summer is hot.' },
    { word: 'fall', emoji: '🍂', cn: '秋天', book: 'AA-11It_Is_Fall', sentence: 'Fall is here.' },
    { word: 'winter', emoji: '❄️', cn: '冬天', book: 'AA-12Winter', sentence: 'Winter is cold.' },
    { word: 'rain', emoji: '🌧️', cn: '雨', book: 'AA-17Rain_on_Fairyland', sentence: 'It is raining.' },
    { word: 'snow', emoji: '🌨️', cn: '雪', book: 'AA-12Winter', sentence: 'It is snowing.' },
    { word: 'sun', emoji: '☀️', cn: '太阳', book: 'AA-10Summer', sentence: 'The sun is hot.' },
    { word: 'cloud', emoji: '☁️', cn: '云', book: 'AA-17Rain_on_Fairyland', sentence: 'The cloud is white.' },
    { word: 'wind', emoji: '💨', cn: '风', book: 'AA-09Spring', sentence: 'The wind blows.' },
    { word: 'hot', emoji: '🔥', cn: '热', book: 'AA-10Summer', sentence: 'It is hot.' },
    { word: 'cold', emoji: '🥶', cn: '冷', book: 'AA-12Winter', sentence: 'It is cold.' },
    { word: 'warm', emoji: '🌤️', cn: '温暖', book: 'AA-09Spring', sentence: 'It is warm.' },
  ],
  场所: [
    { word: 'school', emoji: '🏫', cn: '学校', book: 'AA-61The_School', sentence: 'I go to school.' },
    { word: 'classroom', emoji: '🏫', cn: '教室', book: 'AA-62The_Classroom', sentence: 'We are in the classroom.' },
    { word: 'playground', emoji: '🎠', cn: '操场', book: 'AA-47The_Playground', sentence: 'We play on the playground.' },
    { word: 'kitchen', emoji: '🍳', cn: '厨房', book: 'AA-77This_Kitchen', sentence: 'I am in the kitchen.' },
    { word: 'bathroom', emoji: '🛁', cn: '浴室', book: 'AA-78My_Bath', sentence: 'I bathe in the bathroom.' },
    { word: 'bedroom', emoji: '🛏️', cn: '卧室', book: 'AA-86Mom', sentence: 'I sleep in the bedroom.' },
    { word: 'park', emoji: '🌳', cn: '公园', book: 'AA-69At_the_Lake', sentence: 'We go to the park.' },
    { word: 'zoo', emoji: '🦁', cn: '动物园', book: 'AA-58The_Trip', sentence: 'We go to the zoo.' },
    { word: 'store', emoji: '🏪', cn: '商店', book: 'AA-66The_Bookstore', sentence: 'We go to the store.' },
    { word: 'bookstore', emoji: '📚', cn: '书店', book: 'AA-66The_Bookstore', sentence: 'I buy books at the bookstore.' },
    { word: 'hospital', emoji: '🏥', cn: '医院', book: 'AA-50Too_Many_Sweets', sentence: 'We go to the hospital.' },
    { word: 'city', emoji: '🏙️', cn: '城市', book: 'AA-45City_Street', sentence: 'The city is big.' },
    { word: 'street', emoji: '🛣️', cn: '街道', book: 'AA-44The_Street', sentence: 'The street is busy.' },
    { word: 'ocean', emoji: '🌊', cn: '海洋', book: 'AA-13The_Ocean', sentence: 'The ocean is big.' },
    { word: 'lake', emoji: '🏞️', cn: '湖泊', book: 'AA-69At_the_Lake', sentence: 'We swim in the lake.' },
    { word: 'garden', emoji: '🌻', cn: '花园', book: 'AA-55The_Garden', sentence: 'The garden is beautiful.' },
    { word: 'farm', emoji: '🚜', cn: '农场', book: 'AA-01Farm_Animals', sentence: 'The farm has animals.' },
    { word: 'camp', emoji: '⛺', cn: '营地', book: 'AA-63Summer_Camp', sentence: 'We go to camp.' },
    { word: 'bus', emoji: '🚌', cn: '公交车', book: 'AA-71My_School_Bus', sentence: 'I ride the bus.' },
    { word: 'car', emoji: '🚗', cn: '汽车', book: 'AA-45City_Street', sentence: 'The car is fast.' },
  ],
  动作: [
    { word: 'run', emoji: '🏃', cn: '跑', book: 'AA-02Go_Go_Go', sentence: 'I can run.' },
    { word: 'jump', emoji: '🦘', cn: '跳', book: 'AA-03Jump_Over', sentence: 'I can jump.' },
    { word: 'swim', emoji: '🏊', cn: '游泳', book: 'AA-69At_the_Lake', sentence: 'I can swim.' },
    { word: 'read', emoji: '📖', cn: '阅读', book: 'AA-84The_Book', sentence: 'I read a book.' },
    { word: 'write', emoji: '✏️', cn: '写', book: 'AA-84The_Book', sentence: 'I write a word.' },
    { word: 'play', emoji: '🎮', cn: '玩', book: 'AA-79Toys', sentence: 'I play with toys.' },
    { word: 'eat', emoji: '🍎', cn: '吃', book: 'AA-53Pasta', sentence: 'I eat pasta.' },
    { word: 'drink', emoji: '💧', cn: '喝', book: 'AA-08Water', sentence: 'I drink water.' },
    { word: 'sleep', emoji: '😴', cn: '睡觉', book: 'AA-89Good_Night', sentence: 'I sleep at night.' },
    { word: 'walk', emoji: '🚶', cn: '走', book: 'AA-47The_Playground', sentence: 'I walk to school.' },
    { word: 'sing', emoji: '🎤', cn: '唱', book: 'AA-75The_Birthday_Party', sentence: 'We sing a song.' },
    { word: 'dance', emoji: '💃', cn: '跳舞', book: 'AA-75The_Birthday_Party', sentence: 'I can dance.' },
    { word: 'build', emoji: '🧱', cn: '建造', book: 'AA-80We_Build', sentence: 'We build a house.' },
    { word: 'climb', emoji: '🧗', cn: '爬', book: 'AA-06Rainforest_Animals', sentence: 'The monkey climbs trees.' },
    { word: 'fly', emoji: '🦅', cn: '飞', book: 'AA-16These_Birds', sentence: 'The bird can fly.' },
  ],
  食物: [
    { word: 'apple', emoji: '🍎', cn: '苹果', book: 'AA-73Picking_Apples', sentence: 'I eat an apple.' },
    { word: 'water', emoji: '💧', cn: '水', book: 'AA-08Water', sentence: 'I drink water.' },
    { word: 'pasta', emoji: '🍝', cn: '意大利面', book: 'AA-53Pasta', sentence: 'I eat pasta.' },
    { word: 'sweets', emoji: '🍬', cn: '糖果', book: 'AA-50Too_Many_Sweets', sentence: 'I eat sweets.' },
    { word: 'bread', emoji: '🍞', cn: '面包', book: 'AA-51Lunch_at_School', sentence: 'I eat bread.' },
    { word: 'juice', emoji: '🧃', cn: '果汁', book: 'AA-51Lunch_at_School', sentence: 'I drink juice.' },
    { word: 'milk', emoji: '🥛', cn: '牛奶', book: 'AA-51Lunch_at_School', sentence: 'I drink milk.' },
    { word: 'egg', emoji: '🥚', cn: '鸡蛋', book: 'AA-20Colorful_Eggs', sentence: 'The egg is colorful.' },
    { word: 'orange', emoji: '🍊', cn: '橙子', book: 'AA-25Orange', sentence: 'I eat an orange.' },
    { word: 'banana', emoji: '🍌', cn: '香蕉', book: 'AA-22Yellow', sentence: 'I eat a banana.' },
  ],
  方位: [
    { word: 'big', emoji: '🐘', cn: '大', book: 'AA-91Big', sentence: 'The elephant is big.' },
    { word: 'little', emoji: '🐭', cn: '小', book: 'AA-92Little', sentence: 'The mouse is little.' },
    { word: 'under', emoji: '⬇️', cn: '在…下面', book: 'AA-93Under', sentence: 'The ball is under the table.' },
    { word: 'on', emoji: '⬆️', cn: '在…上面', book: 'AA-94On', sentence: 'The book is on the desk.' },
    { word: 'in', emoji: '📦', cn: '在…里面', book: 'AA-95In', sentence: 'The ball is in the box.' },
    { word: 'out', emoji: '🚪', cn: '在…外面', book: 'AA-96Out', sentence: 'We go out.' },
    { word: 'over', emoji: '⬆️', cn: '在…上方', book: 'AA-98Over', sentence: 'The bird is over the tree.' },
    { word: 'off', emoji: '❌', cn: '离开', book: 'AA-97Off', sentence: 'Take off your hat.' },
    { word: 'up', emoji: '⬆️', cn: '向上', book: 'AA-91Big', sentence: 'I go up.' },
    { word: 'down', emoji: '⬇️', cn: '向下', book: 'AA-92Little', sentence: 'I go down.' },
  ],
  家庭: [
    { word: 'mom', emoji: '👩', cn: '妈妈', book: 'AA-86Mom', sentence: 'I love my mom.' },
    { word: 'dad', emoji: '👨', cn: '爸爸', book: 'AA-88My_Family', sentence: 'I love my dad.' },
    { word: 'sister', emoji: '👧', cn: '姐姐/妹妹', book: 'AA-88My_Family', sentence: 'I have a sister.' },
    { word: 'brother', emoji: '👦', cn: '哥哥/弟弟', book: 'AA-88My_Family', sentence: 'I have a brother.' },
    { word: 'family', emoji: '👨‍👩‍👧‍👦', cn: '家庭', book: 'AA-88My_Family', sentence: 'My family is happy.' },
    { word: 'house', emoji: '🏠', cn: '房子', book: 'AA-88My_Family', sentence: 'We live in a house.' },
    { word: 'baby', emoji: '👶', cn: '宝宝', book: 'AA-86Mom', sentence: 'The baby is sleeping.' },
    { word: 'love', emoji: '❤️', cn: '爱', book: 'AA-76Show_Some_Love', sentence: 'I love you.' },
    { word: 'gift', emoji: '🎁', cn: '礼物', book: 'AA-54My_Gift_for_Mom', sentence: 'This is a gift.' },
    { word: 'happy', emoji: '😊', cn: '开心', book: 'AA-75The_Birthday_Party', sentence: 'I am happy.' },
  ],
};

/** 获取 RAZ 全部词汇（扁平化） */
export const RAZ_ALL_WORDS: RazVocabItem[] = Object.values(RAZ_VOCAB).flat();

/** 按词频排序的 RAZ AA 高频词 */
export const RAZ_TOP_WORDS = RAZ_ALL_WORDS.slice(0, 50).map((w) => w.word);