/**
 * 英语基础数据：字母、核心单词（按主题）、全部单词聚合。
 * 从 study-data.ts 拆分出来，避免主数据文件过于庞大（原 2354 行单文件）。
 * 本文件自包含，不反向依赖 study-data.ts，避免循环引用；
 * study-data.ts 通过 `export * from './study-data-en'` 对外透出同名导出。
 */

/* -------------------- 英语 -------------------- */
export interface LetterItem {
  letter: string;
  word: string;
  emoji: string;
}

export const LETTERS: LetterItem[] = [
  { letter: 'A', word: 'Apple', emoji: '🍎' },
  { letter: 'B', word: 'Ball', emoji: '⚽' },
  { letter: 'C', word: 'Cat', emoji: '🐱' },
  { letter: 'D', word: 'Dog', emoji: '🐶' },
  { letter: 'E', word: 'Egg', emoji: '🥚' },
  { letter: 'F', word: 'Fish', emoji: '🐟' },
  { letter: 'G', word: 'Grapes', emoji: '🍇' },
  { letter: 'H', word: 'Hat', emoji: '🧢' },
  { letter: 'I', word: 'Ice cream', emoji: '🍦' },
  { letter: 'J', word: 'Juice', emoji: '🧃' },
  { letter: 'K', word: 'Kite', emoji: '🪁' },
  { letter: 'L', word: 'Lion', emoji: '🦁' },
  { letter: 'M', word: 'Moon', emoji: '🌙' },
  { letter: 'N', word: 'Nest', emoji: '🪺' },
  { letter: 'O', word: 'Orange', emoji: '🍊' },
  { letter: 'P', word: 'Pig', emoji: '🐷' },
  { letter: 'Q', word: 'Queen', emoji: '👑' },
  { letter: 'R', word: 'Rabbit', emoji: '🐰' },
  { letter: 'S', word: 'Sun', emoji: '☀️' },
  { letter: 'T', word: 'Tiger', emoji: '🐯' },
  { letter: 'U', word: 'Umbrella', emoji: '☂️' },
  { letter: 'V', word: 'Violin', emoji: '🎻' },
  { letter: 'W', word: 'Water', emoji: '💧' },
  { letter: 'X', word: 'Xylophone', emoji: '🎼' },
  { letter: 'Y', word: 'Yellow', emoji: '🟡' },
  { letter: 'Z', word: 'Zebra', emoji: '🦓' },
];

export interface WordItem {
  word: string;
  cn: string;
  emoji: string;
  sentence?: string;
}

// RAZ AA 级核心词 + 常见幼小词汇，按主题分类（约 170 词，覆盖一年级起点上册）
export const EN_WORD_TOPICS: Record<string, WordItem[]> = {
  动物: [
    { word: 'cat', cn: '猫', emoji: '🐱', sentence: 'I see a cat.' },
    { word: 'dog', cn: '狗', emoji: '🐶', sentence: 'I see a dog.' },
    { word: 'pig', cn: '猪', emoji: '🐷', sentence: 'The pig is pink.' },
    { word: 'duck', cn: '鸭子', emoji: '🦆', sentence: 'The duck says quack.' },
    { word: 'cow', cn: '牛', emoji: '🐮', sentence: 'The cow is big.' },
    { word: 'sheep', cn: '羊', emoji: '🐑', sentence: 'The sheep is white.' },
    { word: 'bird', cn: '鸟', emoji: '🐦', sentence: 'The bird can fly.' },
    { word: 'fish', cn: '鱼', emoji: '🐟', sentence: 'The fish can swim.' },
    { word: 'rabbit', cn: '兔子', emoji: '🐰', sentence: 'The rabbit is cute.' },
    { word: 'tiger', cn: '老虎', emoji: '🐯', sentence: 'The tiger is strong.' },
    { word: 'lion', cn: '狮子', emoji: '🦁', sentence: 'The lion is king.' },
    { word: 'elephant', cn: '大象', emoji: '🐘', sentence: 'The elephant is huge.' },
    { word: 'monkey', cn: '猴子', emoji: '🐵', sentence: 'The monkey is funny.' },
    { word: 'panda', cn: '熊猫', emoji: '🐼', sentence: 'The panda is black and white.' },
    { word: 'bear', cn: '熊', emoji: '🐻', sentence: 'The bear is sleepy.' },
    { word: 'bee', cn: '蜜蜂', emoji: '🐝', sentence: 'The bee is busy.' },
    { word: 'frog', cn: '青蛙', emoji: '🐸', sentence: 'The frog can jump.' },
    { word: 'fox', cn: '狐狸', emoji: '🦊', sentence: 'The fox is orange.' },
    { word: 'horse', cn: '马', emoji: '🐴', sentence: 'The horse runs fast.' },
    { word: 'mouse', cn: '老鼠', emoji: '🐭', sentence: 'The mouse is small.' },
    { word: 'chicken', cn: '鸡', emoji: '🐔', sentence: 'The chicken says cluck.' },
    { word: 'snake', cn: '蛇', emoji: '🐍', sentence: 'The snake is long.' },
    { word: 'turtle', cn: '乌龟', emoji: '🐢', sentence: 'The turtle is slow.' },
    { word: 'penguin', cn: '企鹅', emoji: '🐧', sentence: 'The penguin is cute.' },
    { word: 'whale', cn: '鲸鱼', emoji: '🐳', sentence: 'The whale is big.' },
  ],
  食物: [
    { word: 'apple', cn: '苹果', emoji: '🍎', sentence: 'I see an apple.' },
    { word: 'banana', cn: '香蕉', emoji: '🍌', sentence: 'I like bananas.' },
    { word: 'orange', cn: '橙子', emoji: '🍊', sentence: 'The orange is orange.' },
    { word: 'grape', cn: '葡萄', emoji: '🍇', sentence: 'The grapes are sweet.' },
    { word: 'pear', cn: '梨', emoji: '🍐', sentence: 'The pear is green.' },
    { word: 'watermelon', cn: '西瓜', emoji: '🍉', sentence: 'The watermelon is big.' },
    { word: 'egg', cn: '鸡蛋', emoji: '🥚', sentence: 'I eat an egg.' },
    { word: 'rice', cn: '米饭', emoji: '🍚', sentence: 'I eat rice.' },
    { word: 'bread', cn: '面包', emoji: '🍞', sentence: 'I like bread.' },
    { word: 'milk', cn: '牛奶', emoji: '🥛', sentence: 'I drink milk.' },
    { word: 'cake', cn: '蛋糕', emoji: '🍰', sentence: 'The cake is yummy.' },
    { word: 'pizza', cn: '披萨', emoji: '🍕', sentence: 'I like pizza.' },
    { word: 'burger', cn: '汉堡', emoji: '🍔', sentence: 'The burger is tasty.' },
    { word: 'cookie', cn: '饼干', emoji: '🍪', sentence: 'I eat a cookie.' },
    { word: 'icecream', cn: '冰淇淋', emoji: '🍦', sentence: 'I like ice cream.' },
    { word: 'juice', cn: '果汁', emoji: '🧃', sentence: 'I drink juice.' },
    { word: 'cheese', cn: '奶酪', emoji: '🧀', sentence: 'The cheese is yellow.' },
    { word: 'noodle', cn: '面条', emoji: '🍜', sentence: 'I eat noodles.' },
    { word: 'carrot', cn: '胡萝卜', emoji: '🥕', sentence: 'The carrot is orange.' },
    { word: 'tomato', cn: '西红柿', emoji: '🍅', sentence: 'The tomato is red.' },
    { word: 'meat', cn: '肉', emoji: '🍖', sentence: 'I eat meat.' },
  ],
  颜色: [
    { word: 'red', cn: '红色', emoji: '🔴', sentence: 'The apple is red.' },
    { word: 'orange', cn: '橙色', emoji: '🟠', sentence: 'The orange is orange.' },
    { word: 'yellow', cn: '黄色', emoji: '🟡', sentence: 'The sun is yellow.' },
    { word: 'green', cn: '绿色', emoji: '🟢', sentence: 'The tree is green.' },
    { word: 'blue', cn: '蓝色', emoji: '🔵', sentence: 'The sky is blue.' },
    { word: 'purple', cn: '紫色', emoji: '🟣', sentence: 'The grape is purple.' },
    { word: 'pink', cn: '粉色', emoji: '🩷', sentence: 'The pig is pink.' },
    { word: 'brown', cn: '棕色', emoji: '🤎', sentence: 'The bear is brown.' },
    { word: 'black', cn: '黑色', emoji: '⚫', sentence: 'The cat is black.' },
    { word: 'white', cn: '白色', emoji: '⚪', sentence: 'The cloud is white.' },
    { word: 'gray', cn: '灰色', emoji: '⚪', sentence: 'The mouse is gray.' },
    { word: 'gold', cn: '金色', emoji: '🟡', sentence: 'The star is gold.' },
  ],
  数字: [
    { word: 'zero', cn: '0', emoji: '0️⃣' },
    { word: 'one', cn: '1', emoji: '1️⃣' },
    { word: 'two', cn: '2', emoji: '2️⃣' },
    { word: 'three', cn: '3', emoji: '3️⃣' },
    { word: 'four', cn: '4', emoji: '4️⃣' },
    { word: 'five', cn: '5', emoji: '5️⃣' },
    { word: 'six', cn: '6', emoji: '6️⃣' },
    { word: 'seven', cn: '7', emoji: '7️⃣' },
    { word: 'eight', cn: '8', emoji: '8️⃣' },
    { word: 'nine', cn: '9', emoji: '9️⃣' },
    { word: 'ten', cn: '10', emoji: '🔟' },
  ],
  身体: [
    { word: 'eye', cn: '眼睛', emoji: '👁️', sentence: 'I have two eyes.' },
    { word: 'ear', cn: '耳朵', emoji: '👂', sentence: 'I have two ears.' },
    { word: 'nose', cn: '鼻子', emoji: '👃', sentence: 'I smell with my nose.' },
    { word: 'mouth', cn: '嘴巴', emoji: '👄', sentence: 'I eat with my mouth.' },
    { word: 'hand', cn: '手', emoji: '✋', sentence: 'I write with my hand.' },
    { word: 'foot', cn: '脚', emoji: '🦶', sentence: 'I walk with my foot.' },
    { word: 'head', cn: '头', emoji: '🙆', sentence: 'I shake my head.' },
    { word: 'arm', cn: '手臂', emoji: '💪', sentence: 'I raise my arms.' },
    { word: 'leg', cn: '腿', emoji: '🦵', sentence: 'I have two legs.' },
    { word: 'face', cn: '脸', emoji: '😐', sentence: 'I wash my face.' },
    { word: 'hair', cn: '头发', emoji: '💇', sentence: 'I comb my hair.' },
    { word: 'tooth', cn: '牙齿', emoji: '🦷', sentence: 'I brush my teeth.' },
    { word: 'finger', cn: '手指', emoji: '👆', sentence: 'I have ten fingers.' },
  ],
  自然: [
    { word: 'sun', cn: '太阳', emoji: '☀️', sentence: 'I see the sun.' },
    { word: 'moon', cn: '月亮', emoji: '🌙', sentence: 'I see the moon.' },
    { word: 'star', cn: '星星', emoji: '⭐', sentence: 'I see a star.' },
    { word: 'tree', cn: '树', emoji: '🌳', sentence: 'The tree is tall.' },
    { word: 'flower', cn: '花', emoji: '🌸', sentence: 'The flower is pretty.' },
    { word: 'cloud', cn: '云', emoji: '☁️', sentence: 'The cloud is white.' },
    { word: 'rain', cn: '雨', emoji: '🌧️', sentence: 'The rain falls down.' },
    { word: 'snow', cn: '雪', emoji: '❄️', sentence: 'The snow is cold.' },
    { word: 'wind', cn: '风', emoji: '🌬️', sentence: 'The wind blows.' },
    { word: 'fire', cn: '火', emoji: '🔥', sentence: 'The fire is hot.' },
    { word: 'water', cn: '水', emoji: '💧', sentence: 'I drink water.' },
    { word: 'mountain', cn: '山', emoji: '⛰️', sentence: 'The mountain is high.' },
    { word: 'river', cn: '河', emoji: '🌊', sentence: 'The river flows.' },
    { word: 'grass', cn: '草', emoji: '🌿', sentence: 'The grass is green.' },
    { word: 'leaf', cn: '叶子', emoji: '🍃', sentence: 'The leaf is green.' },
  ],
  动作: [
    { word: 'run', cn: '跑', emoji: '🏃', sentence: 'I can run.' },
    { word: 'jump', cn: '跳', emoji: '🦘', sentence: 'I can jump.' },
    { word: 'eat', cn: '吃', emoji: '🍽️', sentence: 'I like to eat.' },
    { word: 'sleep', cn: '睡觉', emoji: '😴', sentence: 'I go to sleep.' },
    { word: 'read', cn: '读', emoji: '📖', sentence: 'I read a book.' },
    { word: 'write', cn: '写', emoji: '✏️', sentence: 'I write a word.' },
    { word: 'sing', cn: '唱', emoji: '🎤', sentence: 'I like to sing.' },
    { word: 'swim', cn: '游泳', emoji: '🏊', sentence: 'I can swim.' },
    { word: 'dance', cn: '跳舞', emoji: '💃', sentence: 'I like to dance.' },
    { word: 'draw', cn: '画', emoji: '🎨', sentence: 'I draw a picture.' },
    { word: 'play', cn: '玩', emoji: '⚽', sentence: 'I play with my friend.' },
    { word: 'walk', cn: '走', emoji: '🚶', sentence: 'I walk to school.' },
    { word: 'fly', cn: '飞', emoji: '✈️', sentence: 'The bird can fly.' },
    { word: 'drink', cn: '喝', emoji: '🥤', sentence: 'I drink juice.' },
    { word: 'open', cn: '打开', emoji: '👐', sentence: 'I open the door.' },
    { word: 'cry', cn: '哭', emoji: '😢', sentence: 'The baby can cry.' },
    { word: 'laugh', cn: '笑', emoji: '😄', sentence: 'I laugh a lot.' },
  ],
  家人: [
    { word: 'dad', cn: '爸爸', emoji: '👨', sentence: 'I love my dad.' },
    { word: 'mom', cn: '妈妈', emoji: '👩', sentence: 'I love my mom.' },
    { word: 'baby', cn: '宝宝', emoji: '👶', sentence: 'The baby is small.' },
    { word: 'boy', cn: '男孩', emoji: '🧒', sentence: 'The boy is happy.' },
    { word: 'girl', cn: '女孩', emoji: '👧', sentence: 'The girl is cute.' },
    { word: 'grandpa', cn: '爷爷', emoji: '👴', sentence: 'I love my grandpa.' },
    { word: 'grandma', cn: '奶奶', emoji: '👵', sentence: 'I love my grandma.' },
    { word: 'brother', cn: '哥哥', emoji: '👦', sentence: 'My brother is big.' },
    { word: 'sister', cn: '姐姐', emoji: '👧', sentence: 'My sister is kind.' },
    { word: 'family', cn: '家庭', emoji: '👪', sentence: 'I love my family.' },
    { word: 'friend', cn: '朋友', emoji: '🤝', sentence: 'You are my friend.' },
    { word: 'teacher', cn: '老师', emoji: '👩‍🏫', sentence: 'The teacher is nice.' },
  ],
  衣物: [
    { word: 'shirt', cn: '衬衫', emoji: '👕', sentence: 'I wear a shirt.' },
    { word: 'pants', cn: '裤子', emoji: '👖', sentence: 'I wear pants.' },
    { word: 'dress', cn: '连衣裙', emoji: '👗', sentence: 'The dress is pretty.' },
    { word: 'shoe', cn: '鞋', emoji: '👟', sentence: 'I put on my shoe.' },
    { word: 'hat', cn: '帽子', emoji: '🧢', sentence: 'I wear a hat.' },
    { word: 'sock', cn: '袜子', emoji: '🧦', sentence: 'I wear socks.' },
    { word: 'coat', cn: '外套', emoji: '🧥', sentence: 'I wear a coat.' },
    { word: 'glove', cn: '手套', emoji: '🧤', sentence: 'I wear gloves.' },
    { word: 'scarf', cn: '围巾', emoji: '🧣', sentence: 'I wear a scarf.' },
    { word: 'glasses', cn: '眼镜', emoji: '👓', sentence: 'I have glasses.' },
  ],
  // —— 人教版（一年级起点）一年级上册 单元补充 ——
  学校: [
    { word: 'book', cn: '书', emoji: '📕', sentence: 'I have a book.' },
    { word: 'bag', cn: '书包', emoji: '🎒', sentence: 'This is my bag.' },
    { word: 'pen', cn: '钢笔', emoji: '🖊️', sentence: 'I have a pen.' },
    { word: 'pencil', cn: '铅笔', emoji: '✏️', sentence: 'I have a pencil.' },
    { word: 'ruler', cn: '尺子', emoji: '📏', sentence: 'I have a ruler.' },
    { word: 'eraser', cn: '橡皮', emoji: '🧽', sentence: 'I have an eraser.' },
    { word: 'school', cn: '学校', emoji: '🏫', sentence: 'This is my school.' },
    { word: 'crayon', cn: '蜡笔', emoji: '🖍️', sentence: 'I have a crayon.' },
    { word: 'desk', cn: '书桌', emoji: '🪑', sentence: 'I sit at the desk.' },
    { word: 'classroom', cn: '教室', emoji: '🏫', sentence: 'This is my classroom.' },
  ],
  问候: [
    { word: 'hello', cn: '你好', emoji: '👋', sentence: 'Hello! I am ...' },
    { word: 'hi', cn: '嗨', emoji: '🙋', sentence: 'Hi! I am ...' },
    { word: 'goodbye', cn: '再见', emoji: '👋', sentence: 'Goodbye!' },
    { word: 'bye', cn: '拜拜', emoji: '✋', sentence: 'Bye!' },
    { word: 'thanks', cn: '谢谢', emoji: '🙏', sentence: 'Thank you!' },
    { word: 'please', cn: '请', emoji: '🤲', sentence: 'Please help me.' },
    { word: 'sorry', cn: '对不起', emoji: '🥺', sentence: 'I am sorry.' },
    { word: 'good', cn: '好', emoji: '👍', sentence: 'I am good.' },
  ],
  交通工具: [
    { word: 'car', cn: '汽车', emoji: '🚗', sentence: 'I see a car.' },
    { word: 'bus', cn: '公交车', emoji: '🚌', sentence: 'I take the bus.' },
    { word: 'bike', cn: '自行车', emoji: '🚲', sentence: 'I ride a bike.' },
    { word: 'train', cn: '火车', emoji: '🚂', sentence: 'The train is long.' },
    { word: 'plane', cn: '飞机', emoji: '✈️', sentence: 'The plane can fly.' },
    { word: 'boat', cn: '小船', emoji: '⛵', sentence: 'The boat is small.' },
    { word: 'taxi', cn: '出租车', emoji: '🚕', sentence: 'I take a taxi.' },
    { word: 'rocket', cn: '火箭', emoji: '🚀', sentence: 'The rocket goes up.' },
  ],
  天气: [
    { word: 'sunny', cn: '晴朗', emoji: '🌞', sentence: 'It is sunny.' },
    { word: 'rainy', cn: '下雨', emoji: '🌧️', sentence: 'It is rainy.' },
    { word: 'cloudy', cn: '多云', emoji: '☁️', sentence: 'It is cloudy.' },
    { word: 'windy', cn: '刮风', emoji: '🌬️', sentence: 'It is windy.' },
    { word: 'snowy', cn: '下雪', emoji: '❄️', sentence: 'It is snowy.' },
    { word: 'hot', cn: '热', emoji: '🥵', sentence: 'It is hot.' },
    { word: 'cold', cn: '冷', emoji: '🥶', sentence: 'It is cold.' },
  ],
  玩具: [
    { word: 'ball', cn: '球', emoji: '⚽', sentence: 'I have a ball.' },
    { word: 'doll', cn: '娃娃', emoji: '🪆', sentence: 'I have a doll.' },
    { word: 'kite', cn: '风筝', emoji: '🪁', sentence: 'I fly a kite.' },
    { word: 'puzzle', cn: '拼图', emoji: '🧩', sentence: 'I do a puzzle.' },
    { word: 'block', cn: '积木', emoji: '🧱', sentence: 'I build with blocks.' },
    { word: 'teddy', cn: '泰迪熊', emoji: '🧸', sentence: 'I hug my teddy.' },
  ],
  场所: [
    { word: 'home', cn: '家', emoji: '🏠', sentence: 'I go home.' },
    { word: 'park', cn: '公园', emoji: '🏞️', sentence: 'I play in the park.' },
    { word: 'zoo', cn: '动物园', emoji: '🦁', sentence: 'I see animals at the zoo.' },
    { word: 'farm', cn: '农场', emoji: '🚜', sentence: 'The farm has cows.' },
    { word: 'hospital', cn: '医院', emoji: '🏥', sentence: 'We go to the hospital.' },
    { word: 'store', cn: '商店', emoji: '🏪', sentence: 'I buy food at the store.' },
    { word: 'library', cn: '图书馆', emoji: '📚', sentence: 'I read at the library.' },
  ],
  时间: [
    { word: 'morning', cn: '早上', emoji: '🌅', sentence: 'Good morning!' },
    { word: 'afternoon', cn: '下午', emoji: '🌇', sentence: 'Good afternoon!' },
    { word: 'evening', cn: '傍晚', emoji: '🌆', sentence: 'Good evening!' },
    { word: 'night', cn: '夜晚', emoji: '🌃', sentence: 'Good night!' },
    { word: 'today', cn: '今天', emoji: '📅', sentence: 'Today is fun.' },
  ],
};

/** 全部英语单词（用于听音选词、口语练习） */
export const ALL_EN_WORDS: WordItem[] = Object.values(EN_WORD_TOPICS).flat();
