// 自动生成：由 scripts 按「季/文件夹」拆分扫描 public/moko/collection/ 生成，请勿手改。
// 重新生成：node scripts/gen-moko-collection.js
import type { MokoChar, MokoCategoryKey } from '../types';

import { mokoCollection_01 } from './by-season/01';
import { mokoCollection_02 } from './by-season/02';
import { mokoCollection_03 } from './by-season/03';
import { mokoCollection_04 } from './by-season/04';
import { mokoCollection_05 } from './by-season/05';
import { mokoCollection_06 } from './by-season/06';
import { mokoCollection_07 } from './by-season/07';
import { mokoCollection_08 } from './by-season/08';
import { mokoCollection_09 } from './by-season/09';
import { mokoCollection_10 } from './by-season/10';

export interface MokoCollectionCat {
  key: MokoCategoryKey;
  label: string;
  emoji: string;
  color: string;
  desc: string;
}

/** 本次新增的季分类（需并入 MOko_CATEGORIES） */
export const COLLECTION_CATEGORIES: MokoCollectionCat[] = [
  {
    "key": "mo",
    "label": "魔方萌可",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "desc": "第一、二季的魔法萌可"
  },
  {
    "key": "prince",
    "label": "王子萌可",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "desc": "守护王国的王子们"
  },
  {
    "key": "villain",
    "label": "反派萌可",
    "emoji": "😈",
    "color": "text-slate-500",
    "desc": "搞怪的反派与神秘角色"
  },
  {
    "key": "legend",
    "label": "传奇萌可",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "desc": "传说中的特别萌可"
  }
];

/** 全部萌可图片（由 public/moko/collection 扫描生成，key 以 col_ 前缀，category 见上） */
export const mokoCollection: MokoChar[] = [
  ...mokoCollection_01,
  ...mokoCollection_02,
  ...mokoCollection_03,
  ...mokoCollection_04,
  ...mokoCollection_05,
  ...mokoCollection_06,
  ...mokoCollection_07,
  ...mokoCollection_08,
  ...mokoCollection_09,
  ...mokoCollection_10
];

/** 同名首图（用于把核心萌可的 img 重映射到真实图片） */
export const mokoCollectionByName: Record<string, MokoChar> = {
  "优雅萌可": {
    "key": "col_01_优雅萌可_render",
    "name": "优雅萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/优雅萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "优雅~ 我是优雅萌可，陪你一起认识字宝宝！"
  },
  "信信萌可": {
    "key": "col_01_信信萌可_render",
    "name": "信信萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/信信萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "信信~ 我是信信萌可，教你读诗词歌赋！"
  },
  "勇气萌可": {
    "key": "col_01_勇气萌可_render",
    "name": "勇气萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/勇气萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "哈哈，我是勇气萌可，冲呀！"
  },
  "唱唱萌可": {
    "key": "col_01_唱唱萌可_render",
    "name": "唱唱萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/唱唱萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啦啦~ 我是唱唱萌可，唱给世界听！"
  },
  "好好萌可": {
    "key": "col_01_好好萌可_render",
    "name": "好好萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/好好萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "好好~ 我是好好萌可，一起优雅地学习！"
  },
  "幸福萌可": {
    "key": "col_01_幸福萌可_render",
    "name": "幸福萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/幸福萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "幸福~ 我是幸福萌可，甜甜满满！"
  },
  "星光萌可": {
    "key": "col_01_星光萌可_render",
    "name": "星光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/星光萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "星星~ 我是星光萌可，闪亮登场！"
  },
  "月光萌可": {
    "key": "col_01_月光萌可_render",
    "name": "月光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/月光萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "月光~ 我是月光萌可，月光下数到一百！"
  },
  "正正萌可": {
    "key": "col_01_正正萌可_render",
    "name": "正正萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/正正萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "敬礼！我是正正萌可，无所畏惧！"
  },
  "漂亮萌可": {
    "key": "col_01_漂亮萌可_render",
    "name": "漂亮萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/漂亮萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "漂亮~ 我是漂亮萌可，陪你一起探索知识！"
  },
  "热情萌可": {
    "key": "col_01_热情萌可_render",
    "name": "热情萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/热情萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "华丽！我是热情萌可，热情满满来啦！"
  },
  "爱心萌可": {
    "key": "col_01_爱心萌可_render",
    "name": "爱心萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/爱心萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "啾~ 我是爱心萌可，爱心光波！"
  },
  "王子萌可": {
    "key": "col_01_王子萌可_render",
    "name": "王子萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/王子萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "我是王子萌可，我来守护大家！"
  },
  "盼盼萌可": {
    "key": "col_01_盼盼萌可_render",
    "name": "盼盼萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/盼盼萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "锵锵，我是盼盼萌可，希望满满！"
  },
  "笑笑萌可": {
    "key": "col_01_笑笑萌可_render",
    "name": "笑笑萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/笑笑萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "笑笑~ 我是笑笑萌可，教你做小公主！"
  },
  "绵绵萌可": {
    "key": "col_01_绵绵萌可_render",
    "name": "绵绵萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/绵绵萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "绵绵~ 我是绵绵萌可，软乎乎！"
  },
  "美丽萌可": {
    "key": "col_01_美丽萌可_render",
    "name": "美丽萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/美丽萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "美丽~ 我是美丽萌可，陪你一起变优雅！"
  },
  "诚实萌可": {
    "key": "col_01_诚实萌可_render",
    "name": "诚实萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/诚实萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "诚实~ 我是诚实萌可，一起学礼仪吧！"
  },
  "赞赞萌可": {
    "key": "col_01_赞赞萌可_render",
    "name": "赞赞萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/赞赞萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "赞赞~ 我是赞赞萌可，陪你一起长大！"
  },
  "软软萌可": {
    "key": "col_01_软软萌可_render",
    "name": "软软萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/软软萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "软软~ 我是软软萌可，弹弹果冻！"
  },
  "银光萌可": {
    "key": "col_01_银光萌可_render",
    "name": "银光萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/银光萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "耀耀~ 我是银光萌可，柔柔发光！"
  },
  "闪闪萌可": {
    "key": "col_01_闪闪萌可_render",
    "name": "闪闪萌可",
    "category": "royal",
    "season": "皇室萌可",
    "img": "/moko/collection/01_皇室萌可/闪闪萌可_render.webp",
    "emoji": "👑",
    "color": "text-moko-rose",
    "item": "✨ 魔法道具",
    "line": "闪闪~ 我是闪闪萌可，元气满满！"
  },
  "乖乖萌可": {
    "key": "col_02_乖乖萌可_render",
    "name": "乖乖萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/乖乖萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "乖乖~ 我是乖乖萌可，规矩最棒！"
  },
  "仿仿萌可": {
    "key": "col_02_仿仿萌可_render",
    "name": "仿仿萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/仿仿萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "仿仿~ 我是仿仿萌可，变身大师！"
  },
  "倒倒萌可": {
    "key": "col_02_倒倒萌可_render",
    "name": "倒倒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/倒倒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "倒倒~ 我是倒倒萌可，反着也行！"
  },
  "八卦萌可": {
    "key": "col_02_八卦萌可_render",
    "name": "八卦萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/八卦萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "八卦~ 我是八卦萌可，谜题通通破！"
  },
  "冰冰萌可": {
    "key": "col_02_冰冰萌可_render",
    "name": "冰冰萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/冰冰萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "冰冰~ 我是冰冰萌可，冷静实验家！"
  },
  "冷冷萌可": {
    "key": "col_02_冷冷萌可_render",
    "name": "冷冷萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/冷冷萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "冷冷~ 我是冷冷萌可，揭秘小能手！"
  },
  "厌厌萌可": {
    "key": "col_02_厌厌萌可_render",
    "name": "厌厌萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/厌厌萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "厌厌~ 我是厌厌萌可，变聪明秘诀！"
  },
  "变身萌可": {
    "key": "col_02_变身萌可_render",
    "name": "变身萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/变身萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "变身~ 我是变身萌可，魔法变变变！"
  },
  "叹气萌可": {
    "key": "col_02_叹气萌可_render",
    "name": "叹气萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/叹气萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "叹气~ 我是叹气萌可，小窍门大全！"
  },
  "否否萌可": {
    "key": "col_02_否否萌可_render",
    "name": "否否萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/否否萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "否否~ 我是否否萌可，想办法高手！"
  },
  "好奇萌可": {
    "key": "col_02_好奇萌可_render",
    "name": "好奇萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/好奇萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "好奇~ 我是好奇萌可，动脑筋探险！"
  },
  "妒妒萌可": {
    "key": "col_02_妒妒萌可_render",
    "name": "妒妒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/妒妒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "妒妒~ 我是妒妒萌可，探索不停歇！"
  },
  "妖妖萌可": {
    "key": "col_02_妖妖萌可_render",
    "name": "妖妖萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/妖妖萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "妖妖~ 我是妖妖萌可，手工达人秀！"
  },
  "娇娇萌可": {
    "key": "col_02_娇娇萌可_render",
    "name": "娇娇萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/娇娇萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "娇娇~ 我是娇娇萌可，搭积木小王！"
  },
  "孤独萌可": {
    "key": "col_02_孤独萌可_render",
    "name": "孤独萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/孤独萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "孤独~ 我是孤独萌可，科学小博士！"
  },
  "宝宝萌可": {
    "key": "col_02_宝宝萌可_render",
    "name": "宝宝萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/宝宝萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "宝宝~ 我是宝宝萌可，观察眼最亮！"
  },
  "害羞萌可": {
    "key": "col_02_害羞萌可_render",
    "name": "害羞萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/害羞萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "害羞~ 我是害羞萌可，游戏教给你！"
  },
  "幻幻萌可": {
    "key": "col_02_幻幻萌可_render",
    "name": "幻幻萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/幻幻萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "幻幻~ 我是幻幻萌可，猜谜语冠军！"
  },
  "怒怒萌可": {
    "key": "col_02_怒怒萌可_render",
    "name": "怒怒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/怒怒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "怒怒~ 我是怒怒萌可，逻辑最厉害！"
  },
  "怕怕萌可": {
    "key": "col_02_怕怕萌可_render",
    "name": "怕怕萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/怕怕萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "怕怕~ 我是怕怕萌可，思考小能手！"
  },
  "恋恋萌可": {
    "key": "col_02_恋恋萌可_render",
    "name": "恋恋萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/恋恋萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "恋恋~ 我是恋恋萌可，魔方玩得溜！"
  },
  "泪泪萌可": {
    "key": "col_02_泪泪萌可_render",
    "name": "泪泪萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/泪泪萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "泪泪~ 我是泪泪萌可，手工教给你！"
  },
  "淘气萌可": {
    "key": "col_02_淘气萌可_render",
    "name": "淘气萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/淘气萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "淘气~ 我是淘气萌可，捣蛋锤挥舞！"
  },
  "玩具萌可": {
    "key": "col_02_玩具萌可_render",
    "name": "玩具萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩具萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "玩具~ 我是玩具萌可，魔术变变变！"
  },
  "玩玩萌可": {
    "key": "col_02_玩玩萌可_render",
    "name": "玩玩萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩玩萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "玩玩~ 我是玩玩萌可，模型搭得高！"
  },
  "玩玩萌可·乐乐萌可": {
    "key": "col_02_玩玩萌可_乐乐萌可_render",
    "name": "玩玩萌可·乐乐萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩玩萌可_乐乐萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "飘飘！我是玩玩萌可·乐乐萌可，双倍快乐！"
  },
  "电电萌可": {
    "key": "col_02_电电萌可_render",
    "name": "电电萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/电电萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "电电~ 我是电电萌可，科学实验家！"
  },
  "画画萌可": {
    "key": "col_02_画画萌可_render",
    "name": "画画萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/画画萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "画画~ 我是画画萌可，编程小画家！"
  },
  "睡睡萌可": {
    "key": "col_02_睡睡萌可_render",
    "name": "睡睡萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/睡睡萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "睡睡~ 我是睡睡萌可，机器人梦工厂！"
  },
  "美美萌可": {
    "key": "col_02_美美萌可_render",
    "name": "美美萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/美美萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "美美~ 我是美美萌可，电子小达人！"
  },
  "聪明萌可": {
    "key": "col_02_聪明萌可_render",
    "name": "聪明萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/聪明萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "聪明~ 我是聪明萌可，电路设计师！"
  },
  "花花萌可": {
    "key": "col_02_花花萌可_render",
    "name": "花花萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/花花萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "花花~ 我是花花萌可，3D打印魔法！"
  },
  "贪贪萌可": {
    "key": "col_02_贪贪萌可_render",
    "name": "贪贪萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/贪贪萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "贪贪~ 我是贪贪萌可，木工小匠人！"
  },
  "赛赛萌可": {
    "key": "col_02_赛赛萌可_render",
    "name": "赛赛萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/赛赛萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "赛赛~ 我是赛赛萌可，绘画小天才！"
  },
  "迷糊萌可": {
    "key": "col_02_迷糊萌可_render",
    "name": "迷糊萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/迷糊萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "迷糊~ 我是迷糊萌可，币币去哪啦！"
  },
  "速速萌可": {
    "key": "col_02_速速萌可_render",
    "name": "速速萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/速速萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "速速~ 我是速速萌可，视频剪辑快！"
  },
  "重重萌可": {
    "key": "col_02_重重萌可_render",
    "name": "重重萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/重重萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "重重~ 我是重重萌可，动画制作家！"
  },
  "黏黏萌可": {
    "key": "col_02_黏黏萌可_render",
    "name": "黏黏萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/黏黏萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "黏黏~ 我是黏黏萌可，乐器拉得好！"
  },
  "公主萌可": {
    "key": "col_03_公主萌可_render",
    "name": "公主萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/公主萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "公主~ 我是公主萌可，今天也是小公主！"
  },
  "净净萌可": {
    "key": "col_03_净净萌可_render",
    "name": "净净萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/净净萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "净净~ 我是净净萌可，干净小标兵！"
  },
  "分享萌可": {
    "key": "col_03_分享萌可_render",
    "name": "分享萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/分享萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "分享~ 我是分享萌可，快乐分一半！"
  },
  "双双萌可": {
    "key": "col_03_双双萌可_render",
    "name": "双双萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/双双萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "双双~ 我是双双萌可，闪闪发光！"
  },
  "嘻嘻萌可": {
    "key": "col_03_嘻嘻萌可_render",
    "name": "嘻嘻萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/嘻嘻萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "嘻嘻~ 我是嘻嘻萌可，发现宝藏啦！"
  },
  "安慰萌可": {
    "key": "col_03_安慰萌可_render",
    "name": "安慰萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/安慰萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "安慰~ 我是安慰萌可，手工暖人心！"
  },
  "弱弱萌可": {
    "key": "col_03_弱弱萌可_render",
    "name": "弱弱萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/弱弱萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "晶晶！我是弱弱萌可，脆弱也闪亮！"
  },
  "愿望萌可": {
    "key": "col_03_愿望萌可_render",
    "name": "愿望萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/愿望萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "愿望~ 我是愿望萌可，画画圆梦想！"
  },
  "暖暖萌可": {
    "key": "col_03_暖暖萌可_render",
    "name": "暖暖萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/暖暖萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "暖暖~ 我是暖暖萌可，温暖传万家！"
  },
  "神奇萌可": {
    "key": "col_03_神奇萌可_render",
    "name": "神奇萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/神奇萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "神奇~ 我是神奇萌可，变漂亮魔法！"
  },
  "笔记萌可": {
    "key": "col_03_笔记萌可_render",
    "name": "笔记萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/笔记萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "笔记~ 我是笔记萌可，礼仪记心间！"
  },
  "美味萌可": {
    "key": "col_03_美味萌可_render",
    "name": "美味萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/美味萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "美味~ 我是美味萌可，跳舞最带劲！"
  },
  "芭蕾萌可": {
    "key": "col_03_芭蕾萌可_render",
    "name": "芭蕾萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/芭蕾萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "芭蕾~ 我是芭蕾萌可，唱歌跳舞俱佳！"
  },
  "躲躲萌可": {
    "key": "col_03_躲躲萌可_render",
    "name": "躲躲萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/躲躲萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "躲躲~ 我是躲躲萌可，开心躲不住！"
  },
  "雕刻萌可": {
    "key": "col_03_雕刻萌可_render",
    "name": "雕刻萌可",
    "category": "jewel",
    "season": "宝石萌可_第三季",
    "img": "/moko/collection/03_宝石萌可_第三季/雕刻萌可_render.webp",
    "emoji": "💎",
    "color": "text-moko-purple",
    "item": "✨ 魔法道具",
    "line": "璀璨！我是雕刻萌可，技艺震四方！"
  },
  "人鱼萌可": {
    "key": "col_04_人鱼萌可_render",
    "name": "人鱼萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/人鱼萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "人鱼~ 我是人鱼萌可，深海寻钥匙！"
  },
  "修理萌可": {
    "key": "col_04_修理萌可_render",
    "name": "修理萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/修理萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "修理~ 我是修理萌可，修好知识门！"
  },
  "加油萌可": {
    "key": "col_04_加油萌可_render",
    "name": "加油萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/加油萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "加油~ 我是加油萌可，解谜冲冲冲！"
  },
  "医生萌可": {
    "key": "col_04_医生萌可_render",
    "name": "医生萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/医生萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "医生~ 我是医生萌可，探险治愈者！"
  },
  "发明萌可": {
    "key": "col_04_发明萌可_render",
    "name": "发明萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/发明萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "发明~ 我是发明萌可，小发明大智慧！"
  },
  "吞吞萌可": {
    "key": "col_04_吞吞萌可_render",
    "name": "吞吞萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/吞吞萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "吞吞~ 我是吞吞萌可，锁好秘密基地！"
  },
  "快快萌可": {
    "key": "col_04_快快萌可_render",
    "name": "快快萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/快快萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "快快~ 我是快快萌可，速度学知识！"
  },
  "时尚萌可": {
    "key": "col_04_时尚萌可_render",
    "name": "时尚萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/时尚萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "时尚~ 我是时尚萌可，穿搭显智慧！"
  },
  "歌声萌可": {
    "key": "col_04_歌声萌可_render",
    "name": "歌声萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/歌声萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "歌声~ 我是歌声萌可，科学唱给你！"
  },
  "气气萌可": {
    "key": "col_04_气气萌可_render",
    "name": "气气萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/气气萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "气气~ 我是气气萌可，新大陆探险！"
  },
  "派对萌可": {
    "key": "col_04_派对萌可_render",
    "name": "派对萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/派对萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "派对~ 我是派对萌可，实验派对开！"
  },
  "滑冰萌可": {
    "key": "col_04_滑冰萌可_render",
    "name": "滑冰萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/滑冰萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "滑冰~ 我是滑冰萌可，动脑滑冰场！"
  },
  "灭火萌可": {
    "key": "col_04_灭火萌可_render",
    "name": "灭火萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/灭火萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "灭火~ 我是灭火萌可，知识火焰旺！"
  },
  "美发萌可": {
    "key": "col_04_美发萌可_render",
    "name": "美发萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/美发萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "美发~ 我是美发萌可，编程造型新！"
  },
  "警察萌可": {
    "key": "col_04_警察萌可_render",
    "name": "警察萌可",
    "category": "key",
    "season": "钥匙萌可_第四季",
    "img": "/moko/collection/04_钥匙萌可_第四季/警察萌可_render.webp",
    "emoji": "🔑",
    "color": "text-moko-violet",
    "item": "✨ 魔法道具",
    "line": "警察~ 我是警察萌可，机械秩序官！"
  },
  "冰沙萌可": {
    "key": "col_05_冰沙萌可_render",
    "name": "冰沙萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/冰沙萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "冰沙~ 我是冰沙萌可，清爽一夏天！"
  },
  "华夫萌可": {
    "key": "col_05_华夫萌可_render",
    "name": "华夫萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/华夫萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "华夫~ 我是华夫萌可，格子满甜蜜！"
  },
  "夹心萌可": {
    "key": "col_05_夹心萌可_render",
    "name": "夹心萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/夹心萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "夹心~ 我是夹心萌可，惊喜在中间！"
  },
  "奶油萌可": {
    "key": "col_05_奶油萌可_render",
    "name": "奶油萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/奶油萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "奶油~ 我是奶油萌可，烘焙云朵软！"
  },
  "巧克力萌可": {
    "key": "col_05_巧克力萌可_render",
    "name": "巧克力萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/巧克力萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "巧克力~ 我是巧克力萌可，苦中带甜最好吃！"
  },
  "布丁萌可": {
    "key": "col_05_布丁萌可_render",
    "name": "布丁萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/布丁萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "布丁~ 我是布丁萌可，摇摇甜心动！"
  },
  "松饼萌可": {
    "key": "col_05_松饼萌可_render",
    "name": "松饼萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/松饼萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "松饼~ 我是松饼萌可，松软甜蜜蜜！"
  },
  "棉花糖萌可": {
    "key": "col_05_棉花糖萌可_render",
    "name": "棉花糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/棉花糖萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "棉花糖~ 我是棉花糖萌可，软软甜甜营养！"
  },
  "棒棒糖萌可": {
    "key": "col_05_棒棒糖萌可_render",
    "name": "棒棒糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/棒棒糖萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "棒棒~ 我是棒棒糖萌可，点心甜滋滋！"
  },
  "泡泡萌可": {
    "key": "col_05_泡泡萌可_render",
    "name": "泡泡萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/泡泡萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "泡泡~ 我是泡泡萌可，糯糯圆又圆！"
  },
  "甜甜圈萌可": {
    "key": "col_05_甜甜圈萌可_render",
    "name": "甜甜圈萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/甜甜圈萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "甜圈~ 我是甜甜圈萌可，水果圈圈甜！"
  },
  "糖糖萌可": {
    "key": "col_05_糖糖萌可_render",
    "name": "糖糖萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/糖糖萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "糖糖~ 我是糖糖萌可，甜滋滋陪伴！"
  },
  "蛋糕妹妹萌可": {
    "key": "col_05_蛋糕妹妹萌可_render",
    "name": "蛋糕妹妹萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕妹妹萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "蛋糕~ 我是蛋糕妹妹萌可，快乐每一天！"
  },
  "蛋糕妹妹萌可·蛋糕弟弟萌可": {
    "key": "col_05_蛋糕妹妹萌可_蛋糕弟弟萌可_render",
    "name": "蛋糕妹妹萌可·蛋糕弟弟萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕妹妹萌可_蛋糕弟弟萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "双倍~ 我们是蛋糕兄妹，甜蜜加倍！"
  },
  "蛋糕弟弟萌可": {
    "key": "col_05_蛋糕弟弟萌可_render",
    "name": "蛋糕弟弟萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/蛋糕弟弟萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "蛋糕~ 我是蛋糕弟弟萌可，甜蜜跟你走！"
  },
  "酸奶萌可": {
    "key": "col_05_酸奶萌可_render",
    "name": "酸奶萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/酸奶萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "酸奶~ 我是酸奶萌可，饮品酸甜好！"
  },
  "马卡龙萌可": {
    "key": "col_05_马卡龙萌可_render",
    "name": "马卡龙萌可",
    "category": "sweetie",
    "season": "甜心萌可_第五季",
    "img": "/moko/collection/05_甜心萌可_第五季/马卡龙萌可_render.webp",
    "emoji": "🍬",
    "color": "text-moko-pink",
    "item": "✨ 魔法道具",
    "line": "马卡~ 我是马卡龙萌可，烹饪彩虹色！"
  },
  "乐美公主": {
    "key": "col_06_乐美萌可_render",
    "name": "乐美公主",
    "category": "guide",
    "season": "星星萌可_第六季",
    "img": "/moko/lemei.jpg",
    "emoji": "👑",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "一起捕捉萌可吧！"
  },
  "亲亲萌可": {
    "key": "col_06_亲亲萌可_render",
    "name": "亲亲萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/亲亲萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "亲亲~ 我是亲亲萌可，mua！"
  },
  "光明萌可": {
    "key": "col_06_光明萌可_render",
    "name": "光明萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/光明萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "光明~ 我是光明萌可，照亮你！"
  },
  "兔兔萌可": {
    "key": "col_06_兔兔萌可_render",
    "name": "兔兔萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/兔兔萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "跳跳~ 我是兔兔萌可，蹦蹦跳！"
  },
  "共共萌可": {
    "key": "col_06_共共萌可_render",
    "name": "共共萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/共共萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "共共~ 我是共共萌可，一起分享！"
  },
  "动动萌可": {
    "key": "col_06_动动萌可_render",
    "name": "动动萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/动动萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "动动~ 我是动动萌可，动起来！"
  },
  "叮咚萌可": {
    "key": "col_06_叮咚萌可_render",
    "name": "叮咚萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/叮咚萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "叮咚~ 我是叮咚萌可，门铃响啦！"
  },
  "呼啦萌可": {
    "key": "col_06_呼啦萌可_render",
    "name": "呼啦萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/呼啦萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼啦~ 我是呼啦萌可，转圈圈！"
  },
  "悄悄萌可": {
    "key": "col_06_悄悄萌可_render",
    "name": "悄悄萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/悄悄萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "悄悄~ 我是悄悄萌可，别出声～"
  },
  "歌谣萌可": {
    "key": "col_06_歌谣萌可_render",
    "name": "歌谣萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/歌谣萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "歌谣~ 我是歌谣萌可，唱起来！"
  },
  "流浪萌可": {
    "key": "col_06_流浪萌可_render",
    "name": "流浪萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/流浪萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "流浪~ 我是流浪萌可，看流星雨！"
  },
  "熊熊萌可": {
    "key": "col_06_熊熊萌可_render",
    "name": "熊熊萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/熊熊萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "熊熊~ 我是熊熊萌可，抱抱你！"
  },
  "狐狐萌可": {
    "key": "col_06_狐狐萌可_render",
    "name": "狐狐萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/狐狐萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "狐狐~ 我是狐狐萌可，狡黠一笑！"
  },
  "纷纷萌可": {
    "key": "col_06_纷纷萌可_render",
    "name": "纷纷萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/纷纷萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "纷纷~ 我是纷纷萌可，飘呀飘！"
  },
  "绵羊萌可": {
    "key": "col_06_绵羊萌可_render",
    "name": "绵羊萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/绵羊萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咩咩~ 我是绵羊萌可，软软的！"
  },
  "缤缤萌可": {
    "key": "col_06_缤缤萌可_render",
    "name": "缤缤萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/缤缤萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "缤缤~ 我是缤缤萌可，五彩缤纷！"
  },
  "缤缤萌可·纷纷萌可": {
    "key": "col_06_缤缤萌可_纷纷萌可_render",
    "name": "缤缤萌可·纷纷萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/缤缤萌可_纷纷萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "望望！我是缤缤萌可·纷纷萌可，双彩绽放！"
  },
  "贴贴萌可": {
    "key": "col_06_贴贴萌可_render",
    "name": "贴贴萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/贴贴萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "贴贴~ 我是贴贴萌可，贴贴你！"
  },
  "跳舞萌可": {
    "key": "col_06_跳舞萌可_render",
    "name": "跳舞萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/跳舞萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "跳舞~ 我是跳舞萌可，转个圈！"
  },
  "透明萌可": {
    "key": "col_06_透明萌可_render",
    "name": "透明萌可",
    "category": "star",
    "season": "星星萌可_第六季",
    "img": "/moko/collection/06_星星萌可_第六季/透明萌可_render.webp",
    "emoji": "☄️",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "透明~ 我是透明萌可，隐身大法！"
  },
  "丘比特萌可": {
    "key": "col_07_丘比特萌可_render",
    "name": "丘比特萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/丘比特萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "丘比特~ 我是丘比特萌可，爱之箭射心！"
  },
  "丝绸萌可": {
    "key": "col_07_丝绸萌可_render",
    "name": "丝绸萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/丝绸萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "丝绸~ 我是丝绸萌可，芭蕾舞轻盈！"
  },
  "困困萌可": {
    "key": "col_07_困困萌可_render",
    "name": "困困萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/困困萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "困困~ 我是困困萌可，睡醒更自信！"
  },
  "洗洗萌可": {
    "key": "col_07_洗洗萌可_render",
    "name": "洗洗萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/洗洗萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "洗洗~ 我是洗洗萌可，干净最漂亮！"
  },
  "猫猫萌可": {
    "key": "col_07_猫猫萌可_render",
    "name": "猫猫萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/猫猫萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "喵喵~ 我是猫猫萌可，优雅小猫咪！"
  },
  "玲珑萌可": {
    "key": "col_07_玲珑萌可_render",
    "name": "玲珑萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/玲珑萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "玲珑~ 我是玲珑萌可，心思剔透亮！"
  },
  "白雪萌可": {
    "key": "col_07_白雪萌可_render",
    "name": "白雪萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/白雪萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "白雪~ 我是白雪萌可，纯真如雪花！"
  },
  "蝴蝶萌可": {
    "key": "col_07_蝴蝶萌可_render",
    "name": "蝴蝶萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/蝴蝶萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "蝴蝶~ 我是蝴蝶萌可，破茧成蝶飞！"
  },
  "露水萌可": {
    "key": "col_07_露水萌可_render",
    "name": "露水萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/露水萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "露水~ 我是露水萌可，晨曦最晶莹！"
  },
  "鞋鞋萌可": {
    "key": "col_07_鞋鞋萌可_render",
    "name": "鞋鞋萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/鞋鞋萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "鞋鞋~ 我是鞋鞋萌可，舞鞋踏梦想！"
  },
  "魅力萌可": {
    "key": "col_07_魅力萌可_render",
    "name": "魅力萌可",
    "category": "princess",
    "season": "公主萌可_第七季",
    "img": "/moko/collection/07_公主萌可_第七季/魅力萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "魅力~ 我是魅力萌可，优雅迷人心！"
  },
  "查尔斯王子": {
    "key": "col_08_查尔斯萌可_render",
    "name": "查尔斯王子",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/查尔斯萌可_render.webp",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "查尔斯~ 我是查尔斯王子，绅士风度足！"
  },
  "演歌萌可": {
    "key": "col_08_演歌萌可_render",
    "name": "演歌萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/演歌萌可_render.webp",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "演歌~ 我是演歌萌可，歌声震四方！"
  },
  "绅士萌可": {
    "key": "col_08_绅士萌可_render",
    "name": "绅士萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/绅士萌可_render.webp",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "绅士~ 我是绅士萌可，礼仪守护者！"
  },
  "青蛙萌可": {
    "key": "col_08_青蛙萌可_render",
    "name": "青蛙萌可",
    "category": "prince",
    "season": "王子萌可",
    "img": "/moko/collection/08_王子萌可/青蛙萌可_render.webp",
    "emoji": "🤴",
    "color": "text-moko-blue",
    "item": "✨ 魔法道具",
    "line": "呱呱~ 我是青蛙萌可，王子也跳跃！"
  },
  "奉献萌可": {
    "key": "col_09_奉献萌可_render",
    "name": "奉献萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/奉献萌可_render.webp",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "奉献~ 我是奉献萌可，反派也有爱！"
  },
  "闹闹萌可": {
    "key": "col_09_闹闹萌可_render",
    "name": "闹闹萌可",
    "category": "villain",
    "season": "反派及其他",
    "img": "/moko/collection/09_反派及其他/闹闹萌可_render.webp",
    "emoji": "😈",
    "color": "text-slate-500",
    "item": "✨ 魔法道具",
    "line": "闹闹~ 我是闹闹萌可，恶作剧大王！"
  },
  "幸运萌可": {
    "key": "col_10_幸运萌可_render",
    "name": "幸运萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/幸运萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "幸运~ 我是幸运萌可，福星高照！"
  },
  "月神萌可": {
    "key": "col_10_月神萌可_render",
    "name": "月神萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/月神萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "月神~ 我是月神萌可，月华守护者！"
  },
  "月食萌可": {
    "key": "col_10_月食萌可_render",
    "name": "月食萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/月食萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "月食~ 我是月食萌可，神秘遮月光！"
  },
  "极光萌可": {
    "key": "col_10_极光萌可_render",
    "name": "极光萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/极光萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "极光~ 我是极光萌可，绚丽登场角度正！"
  },
  "甜甜萌可": {
    "key": "col_10_甜甜萌可_render",
    "name": "甜甜萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/甜甜萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "甜甜~ 我是甜甜萌可，甜度满分！"
  },
  "酸酸萌可": {
    "key": "col_10_酸酸萌可_render",
    "name": "酸酸萌可",
    "category": "legend",
    "season": "传奇萌可",
    "img": "/moko/collection/10_传奇萌可/酸酸萌可_render.webp",
    "emoji": "🌟",
    "color": "text-moko-gold",
    "item": "✨ 魔法道具",
    "line": "酸酸~ 我是酸酸萌可，酸中带甜心！"
  }
};

/** 图鉴可收集角色总数（去重后的唯一角色名，排除捣蛋萌可） */
export const COLLECTIBLE_MOKO_NAMES: string[] = [
  "优雅萌可",
  "信信萌可",
  "勇气萌可",
  "唱唱萌可",
  "好好萌可",
  "幸福萌可",
  "星光萌可",
  "月光萌可",
  "正正萌可",
  "漂亮萌可",
  "热情萌可",
  "爱心萌可",
  "王子萌可",
  "盼盼萌可",
  "笑笑萌可",
  "绵绵萌可",
  "美丽萌可",
  "诚实萌可",
  "赞赞萌可",
  "软软萌可",
  "银光萌可",
  "闪闪萌可",
  "乖乖萌可",
  "仿仿萌可",
  "倒倒萌可",
  "八卦萌可",
  "冰冰萌可",
  "冷冷萌可",
  "厌厌萌可",
  "变身萌可",
  "叹气萌可",
  "否否萌可",
  "好奇萌可",
  "妒妒萌可",
  "妖妖萌可",
  "娇娇萌可",
  "孤独萌可",
  "宝宝萌可",
  "害羞萌可",
  "幻幻萌可",
  "怒怒萌可",
  "怕怕萌可",
  "恋恋萌可",
  "泪泪萌可",
  "淘气萌可",
  "玩具萌可",
  "玩玩萌可",
  "玩玩萌可·乐乐萌可",
  "电电萌可",
  "画画萌可",
  "睡睡萌可",
  "美美萌可",
  "聪明萌可",
  "花花萌可",
  "贪贪萌可",
  "赛赛萌可",
  "迷糊萌可",
  "速速萌可",
  "重重萌可",
  "黏黏萌可",
  "公主萌可",
  "净净萌可",
  "分享萌可",
  "双双萌可",
  "嘻嘻萌可",
  "安慰萌可",
  "弱弱萌可",
  "愿望萌可",
  "暖暖萌可",
  "神奇萌可",
  "笔记萌可",
  "美味萌可",
  "芭蕾萌可",
  "躲躲萌可",
  "雕刻萌可",
  "人鱼萌可",
  "修理萌可",
  "加油萌可",
  "医生萌可",
  "发明萌可",
  "吞吞萌可",
  "快快萌可",
  "时尚萌可",
  "歌声萌可",
  "气气萌可",
  "派对萌可",
  "滑冰萌可",
  "灭火萌可",
  "美发萌可",
  "警察萌可",
  "冰沙萌可",
  "华夫萌可",
  "夹心萌可",
  "奶油萌可",
  "巧克力萌可",
  "布丁萌可",
  "松饼萌可",
  "棉花糖萌可",
  "棒棒糖萌可",
  "泡泡萌可",
  "甜甜圈萌可",
  "糖糖萌可",
  "蛋糕妹妹萌可",
  "蛋糕妹妹萌可·蛋糕弟弟萌可",
  "蛋糕弟弟萌可",
  "酸奶萌可",
  "马卡龙萌可",
  "乐美公主",
  "亲亲萌可",
  "光明萌可",
  "兔兔萌可",
  "共共萌可",
  "动动萌可",
  "叮咚萌可",
  "呼啦萌可",
  "悄悄萌可",
  "歌谣萌可",
  "流浪萌可",
  "熊熊萌可",
  "狐狐萌可",
  "纷纷萌可",
  "绵羊萌可",
  "缤缤萌可",
  "缤缤萌可·纷纷萌可",
  "贴贴萌可",
  "跳舞萌可",
  "透明萌可",
  "丘比特萌可",
  "丝绸萌可",
  "困困萌可",
  "洗洗萌可",
  "猫猫萌可",
  "玲珑萌可",
  "白雪萌可",
  "蝴蝶萌可",
  "露水萌可",
  "鞋鞋萌可",
  "魅力萌可",
  "查尔斯王子",
  "演歌萌可",
  "绅士萌可",
  "青蛙萌可",
  "奉献萌可",
  "闹闹萌可",
  "幸运萌可",
  "月神萌可",
  "月食萌可",
  "极光萌可",
  "甜甜萌可",
  "酸酸萌可"
];
