/**
 * 本文件由 study-data.ts 拆分而来（数据内容未改动，仅移动位置）。
 * 对外统一入口仍是 @/lib/study-data，见 src/lib/study-data.ts 的聚合 re-export。
 */

/* -------------------- 语文 · 识字（按类别） -------------------- */
export interface CharacterItem {
  char: string;
  pinyin: string; // 带声调拼音，识字卡 / 笔顺动画都靠它标音
  strokeCount: number;
  meaning: string;
  phrase: string;
  category: string;
  /** 多音字第二读音（可选），如 了 le/liǎo、着 zhe/zháo。识字卡会展示「又读 xxx」 */
  altPinyin?: string;
}

export const CHARACTER_CATEGORIES = ['数字', '自然', '人体', '家庭', '方位', '动作', '颜色', '动物', '植物', '物品'];

/** 明显的多音字第二读音（仅标一年级会遇到的常见多音字）。
 *  与 CHARACTERS 主读音拼接后派生到每项 altPinyin，避免改动 290 行数据块。 */
export const MULTI_READINGS: Record<string, string> = {
  了: 'liǎo', // le（来了）/ liǎo（了解）
  着: 'zháo', // zhe（笑着）/ zháo（着火）
  长: 'zhǎng', // cháng（长短）/ zhǎng（成长）
  地: 'de', // dì（天地）/ de（轻轻地）
  得: 'de', // dé（觉得）/ de（跑得快）
  还: 'huán', // hái（还有）/ huán（归还）
  只: 'zhǐ', // zhī（一只）/ zhǐ（只有）
  少: 'shào', // shǎo（多少）/ shào（少年）
  好: 'hào', // hǎo（好朋友）/ hào（爱好）
  中: 'zhòng', // zhōng（中国）/ zhòng（中奖）
  数: 'shǔ', // shù（数学）/ shǔ（数一数）
  空: 'kòng', // kōng（天空）/ kòng（空地）
  乐: 'yuè', // lè（快乐）/ yuè（音乐）
  发: 'fà', // fā（发芽）/ fà（头发）
  觉: 'jiào', // jué（觉得）/ jiào（睡觉）
};

const RAW_CHARACTERS: CharacterItem[] = [
  // 数字
  { char: '一', pinyin: 'yī', strokeCount: 1, meaning: '最小的数', phrase: '一个苹果', category: '数字' },
  { char: '二', pinyin: 'èr', strokeCount: 2, meaning: '比一多一个', phrase: '二只小鸟', category: '数字' },
  { char: '三', pinyin: 'sān', strokeCount: 3, meaning: '比二多一个', phrase: '三只兔子', category: '数字' },
  { char: '四', pinyin: 'sì', strokeCount: 5, meaning: '比三多一个', phrase: '四个气球', category: '数字' },
  { char: '五', pinyin: 'wǔ', strokeCount: 4, meaning: '比四多一个', phrase: '五颗星星', category: '数字' },
  { char: '六', pinyin: 'liù', strokeCount: 4, meaning: '比五多一个', phrase: '六个雪人', category: '数字' },
  { char: '七', pinyin: 'qī', strokeCount: 2, meaning: '比六多一个', phrase: '七朵花', category: '数字' },
  { char: '八', pinyin: 'bā', strokeCount: 2, meaning: '比七多一个', phrase: '八只狗', category: '数字' },
  { char: '九', pinyin: 'jiǔ', strokeCount: 2, meaning: '比八多一个', phrase: '九片叶子', category: '数字' },
  { char: '十', pinyin: 'shí', strokeCount: 2, meaning: '比九多一个，也指齐全', phrase: '十个小朋友', category: '数字' },
  // 自然
  { char: '天', pinyin: 'tiān', strokeCount: 4, meaning: '头顶上的高处；也指日子', phrase: '今天天气好', category: '自然' },
  { char: '地', pinyin: 'dì', strokeCount: 6, meaning: '大地', phrase: '大地是绿色的', category: '自然' },
  { char: '日', pinyin: 'rì', strokeCount: 4, meaning: '太阳 / 日子', phrase: '红日东升', category: '自然' },
  { char: '月', pinyin: 'yuè', strokeCount: 4, meaning: '月亮', phrase: '弯弯的月儿', category: '自然' },
  { char: '水', pinyin: 'shuǐ', strokeCount: 4, meaning: '水流', phrase: '清水哗哗流', category: '自然' },
  { char: '火', pinyin: 'huǒ', strokeCount: 4, meaning: '火焰', phrase: '红红火火', category: '自然' },
  { char: '山', pinyin: 'shān', strokeCount: 3, meaning: '高山', phrase: '大山高高', category: '自然' },
  { char: '石', pinyin: 'shí', strokeCount: 5, meaning: '石头', phrase: '一块石头', category: '自然' },
  { char: '田', pinyin: 'tián', strokeCount: 5, meaning: '田地', phrase: '种田真辛苦', category: '自然' },
  { char: '土', pinyin: 'tǔ', strokeCount: 3, meaning: '泥土', phrase: '泥土香喷喷', category: '自然' },
  // 人体
  { char: '人', pinyin: 'rén', strokeCount: 2, meaning: '人们', phrase: '大人小孩', category: '人体' },
  { char: '口', pinyin: 'kǒu', strokeCount: 3, meaning: '嘴巴', phrase: '嘴巴张开', category: '人体' },
  { char: '耳', pinyin: 'ěr', strokeCount: 6, meaning: '耳朵', phrase: '竖起耳朵', category: '人体' },
  { char: '目', pinyin: 'mù', strokeCount: 5, meaning: '眼睛', phrase: '目不转睛', category: '人体' },
  { char: '手', pinyin: 'shǒu', strokeCount: 4, meaning: '手掌', phrase: '小手真能干', category: '人体' },
  { char: '足', pinyin: 'zú', strokeCount: 7, meaning: '脚', phrase: '手足', category: '人体' },
  { char: '头', pinyin: 'tóu', strokeCount: 5, meaning: '脑袋', phrase: '洗头洗澡', category: '人体' },
  { char: '心', pinyin: 'xīn', strokeCount: 4, meaning: '心脏', phrase: '心情真好', category: '人体' },
  // 家庭
  { char: '父', pinyin: 'fù', strokeCount: 4, meaning: '爸爸', phrase: '父爱如山', category: '家庭' },
  { char: '母', pinyin: 'mǔ', strokeCount: 5, meaning: '妈妈', phrase: '母爱温暖', category: '家庭' },
  { char: '儿', pinyin: 'ér', strokeCount: 2, meaning: '小孩子', phrase: '儿童节快乐', category: '家庭' },
  { char: '女', pinyin: 'nǚ', strokeCount: 3, meaning: '女孩', phrase: '女孩子', category: '家庭' },
  { char: '子', pinyin: 'zǐ', strokeCount: 3, meaning: '小孩', phrase: '子儿满地跑', category: '家庭' },
  // 方位
  { char: '上', pinyin: 'shàng', strokeCount: 3, meaning: '上面', phrase: '天上飞', category: '方位' },
  { char: '下', pinyin: 'xià', strokeCount: 3, meaning: '下面', phrase: '树下坐', category: '方位' },
  { char: '左', pinyin: 'zuǒ', strokeCount: 5, meaning: '左边', phrase: '左手拿笔', category: '方位' },
  { char: '右', pinyin: 'yòu', strokeCount: 5, meaning: '右边', phrase: '右手举手', category: '方位' },
  { char: '中', pinyin: 'zhōng', strokeCount: 4, meaning: '中间', phrase: '水中月', category: '方位' },
  // 动作
  { char: '来', pinyin: 'lái', strokeCount: 7, meaning: '过来', phrase: '快来玩', category: '动作' },
  { char: '去', pinyin: 'qù', strokeCount: 5, meaning: '离开', phrase: '去上学', category: '动作' },
  { char: '坐', pinyin: 'zuò', strokeCount: 7, meaning: '坐下', phrase: '坐端正', category: '动作' },
  { char: '立', pinyin: 'lì', strokeCount: 5, meaning: '笔直地站着', phrase: '立正', category: '动作' },
  { char: '走', pinyin: 'zǒu', strokeCount: 7, meaning: '用脚一步一步往前移动', phrase: '走一走', category: '动作' },
  { char: '飞', pinyin: 'fēi', strokeCount: 3, meaning: '飞翔', phrase: '小鸟飞', category: '动作' },
  // 颜色
  { char: '红', pinyin: 'hóng', strokeCount: 6, meaning: '红色', phrase: '红花朵朵', category: '颜色' },
  { char: '白', pinyin: 'bái', strokeCount: 5, meaning: '白色', phrase: '白色', category: '颜色' },
  { char: '黑', pinyin: 'hēi', strokeCount: 12, meaning: '黑色', phrase: '黑夜来了', category: '颜色' },
  // 动物
  { char: '马', pinyin: 'mǎ', strokeCount: 3, meaning: '马儿', phrase: '小马快跑', category: '动物' },
  { char: '牛', pinyin: 'niú', strokeCount: 4, meaning: '一种家畜，能耕田，会「哞哞」叫', phrase: '老牛耕田', category: '动物' },
  { char: '羊', pinyin: 'yáng', strokeCount: 6, meaning: '一种家畜，身上有白毛，会「咩咩」叫', phrase: '小羊咩咩', category: '动物' },
  { char: '鸟', pinyin: 'niǎo', strokeCount: 5, meaning: '鸟儿', phrase: '小鸟唱歌', category: '动物' },
  { char: '鱼', pinyin: 'yú', strokeCount: 8, meaning: '鱼类', phrase: '小鱼游水', category: '动物' },
  { char: '虫', pinyin: 'chóng', strokeCount: 6, meaning: '虫子', phrase: '小虫爬爬', category: '动物' },
  // 植物
  { char: '花', pinyin: 'huā', strokeCount: 7, meaning: '花朵', phrase: '花儿香', category: '植物' },
  { char: '木', pinyin: 'mù', strokeCount: 4, meaning: '树木', phrase: '木头桌子', category: '植物' },
  { char: '草', pinyin: 'cǎo', strokeCount: 9, meaning: '青草', phrase: '小草绿', category: '植物' },
  { char: '叶', pinyin: 'yè', strokeCount: 5, meaning: '叶子', phrase: '树叶黄', category: '植物' },
  // 物品
  { char: '书', pinyin: 'shū', strokeCount: 4, meaning: '书本', phrase: '读书啦', category: '物品' },
  { char: '笔', pinyin: 'bǐ', strokeCount: 10, meaning: '用来写字、画画的工具', phrase: '铅笔写字', category: '物品' },
  { char: '刀', pinyin: 'dāo', strokeCount: 2, meaning: '小刀', phrase: '水果刀', category: '物品' },
  { char: '门', pinyin: 'mén', strokeCount: 3, meaning: '房子上的出入口，可以开关', phrase: '开门请进', category: '物品' },
  { char: '机', pinyin: 'jī', strokeCount: 6, meaning: '机器 / 飞机', phrase: '飞机飞得高', category: '物品' },
  { char: '球', pinyin: 'qiú', strokeCount: 11, meaning: '皮球 / 球类', phrase: '皮球圆又圆', category: '物品' },
  { char: '壳', pinyin: 'ké', strokeCount: 7, meaning: '外壳（贝壳/蛋壳）', phrase: '贝壳亮晶晶', category: '物品' },

  // —— 一年级上册 识字课文补充 ——
  { char: '你', pinyin: 'nǐ', strokeCount: 7, meaning: '称呼对方，就是跟我说话的那个人', phrase: '你们好', category: '家庭' },
  { char: '我', pinyin: 'wǒ', strokeCount: 7, meaning: '说话的人自己', phrase: '我们', category: '家庭' },
  { char: '他', pinyin: 'tā', strokeCount: 5, meaning: '说到的另一个人', phrase: '他们', category: '家庭' },
  { char: '金', pinyin: 'jīn', strokeCount: 8, meaning: '金子 / 金属', phrase: '金子闪闪', category: '自然' },
  { char: '川', pinyin: 'chuān', strokeCount: 3, meaning: '河流 / 山川', phrase: '山川壮美', category: '自然' },
  { char: '禾', pinyin: 'hé', strokeCount: 5, meaning: '禾苗（庄稼）', phrase: '禾苗青青', category: '植物' },
  { char: '站', pinyin: 'zhàn', strokeCount: 10, meaning: '立着不动；也指等车的地方', phrase: '站如松', category: '动作' },
  { char: '云', pinyin: 'yún', strokeCount: 4, meaning: '云朵', phrase: '云朵', category: '自然' },
  { char: '雨', pinyin: 'yǔ', strokeCount: 8, meaning: '雨水', phrase: '下雨啦', category: '自然' },
  { char: '风', pinyin: 'fēng', strokeCount: 4, meaning: '空气流动形成的，能吹动树叶', phrase: '大风呼呼', category: '自然' },
  { char: '明', pinyin: 'míng', strokeCount: 8, meaning: '明亮 / 明白', phrase: '明亮灯光', category: '自然' },
  { char: '男', pinyin: 'nán', strokeCount: 7, meaning: '男孩 / 男人', phrase: '男孩勇敢', category: '家庭' },
  { char: '尖', pinyin: 'jiān', strokeCount: 6, meaning: '尖锐 / 笔尖', phrase: '笔尖尖尖', category: '物品' },
  { char: '尘', pinyin: 'chén', strokeCount: 6, meaning: '尘土', phrase: '尘土飞扬', category: '自然' },
  { char: '从', pinyin: 'cóng', strokeCount: 4, meaning: '跟从', phrase: '跟从老师', category: '家庭' },
  { char: '众', pinyin: 'zhòng', strokeCount: 6, meaning: '众人 / 许多', phrase: '众人拾柴', category: '家庭' },
  { char: '林', pinyin: 'lín', strokeCount: 8, meaning: '树林', phrase: '树林密密', category: '植物' },
  { char: '森', pinyin: 'sēn', strokeCount: 12, meaning: '森林', phrase: '森林深深', category: '植物' },
  { char: '包', pinyin: 'bāo', strokeCount: 5, meaning: '书包 / 包裹', phrase: '书包真神气', category: '物品' },
  { char: '尺', pinyin: 'chǐ', strokeCount: 4, meaning: '尺子', phrase: '一把尺子', category: '物品' },
  { char: '作', pinyin: 'zuò', strokeCount: 7, meaning: '作业 / 工作', phrase: '做作业', category: '物品' },
  { char: '业', pinyin: 'yè', strokeCount: 5, meaning: '作业 / 事业', phrase: '完成作业', category: '物品' },
  { char: '本', pinyin: 'běn', strokeCount: 5, meaning: '本子 / 书本', phrase: '一本本子', category: '物品' },
  { char: '课', pinyin: 'kè', strokeCount: 10, meaning: '上课 / 课程', phrase: '上课啦', category: '物品' },
  { char: '早', pinyin: 'zǎo', strokeCount: 6, meaning: '早晨 / 早', phrase: '早上好', category: '自然' },
  { char: '校', pinyin: 'xiào', strokeCount: 10, meaning: '学校', phrase: '学校真漂亮', category: '物品' },
  { char: '升', pinyin: 'shēng', strokeCount: 4, meaning: '升起', phrase: '升旗', category: '动作' },
  { char: '国', pinyin: 'guó', strokeCount: 8, meaning: '国家 / 中国', phrase: '我爱中国', category: '家庭' },
  { char: '旗', pinyin: 'qí', strokeCount: 14, meaning: '旗帜', phrase: '五星红旗', category: '物品' },
  { char: '起', pinyin: 'qǐ', strokeCount: 10, meaning: '起来 / 起立', phrase: '起立', category: '动作' },
  { char: '美', pinyin: 'měi', strokeCount: 9, meaning: '好看、漂亮', phrase: '美丽中国', category: '自然' },
  { char: '丽', pinyin: 'lì', strokeCount: 7, meaning: '好看；常和「美」一起用', phrase: '风和日丽', category: '自然' },
  { char: '歌', pinyin: 'gē', strokeCount: 14, meaning: '歌曲 / 唱歌', phrase: '唱歌', category: '动作' },
  { char: '午', pinyin: 'wǔ', strokeCount: 4, meaning: '中午 / 下午', phrase: '中午吃饭', category: '自然' },
  { char: '晚', pinyin: 'wǎn', strokeCount: 11, meaning: '晚上', phrase: '晚上好', category: '自然' },
  { char: '昨', pinyin: 'zuó', strokeCount: 9, meaning: '昨天', phrase: '昨天的事', category: '自然' },
  { char: '今', pinyin: 'jīn', strokeCount: 4, meaning: '今天', phrase: '今天开心', category: '自然' },
  { char: '年', pinyin: 'nián', strokeCount: 6, meaning: '十二个月就是一轮春夏秋冬', phrase: '过新年', category: '自然' },
  { char: '开', pinyin: 'kāi', strokeCount: 4, meaning: '打开 / 开心', phrase: '开门', category: '动作' },
  { char: '关', pinyin: 'guān', strokeCount: 6, meaning: '关上', phrase: '关上门', category: '动作' },
  { char: '牙', pinyin: 'yá', strokeCount: 4, meaning: '牙齿', phrase: '刷牙', category: '人体' },
  { char: '少', pinyin: 'shǎo', strokeCount: 4, meaning: '多少 / 少', phrase: '多少', category: '数字' },
  { char: '不', pinyin: 'bù', strokeCount: 4, meaning: '没有，或者拒绝', phrase: '不行', category: '动作' },

  // —— 一年级上册生字表补全（课本各单元会认字，按单元出现顺序补充） ——
  { char: '学', pinyin: 'xué', strokeCount: 8, meaning: '学习', phrase: '学校', category: '动作' },
  { char: '了', pinyin: 'le', strokeCount: 2, meaning: '表示事情已经做完', phrase: '来了', category: '动作' },
  { char: '爱', pinyin: 'ài', strokeCount: 10, meaning: '喜爱', phrase: '爱心', category: '家庭' },
  { char: '们', pinyin: 'men', strokeCount: 5, meaning: '表示复数', phrase: '我们', category: '家庭' },
  { char: '对', pinyin: 'duì', strokeCount: 5, meaning: '正确 / 答对', phrase: '对了', category: '动作' },
  { char: '爸', pinyin: 'bà', strokeCount: 8, meaning: '爸爸', phrase: '爸爸', category: '家庭' },
  { char: '妈', pinyin: 'mā', strokeCount: 6, meaning: '妈妈', phrase: '妈妈', category: '家庭' },
  { char: '画', pinyin: 'huà', strokeCount: 8, meaning: '画画', phrase: '画图', category: '动作' },
  { char: '打', pinyin: 'dǎ', strokeCount: 5, meaning: '拍打 / 打球', phrase: '打球', category: '动作' },
  { char: '棋', pinyin: 'qí', strokeCount: 12, meaning: '棋子 / 下棋', phrase: '下棋', category: '物品' },
  { char: '鸡', pinyin: 'jī', strokeCount: 7, meaning: '小鸡', phrase: '公鸡', category: '动物' },
  { char: '字', pinyin: 'zì', strokeCount: 6, meaning: '汉字', phrase: '写字', category: '物品' },
  { char: '词', pinyin: 'cí', strokeCount: 7, meaning: '词语', phrase: '字词', category: '物品' },
  { char: '语', pinyin: 'yǔ', strokeCount: 9, meaning: '语言', phrase: '语文', category: '物品' },
  { char: '句', pinyin: 'jù', strokeCount: 5, meaning: '句子', phrase: '一句话', category: '物品' },
  { char: '桌', pinyin: 'zhuō', strokeCount: 10, meaning: '桌子', phrase: '书桌', category: '物品' },
  { char: '纸', pinyin: 'zhǐ', strokeCount: 7, meaning: '纸张', phrase: '白纸', category: '物品' },
  { char: '文', pinyin: 'wén', strokeCount: 4, meaning: '文字 / 语文', phrase: '文化', category: '物品' },
  { char: '数', pinyin: 'shù', strokeCount: 13, meaning: '数学 / 数字', phrase: '数数', category: '物品' },
  { char: '音', pinyin: 'yīn', strokeCount: 9, meaning: '听到的声响；也指乐曲', phrase: '音乐', category: '物品' },
  { char: '乐', pinyin: 'lè', strokeCount: 5, meaning: '快乐 / 音乐', phrase: '欢乐', category: '动作' },
  { char: '妹', pinyin: 'mèi', strokeCount: 8, meaning: '妹妹', phrase: '妹妹', category: '家庭' },
  { char: '奶', pinyin: 'nǎi', strokeCount: 5, meaning: '奶奶', phrase: '奶奶', category: '家庭' },
  { char: '皮', pinyin: 'pí', strokeCount: 5, meaning: '人或动物身体外面的一层', phrase: '皮球', category: '人体' },
  { char: '桥', pinyin: 'qiáo', strokeCount: 10, meaning: '小桥', phrase: '木桥', category: '物品' },
  { char: '台', pinyin: 'tái', strokeCount: 5, meaning: '台子 / 台子', phrase: '台上', category: '物品' },
  { char: '雪', pinyin: 'xuě', strokeCount: 11, meaning: '雪花', phrase: '雪人', category: '自然' },
  { char: '家', pinyin: 'jiā', strokeCount: 10, meaning: '家庭', phrase: '大家', category: '家庭' },
  { char: '是', pinyin: 'shì', strokeCount: 9, meaning: '用在两样东西之间，说它们一样', phrase: '也是', category: '动作' },
  { char: '车', pinyin: 'chē', strokeCount: 4, meaning: '车子', phrase: '马车', category: '物品' },
  { char: '也', pinyin: 'yě', strokeCount: 3, meaning: '表示同样、一样', phrase: '也是', category: '动作' },
  { char: '秋', pinyin: 'qiū', strokeCount: 9, meaning: '秋天', phrase: '秋天', category: '自然' },
  { char: '气', pinyin: 'qì', strokeCount: 4, meaning: '空气 / 天气', phrase: '生气', category: '自然' },
  { char: '树', pinyin: 'shù', strokeCount: 9, meaning: '大树', phrase: '树叶', category: '植物' },
  { char: '片', pinyin: 'piàn', strokeCount: 4, meaning: '一片', phrase: '卡片', category: '物品' },
  { char: '大', pinyin: 'dà', strokeCount: 3, meaning: '大小', phrase: '大人', category: '方位' },
  { char: '会', pinyin: 'huì', strokeCount: 6, meaning: '能做某件事', phrase: '学会', category: '动作' },
  { char: '个', pinyin: 'gè', strokeCount: 3, meaning: '数东西时用的词，放在数字后面', phrase: '一个', category: '物品' },
  { char: '的', pinyin: 'de', strokeCount: 8, meaning: '两个词中间那个小帮手，说明东西归谁', phrase: '我的书', category: '动作' },
  { char: '船', pinyin: 'chuán', strokeCount: 11, meaning: '小船', phrase: '飞船', category: '物品' },
  { char: '两', pinyin: 'liǎng', strokeCount: 7, meaning: '两个', phrase: '两天', category: '数字' },
  { char: '在', pinyin: 'zài', strokeCount: 6, meaning: '说明位置，或指事情正发生着', phrase: '在家', category: '方位' },
  { char: '里', pinyin: 'lǐ', strokeCount: 7, meaning: '里面', phrase: '家里', category: '方位' },
  { char: '看', pinyin: 'kàn', strokeCount: 9, meaning: '用眼睛去瞧', phrase: '看书', category: '动作' },
  { char: '见', pinyin: 'jiàn', strokeCount: 4, meaning: '看到、碰面', phrase: '见面', category: '动作' },
  { char: '闪', pinyin: 'shǎn', strokeCount: 5, meaning: '闪亮', phrase: '闪电', category: '自然' },
  { char: '星', pinyin: 'xīng', strokeCount: 9, meaning: '星星', phrase: '星空', category: '自然' },
  { char: '江', pinyin: 'jiāng', strokeCount: 6, meaning: '长江', phrase: '江南', category: '自然' },
  { char: '南', pinyin: 'nán', strokeCount: 9, meaning: '南方', phrase: '江南', category: '方位' },
  { char: '可', pinyin: 'kě', strokeCount: 5, meaning: '可以', phrase: '可爱', category: '动作' },
  { char: '采', pinyin: 'cǎi', strokeCount: 8, meaning: '用手把花果摘下来', phrase: '采花', category: '动作' },
  { char: '莲', pinyin: 'lián', strokeCount: 10, meaning: '莲花', phrase: '莲叶', category: '植物' },
  { char: '东', pinyin: 'dōng', strokeCount: 5, meaning: '东边', phrase: '东西', category: '方位' },
  { char: '西', pinyin: 'xī', strokeCount: 6, meaning: '西边', phrase: '东西', category: '方位' },
  { char: '北', pinyin: 'běi', strokeCount: 5, meaning: '北方', phrase: '北方', category: '方位' },
  { char: '说', pinyin: 'shuō', strokeCount: 9, meaning: '说话', phrase: '说话', category: '动作' },
  { char: '春', pinyin: 'chūn', strokeCount: 9, meaning: '春天', phrase: '春风', category: '自然' },
  { char: '青', pinyin: 'qīng', strokeCount: 8, meaning: '青色', phrase: '青草', category: '颜色' },
  { char: '蛙', pinyin: 'wā', strokeCount: 12, meaning: '青蛙', phrase: '牛蛙', category: '动物' },
  { char: '夏', pinyin: 'xià', strokeCount: 10, meaning: '夏天', phrase: '夏夜', category: '自然' },
  { char: '弯', pinyin: 'wān', strokeCount: 9, meaning: '弯弯', phrase: '弯路', category: '动作' },
  { char: '就', pinyin: 'jiù', strokeCount: 12, meaning: '马上、立刻', phrase: '就是', category: '动作' },
  { char: '冬', pinyin: 'dōng', strokeCount: 5, meaning: '冬天', phrase: '过冬', category: '自然' },
  { char: '远', pinyin: 'yuǎn', strokeCount: 7, meaning: '距离大', phrase: '远方', category: '方位' },
  { char: '色', pinyin: 'sè', strokeCount: 6, meaning: '颜色', phrase: '色彩', category: '颜色' },
  { char: '近', pinyin: 'jìn', strokeCount: 7, meaning: '距离小', phrase: '靠近', category: '方位' },
  { char: '听', pinyin: 'tīng', strokeCount: 7, meaning: '用耳朵接收声音', phrase: '听见', category: '动作' },
  { char: '无', pinyin: 'wú', strokeCount: 4, meaning: '没有、不存在', phrase: '无力', category: '数字' },
  { char: '声', pinyin: 'shēng', strokeCount: 7, meaning: '听到的动静', phrase: '笑声', category: '自然' },
  { char: '还', pinyin: 'hái', strokeCount: 7, meaning: '仍然、仍旧', phrase: '还是', category: '动作' },
  { char: '多', pinyin: 'duō', strokeCount: 6, meaning: '多少', phrase: '很多', category: '数字' },
  { char: '黄', pinyin: 'huáng', strokeCount: 11, meaning: '黄色', phrase: '金黄', category: '颜色' },
  { char: '只', pinyin: 'zhī', strokeCount: 5, meaning: '数动物或某些东西的量词', phrase: '一只猫', category: '数字' },
  { char: '猫', pinyin: 'māo', strokeCount: 11, meaning: '小猫', phrase: '花猫', category: '动物' },
  { char: '边', pinyin: 'biān', strokeCount: 5, meaning: '旁边', phrase: '河边', category: '方位' },
  { char: '鸭', pinyin: 'yā', strokeCount: 10, meaning: '鸭子', phrase: '小鸭', category: '动物' },
  { char: '苹', pinyin: 'píng', strokeCount: 8, meaning: '苹果', phrase: '苹果', category: '植物' },
  { char: '果', pinyin: 'guǒ', strokeCount: 8, meaning: '水果', phrase: '果实', category: '植物' },
  { char: '杏', pinyin: 'xìng', strokeCount: 7, meaning: '杏子', phrase: '杏树', category: '植物' },
  { char: '桃', pinyin: 'táo', strokeCount: 10, meaning: '桃子', phrase: '桃树', category: '植物' },
  { char: '力', pinyin: 'lì', strokeCount: 2, meaning: '力气', phrase: '大力', category: '动作' },
  { char: '双', pinyin: 'shuāng', strokeCount: 4, meaning: '一双', phrase: '双手', category: '数字' },
  { char: '条', pinyin: 'tiáo', strokeCount: 7, meaning: '一条', phrase: '纸条', category: '数字' },
  { char: '么', pinyin: 'me', strokeCount: 3, meaning: '轻声字，用在疑问词后面', phrase: '怎么', category: '动作' },
  { char: '影', pinyin: 'yǐng', strokeCount: 15, meaning: '影子', phrase: '影子', category: '自然' },
  { char: '前', pinyin: 'qián', strokeCount: 9, meaning: '前面', phrase: '前后', category: '方位' },
  { char: '后', pinyin: 'hòu', strokeCount: 6, meaning: '后面', phrase: '以后', category: '方位' },
  { char: '狗', pinyin: 'gǒu', strokeCount: 8, meaning: '小狗', phrase: '黑狗', category: '动物' },
  { char: '它', pinyin: 'tā', strokeCount: 5, meaning: '说到的动物或东西', phrase: '它们', category: '动物' },
  { char: '好', pinyin: 'hǎo', strokeCount: 6, meaning: '优点多、让人满意', phrase: '好朋友', category: '家庭' },
  { char: '朋', pinyin: 'péng', strokeCount: 8, meaning: '伙伴、要好的伴', phrase: '亲朋', category: '家庭' },
  { char: '友', pinyin: 'yǒu', strokeCount: 4, meaning: '要好的人；也指关系亲近', phrase: '好友', category: '家庭' },
  { char: '尾', pinyin: 'wěi', strokeCount: 7, meaning: '动物身子后面那一条；也指最后', phrase: '尾羽', category: '动物' },
  { char: '巴', pinyin: 'bā', strokeCount: 4, meaning: '盼望；也指紧紧地贴', phrase: '尾巴', category: '动物' },
  { char: '谁', pinyin: 'shuí', strokeCount: 10, meaning: '问人的疑问词', phrase: '谁知', category: '动作' },
  { char: '长', pinyin: 'cháng', strokeCount: 4, meaning: '长短', phrase: '长高', category: '方位' },
  { char: '短', pinyin: 'duǎn', strokeCount: 12, meaning: '长度小', phrase: '短发', category: '方位' },
  { char: '把', pinyin: 'bǎ', strokeCount: 7, meaning: '一把', phrase: '把门', category: '动作' },
  { char: '伞', pinyin: 'sǎn', strokeCount: 6, meaning: '雨伞', phrase: '打伞', category: '物品' },
  { char: '兔', pinyin: 'tù', strokeCount: 8, meaning: '兔子', phrase: '白兔', category: '动物' },
  { char: '最', pinyin: 'zuì', strokeCount: 12, meaning: '表示程度排第一', phrase: '最好', category: '动作' },
  { char: '公', pinyin: 'gōng', strokeCount: 4, meaning: '公鸡', phrase: '公鸡', category: '动物' },
  { char: '写', pinyin: 'xiě', strokeCount: 5, meaning: '用笔在纸上留下字', phrase: '写字', category: '动作' },
  { char: '诗', pinyin: 'shī', strokeCount: 8, meaning: '诗歌', phrase: '写诗', category: '物品' },
  { char: '点', pinyin: 'diǎn', strokeCount: 9, meaning: '一点', phrase: '点头', category: '数字' },
  { char: '要', pinyin: 'yào', strokeCount: 9, meaning: '表示希望得到或必须', phrase: '不要', category: '动作' },
  { char: '过', pinyin: 'guò', strokeCount: 6, meaning: '从一个地方到另一个地方', phrase: '过来', category: '动作' },
  { char: '给', pinyin: 'gěi', strokeCount: 9, meaning: '把东西交到别人手里', phrase: '送给', category: '动作' },
  { char: '当', pinyin: 'dāng', strokeCount: 6, meaning: '担任；也表示正在那时', phrase: '当然', category: '动作' },
  { char: '串', pinyin: 'chuàn', strokeCount: 7, meaning: '一串', phrase: '串门', category: '数字' },
  { char: '以', pinyin: 'yǐ', strokeCount: 4, meaning: '以后', phrase: '以前', category: '动作' },
  { char: '成', pinyin: 'chéng', strokeCount: 6, meaning: '做完了、做好了', phrase: '成功', category: '动作' },
  { char: '彩', pinyin: 'cǎi', strokeCount: 11, meaning: '彩色', phrase: '彩虹', category: '颜色' },
  { char: '半', pinyin: 'bàn', strokeCount: 5, meaning: '一半', phrase: '半个', category: '数字' },
  { char: '空', pinyin: 'kōng', strokeCount: 8, meaning: '里面没有东西；也指天上', phrase: '天空', category: '自然' },
  { char: '问', pinyin: 'wèn', strokeCount: 6, meaning: '向别人请教、打听', phrase: '提问', category: '动作' },
  { char: '到', pinyin: 'dào', strokeCount: 8, meaning: '从别处来，走进某个地方', phrase: '到了', category: '动作' },
  { char: '方', pinyin: 'fāng', strokeCount: 4, meaning: '方向', phrase: '地方', category: '方位' },
  { char: '没', pinyin: 'méi', strokeCount: 7, meaning: '表示不存在；也读 mò，沉下去', phrase: '没空', category: '数字' },
  { char: '更', pinyin: 'gèng', strokeCount: 7, meaning: '表示程度又高一些', phrase: '更好', category: '动作' },
  { char: '绿', pinyin: 'lǜ', strokeCount: 11, meaning: '绿色', phrase: '绿叶', category: '颜色' },
  { char: '出', pinyin: 'chū', strokeCount: 5, meaning: '从里面到外面', phrase: '出来', category: '动作' },
  { char: '睡', pinyin: 'shuì', strokeCount: 13, meaning: '睡觉', phrase: '入睡', category: '动作' },
  { char: '那', pinyin: 'nà', strokeCount: 6, meaning: '指较远的人或事', phrase: '那里', category: '方位' },
  { char: '海', pinyin: 'hǎi', strokeCount: 10, meaning: '大海', phrase: '海边', category: '自然' },
  { char: '真', pinyin: 'zhēn', strokeCount: 10, meaning: '确实、一点都不假', phrase: '真心', category: '动作' },
  { char: '老', pinyin: 'lǎo', strokeCount: 6, meaning: '年纪大；也指经常', phrase: '老师', category: '家庭' },
  { char: '师', pinyin: 'shī', strokeCount: 6, meaning: '老师', phrase: '师徒', category: '家庭' },
  { char: '吗', pinyin: 'ma', strokeCount: 6, meaning: '放在句子最后表示疑问', phrase: '好吗', category: '动作' },
  { char: '同', pinyin: 'tóng', strokeCount: 6, meaning: '一样、一起', phrase: '同心', category: '家庭' },
  { char: '什', pinyin: 'shén', strokeCount: 4, meaning: '读 shén 时用在疑问词里；读 shí 时如多种的', phrase: '干什么', category: '动作' },
  { char: '才', pinyin: 'cái', strokeCount: 3, meaning: '刚发生不久；也表示只有', phrase: '刚才', category: '动作' },
  { char: '亮', pinyin: 'liàng', strokeCount: 9, meaning: '有光，不暗', phrase: '月亮', category: '自然' },
  { char: '时', pinyin: 'shí', strokeCount: 7, meaning: '时间', phrase: '时候', category: '自然' },
  { char: '候', pinyin: 'hòu', strokeCount: 10, meaning: '时候', phrase: '气候', category: '自然' },
  { char: '觉', pinyin: 'jué', strokeCount: 9, meaning: '感受到；也读 jiào，指睡眠', phrase: '睡觉', category: '动作' },
  { char: '得', pinyin: 'dé', strokeCount: 11, meaning: '拿到、到手', phrase: '得到', category: '动作' },
  { char: '自', pinyin: 'zì', strokeCount: 6, meaning: '指说话人本身', phrase: '自由', category: '家庭' },
  { char: '己', pinyin: 'jǐ', strokeCount: 3, meaning: '指自身；常和「自」一起用', phrase: '知己', category: '家庭' },
  { char: '很', pinyin: 'hěn', strokeCount: 9, meaning: '表示程度高', phrase: '很好', category: '动作' },
  { char: '穿', pinyin: 'chuān', strokeCount: 9, meaning: '把衣服套在身上', phrase: '穿衣', category: '动作' },
  { char: '衣', pinyin: 'yī', strokeCount: 6, meaning: '穿在身上的东西', phrase: '大衣', category: '物品' },
  { char: '服', pinyin: 'fú', strokeCount: 8, meaning: '穿的东西；也指听从', phrase: '衣服', category: '物品' },
  { char: '快', pinyin: 'kuài', strokeCount: 7, meaning: '速度高', phrase: '飞快', category: '动作' },
  { char: '蓝', pinyin: 'lán', strokeCount: 13, meaning: '蓝色', phrase: '蓝天', category: '颜色' },
  { char: '又', pinyin: 'yòu', strokeCount: 2, meaning: '再一次', phrase: '又快', category: '动作' },
  { char: '笑', pinyin: 'xiào', strokeCount: 10, meaning: '高兴时脸上的表情和声音', phrase: '笑脸', category: '动作' },
  { char: '着', pinyin: 'zhe', strokeCount: 11, meaning: '放在动作后面，说这事还没停', phrase: '看着', category: '动作' },
  { char: '向', pinyin: 'xiàng', strokeCount: 6, meaning: '朝着某个目标或方位', phrase: '向前', category: '方位' },
  { char: '和', pinyin: 'hé', strokeCount: 8, meaning: '跟、与；也表示不吵架', phrase: '和气', category: '动作' },
  { char: '贝', pinyin: 'bèi', strokeCount: 4, meaning: '贝壳', phrase: '宝贝', category: '物品' },
  { char: '娃', pinyin: 'wá', strokeCount: 9, meaning: '娃娃', phrase: '女娃', category: '家庭' },
  { char: '挂', pinyin: 'guà', strokeCount: 9, meaning: '把东西吊在高处', phrase: '挂上', category: '动作' },
  { char: '活', pinyin: 'huó', strokeCount: 9, meaning: '有生命；也指做事情', phrase: '生活', category: '动作' },
  { char: '群', pinyin: 'qún', strokeCount: 13, meaning: '一群', phrase: '群众', category: '数字' },
  { char: '竹', pinyin: 'zhú', strokeCount: 6, meaning: '竹子', phrase: '竹林', category: '植物' },
  { char: '用', pinyin: 'yòng', strokeCount: 5, meaning: '拿来做事情', phrase: '有用', category: '动作' },
  { char: '几', pinyin: 'jǐ', strokeCount: 2, meaning: '问多少时用，表示不多的数目', phrase: '几个', category: '数字' },
  { char: '步', pinyin: 'bù', strokeCount: 7, meaning: '脚动一下', phrase: '一步', category: '动作' },
  { char: '为', pinyin: 'wèi', strokeCount: 4, meaning: '表示原因或目的', phrase: '为什么', category: '动作' },
  { char: '参', pinyin: 'cān', strokeCount: 8, meaning: '参加', phrase: '参考', category: '动作' },
  { char: '加', pinyin: 'jiā', strokeCount: 5, meaning: '把两组数合在一起算；也指一起做事', phrase: '加法', category: '动作' },
  { char: '洞', pinyin: 'dòng', strokeCount: 9, meaning: '物体上凹进去或穿透的孔', phrase: '山洞', category: '自然' },
  { char: '乌', pinyin: 'wū', strokeCount: 4, meaning: '黑色；也用在鸟名里', phrase: '乌黑', category: '动物' },
  { char: '鸦', pinyin: 'yā', strokeCount: 9, meaning: '一种黑色的鸟', phrase: '寒鸦', category: '动物' },
  { char: '处', pinyin: 'chù', strokeCount: 5, meaning: '地方', phrase: '处处', category: '方位' },
  { char: '找', pinyin: 'zhǎo', strokeCount: 7, meaning: '为了得到而寻求', phrase: '寻找', category: '动作' },
  { char: '办', pinyin: 'bàn', strokeCount: 4, meaning: '做、处理事情', phrase: '办公', category: '动作' },
  { char: '许', pinyin: 'xǔ', strokeCount: 6, meaning: '答应、同意；也表示很多', phrase: '许可', category: '动作' },
  { char: '法', pinyin: 'fǎ', strokeCount: 8, meaning: '办法', phrase: '方法', category: '动作' },
  { char: '放', pinyin: 'fàng', strokeCount: 8, meaning: '把东西搁下；也指不限制', phrase: '放开', category: '动作' },
  { char: '进', pinyin: 'jìn', strokeCount: 7, meaning: '从外面到里面', phrase: '进步', category: '动作' },
  { char: '住', pinyin: 'zhù', strokeCount: 7, meaning: '长期生活在某个地方；也表示停下来', phrase: '住房', category: '动作' },
  { char: '孩', pinyin: 'hái', strokeCount: 9, meaning: '小娃娃、幼童', phrase: '女孩', category: '家庭' },
  { char: '玩', pinyin: 'wán', strokeCount: 8, meaning: '做游戏、开心地活动', phrase: '玩耍', category: '动作' },
  { char: '吧', pinyin: 'ba', strokeCount: 7, meaning: '放在句尾表示商量、建议', phrase: '走吧', category: '动作' },
  { char: '发', pinyin: 'fā', strokeCount: 5, meaning: '头上长的毛；也指送出、产生', phrase: '发现', category: '人体' },
  { char: '芽', pinyin: 'yá', strokeCount: 7, meaning: '植物刚长出来的嫩尖', phrase: '发芽', category: '植物' },
  { char: '爬', pinyin: 'pá', strokeCount: 8, meaning: '手脚着地往前移动', phrase: '爬虫', category: '动作' },
  { char: '呀', pinyin: 'ya', strokeCount: 7, meaning: '放在句尾表示感叹或惊讶', phrase: '好呀', category: '动作' },
  { char: '久', pinyin: 'jiǔ', strokeCount: 3, meaning: '时间很长', phrase: '不久', category: '时间' },
  { char: '回', pinyin: 'huí', strokeCount: 6, meaning: '从别处返程；也指转一圈', phrase: '回家', category: '动作' },
  { char: '全', pinyin: 'quán', strokeCount: 6, meaning: '所有的，一个都不少', phrase: '安全', category: '数字' },
  { char: '变', pinyin: 'biàn', strokeCount: 8, meaning: '和原来不一样了', phrase: '变大', category: '动作' },
  // —— 生字表补全中漏掉的两个字 ——
  { char: '小', pinyin: 'xiǎo', strokeCount: 3, meaning: '大小 / 小', phrase: '小猫小小', category: '动物' },
  { char: '高', pinyin: 'gāo', strokeCount: 10, meaning: '从下到上距离大', phrase: '高高大树', category: '方位' },

];

/** 在 RAW_CHARACTERS 基础上，把多音字的第二读音（MULTI_READINGS）派生到 altPinyin。
 *  这样识字卡 / 识字闯关就能展示「又读 xxx」，而无需改动 290 行的原始数据块。 */
export const CHARACTERS: CharacterItem[] = RAW_CHARACTERS.map((c) =>
  MULTI_READINGS[c.char] ? { ...c, altPinyin: MULTI_READINGS[c.char] } : c
);
