// 自动生成（按季拆分）：由 scripts/gen-moko-collection.js 生成，请勿手改。
import type { MokoChar } from '../../types';

export const mokoCollection_02: MokoChar[] = [
  {
    "key": "col_02_乖乖萌可_render",
    "name": "乖乖萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/乖乖萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，乖乖萌可在这里，咻咻~"
  },
  {
    "key": "col_02_仿仿萌可_render",
    "name": "仿仿萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/仿仿萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！仿仿萌可来啦！"
  },
  {
    "key": "col_02_倒倒萌可_render",
    "name": "倒倒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/倒倒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，倒倒萌可在这里，咻咻~"
  },
  {
    "key": "col_02_八卦萌可_render",
    "name": "八卦萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/八卦萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "八卦萌可登场，转转~"
  },
  {
    "key": "col_02_冰冰萌可_render",
    "name": "冰冰萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/冰冰萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，冰冰萌可在这里，咻咻~"
  },
  {
    "key": "col_02_冷冷萌可_render",
    "name": "冷冷萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/冷冷萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！冷冷萌可来啦！"
  },
  {
    "key": "col_02_厌厌萌可_render",
    "name": "厌厌萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/厌厌萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是厌厌萌可！"
  },
  {
    "key": "col_02_变身萌可_render",
    "name": "变身萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/变身萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，灵灵~ 我是变身萌可！"
  },
  {
    "key": "col_02_叹气萌可_render",
    "name": "叹气萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/叹气萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "叹气萌可登场，转转~"
  },
  {
    "key": "col_02_否否萌可_render",
    "name": "否否萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/否否萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，否否萌可在这里，咻咻~"
  },
  {
    "key": "col_02_好奇萌可_render",
    "name": "好奇萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/好奇萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，叮咚~ 我是好奇萌可！"
  },
  {
    "key": "col_02_妒妒萌可_render",
    "name": "妒妒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/妒妒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是妒妒萌可！"
  },
  {
    "key": "col_02_妖妖萌可_render",
    "name": "妖妖萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/妖妖萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，妖妖萌可在这里，咻咻~"
  },
  {
    "key": "col_02_娇娇萌可_render",
    "name": "娇娇萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/娇娇萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是娇娇萌可！"
  },
  {
    "key": "col_02_孤独萌可_render",
    "name": "孤独萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/孤独萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，孤独萌可在这里，闪闪~"
  },
  {
    "key": "col_02_宝宝萌可_render",
    "name": "宝宝萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/宝宝萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，宝宝萌可在这里，咻咻~"
  },
  {
    "key": "col_02_害羞萌可_render",
    "name": "害羞萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/害羞萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "今天也要开开心心哦，转转~ 我是害羞萌可！"
  },
  {
    "key": "col_02_幻幻萌可_render",
    "name": "幻幻萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/幻幻萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是幻幻萌可！"
  },
  {
    "key": "col_02_怒怒萌可_render",
    "name": "怒怒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/怒怒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！怒怒萌可来啦！"
  },
  {
    "key": "col_02_怕怕萌可_render",
    "name": "怕怕萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/怕怕萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！怕怕萌可来啦！"
  },
  {
    "key": "col_02_恋恋萌可_render",
    "name": "恋恋萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/恋恋萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！恋恋萌可来啦！"
  },
  {
    "key": "col_02_泪泪萌可_render",
    "name": "泪泪萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/泪泪萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！泪泪萌可来啦！"
  },
  {
    "key": "col_02_淘气萌可_render",
    "name": "淘气萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/淘气萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咔咔！淘气萌可来啦！"
  },
  {
    "key": "col_02_玩具萌可_render",
    "name": "玩具萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩具萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，玩具萌可在这里，噗噗~"
  },
  {
    "key": "col_02_玩玩萌可_render",
    "name": "玩玩萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩玩萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，玩玩萌可在这里，咻咻~"
  },
  {
    "key": "col_02_玩玩萌可_乐乐萌可_render",
    "name": "玩玩萌可·乐乐萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩玩萌可_乐乐萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "飘飘！玩玩萌可·乐乐萌可来啦！"
  },
  {
    "key": "col_02_电电萌可_render",
    "name": "电电萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/电电萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，电电萌可在这里，咻咻~"
  },
  {
    "key": "col_02_画画萌可_render",
    "name": "画画萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/画画萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，画画萌可在这里，咻咻~"
  },
  {
    "key": "col_02_睡睡萌可_render",
    "name": "睡睡萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/睡睡萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！睡睡萌可来啦！"
  },
  {
    "key": "col_02_美美萌可_render",
    "name": "美美萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/美美萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，美美萌可在这里，咻咻~"
  },
  {
    "key": "col_02_聪明萌可_render",
    "name": "聪明萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/聪明萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，飘飘~ 我是聪明萌可！"
  },
  {
    "key": "col_02_花花萌可_render",
    "name": "花花萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/花花萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是花花萌可！"
  },
  {
    "key": "col_02_贪贪萌可_render",
    "name": "贪贪萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/贪贪萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "咻咻！贪贪萌可来啦！"
  },
  {
    "key": "col_02_赛赛萌可_render",
    "name": "赛赛萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/赛赛萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是赛赛萌可！"
  },
  {
    "key": "col_02_迷糊萌可_render",
    "name": "迷糊萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/迷糊萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "灵灵~ 我是迷糊萌可！"
  },
  {
    "key": "col_02_速速萌可_render",
    "name": "速速萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/速速萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "来和我玩吧，咻咻~ 我是速速萌可！"
  },
  {
    "key": "col_02_重重萌可_render",
    "name": "重重萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/重重萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，重重萌可在这里，咻咻~"
  },
  {
    "key": "col_02_黏黏萌可_render",
    "name": "黏黏萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/黏黏萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "呼呼，黏黏萌可在这里，咻咻~"
  }
];
