// 自动生成（按季拆分）：由 scripts/gen-moko-collection.js 生成，请勿手改。
import type { MokoChar } from '../../types';

export const mokoCollection_02: MokoChar[] = [
  {
    "key": "col_02_乖乖萌可_render",
    "name": "乖乖萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/乖乖萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "乖乖~ 我是乖乖萌可，规矩最棒！"
  },
  {
    "key": "col_02_仿仿萌可_render",
    "name": "仿仿萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/仿仿萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "仿仿~ 我是仿仿萌可，变身大师！"
  },
  {
    "key": "col_02_倒倒萌可_render",
    "name": "倒倒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/倒倒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "倒倒~ 我是倒倒萌可，反着也行！"
  },
  {
    "key": "col_02_八卦萌可_render",
    "name": "八卦萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/八卦萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "八卦~ 我是八卦萌可，谜题通通破！"
  },
  {
    "key": "col_02_冰冰萌可_render",
    "name": "冰冰萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/冰冰萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "冰冰~ 我是冰冰萌可，冷静实验家！"
  },
  {
    "key": "col_02_冷冷萌可_render",
    "name": "冷冷萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/冷冷萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "冷冷~ 我是冷冷萌可，揭秘小能手！"
  },
  {
    "key": "col_02_厌厌萌可_render",
    "name": "厌厌萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/厌厌萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "厌厌~ 我是厌厌萌可，变聪明秘诀！"
  },
  {
    "key": "col_02_变身萌可_render",
    "name": "变身萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/变身萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "变身~ 我是变身萌可，魔法变变变！"
  },
  {
    "key": "col_02_叹气萌可_render",
    "name": "叹气萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/叹气萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "叹气~ 我是叹气萌可，小窍门大全！"
  },
  {
    "key": "col_02_否否萌可_render",
    "name": "否否萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/否否萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "否否~ 我是否否萌可，想办法高手！"
  },
  {
    "key": "col_02_好奇萌可_render",
    "name": "好奇萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/好奇萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "好奇~ 我是好奇萌可，动脑筋探险！"
  },
  {
    "key": "col_02_妒妒萌可_render",
    "name": "妒妒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/妒妒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "妒妒~ 我是妒妒萌可，探索不停歇！"
  },
  {
    "key": "col_02_妖妖萌可_render",
    "name": "妖妖萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/妖妖萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "妖妖~ 我是妖妖萌可，手工达人秀！"
  },
  {
    "key": "col_02_娇娇萌可_render",
    "name": "娇娇萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/娇娇萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "娇娇~ 我是娇娇萌可，搭积木小王！"
  },
  {
    "key": "col_02_孤独萌可_render",
    "name": "孤独萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/孤独萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "孤独~ 我是孤独萌可，科学小博士！"
  },
  {
    "key": "col_02_宝宝萌可_render",
    "name": "宝宝萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/宝宝萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "宝宝~ 我是宝宝萌可，观察眼最亮！"
  },
  {
    "key": "col_02_害羞萌可_render",
    "name": "害羞萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/害羞萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "害羞~ 我是害羞萌可，游戏教给你！"
  },
  {
    "key": "col_02_幻幻萌可_render",
    "name": "幻幻萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/幻幻萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "幻幻~ 我是幻幻萌可，猜谜语冠军！"
  },
  {
    "key": "col_02_怒怒萌可_render",
    "name": "怒怒萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/怒怒萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "怒怒~ 我是怒怒萌可，逻辑最厉害！"
  },
  {
    "key": "col_02_怕怕萌可_render",
    "name": "怕怕萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/怕怕萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "怕怕~ 我是怕怕萌可，思考小能手！"
  },
  {
    "key": "col_02_恋恋萌可_render",
    "name": "恋恋萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/恋恋萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "恋恋~ 我是恋恋萌可，魔方玩得溜！"
  },
  {
    "key": "col_02_泪泪萌可_render",
    "name": "泪泪萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/泪泪萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "泪泪~ 我是泪泪萌可，手工教给你！"
  },
  {
    "key": "col_02_淘气萌可_render",
    "name": "淘气萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/淘气萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "淘气~ 我是淘气萌可，捣蛋锤挥舞！"
  },
  {
    "key": "col_02_玩具萌可_render",
    "name": "玩具萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩具萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "玩具~ 我是玩具萌可，魔术变变变！"
  },
  {
    "key": "col_02_玩玩萌可_render",
    "name": "玩玩萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩玩萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "玩玩~ 我是玩玩萌可，模型搭得高！"
  },
  {
    "key": "col_02_玩玩萌可_乐乐萌可_render",
    "name": "玩玩萌可·乐乐萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/玩玩萌可_乐乐萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "飘飘！我是玩玩萌可·乐乐萌可，双倍快乐！"
  },
  {
    "key": "col_02_电电萌可_render",
    "name": "电电萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/电电萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "电电~ 我是电电萌可，科学实验家！"
  },
  {
    "key": "col_02_画画萌可_render",
    "name": "画画萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/画画萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "画画~ 我是画画萌可，编程小画家！"
  },
  {
    "key": "col_02_睡睡萌可_render",
    "name": "睡睡萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/睡睡萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "睡睡~ 我是睡睡萌可，机器人梦工厂！"
  },
  {
    "key": "col_02_美美萌可_render",
    "name": "美美萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/美美萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "美美~ 我是美美萌可，电子小达人！"
  },
  {
    "key": "col_02_聪明萌可_render",
    "name": "聪明萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/聪明萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "聪明~ 我是聪明萌可，电路设计师！"
  },
  {
    "key": "col_02_花花萌可_render",
    "name": "花花萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/花花萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "花花~ 我是花花萌可，3D打印魔法！"
  },
  {
    "key": "col_02_贪贪萌可_render",
    "name": "贪贪萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/贪贪萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "贪贪~ 我是贪贪萌可，木工小匠人！"
  },
  {
    "key": "col_02_赛赛萌可_render",
    "name": "赛赛萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/赛赛萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "赛赛~ 我是赛赛萌可，绘画小天才！"
  },
  {
    "key": "col_02_迷糊萌可_render",
    "name": "迷糊萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/迷糊萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "迷糊~ 我是迷糊萌可，币币去哪啦！"
  },
  {
    "key": "col_02_速速萌可_render",
    "name": "速速萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/速速萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "速速~ 我是速速萌可，视频剪辑快！"
  },
  {
    "key": "col_02_重重萌可_render",
    "name": "重重萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/重重萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "重重~ 我是重重萌可，动画制作家！"
  },
  {
    "key": "col_02_黏黏萌可_render",
    "name": "黏黏萌可",
    "category": "mo",
    "season": "魔方萌可_第一二季",
    "img": "/moko/collection/02_魔方萌可_第一二季/黏黏萌可_render.webp",
    "emoji": "🧊",
    "color": "text-moko-cyan",
    "item": "✨ 魔法道具",
    "line": "黏黏~ 我是黏黏萌可，乐器拉得好！"
  }
];
